In [254]:
import pandas as pd
import numpy as np

In [255]:
df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Data_Train.csv")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [256]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [257]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [258]:
df["Airline"].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [259]:
df["Airline"].isna().sum()

np.int64(0)

In [260]:
# Data to collect:
# Airline
# Source
# Destination
# Departure
# Arrival
# Duration
# Total stops
# Price
# Date of journey


# droping the remaining col

df.drop("Route", axis=1, inplace=True)
df.drop("Additional_Info", axis=1, inplace=True)

In [261]:
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,non-stop,3897
1,Air India,1/05/2019,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,09:25,04:25 10 Jun,19h,2 stops,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,13302
...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,19:55,22:25,2h 30m,non-stop,4107
10679,Air India,27/04/2019,Kolkata,Banglore,20:45,23:20,2h 35m,non-stop,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,08:20,11:20,3h,non-stop,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,11:30,14:10,2h 40m,non-stop,12648
10682,Air India,9/05/2019,Delhi,Cochin,10:55,19:15,8h 20m,2 stops,11753

## Date_of_Journey

In [262]:
df["Date_of_Journey"].isna().sum()

np.int64(0)

In [263]:
df["Date_of_Journey"].dtypes

dtype('O')

In [264]:
df["Date_of_Journey"]=pd.to_datetime(df["Date_of_Journey"],dayfirst=True)
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price
0,IndiGo,2019-03-24,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,non-stop,3897
1,Air India,2019-05-01,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,7662
2,Jet Airways,2019-06-09,Delhi,Cochin,09:25,04:25 10 Jun,19h,2 stops,13882
3,IndiGo,2019-05-12,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,6218
4,IndiGo,2019-03-01,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,13302
...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,19:55,22:25,2h 30m,non-stop,4107
10679,Air India,2019-04-27,Kolkata,Banglore,20:45,23:20,2h 35m,non-stop,4145
10680,Jet Airways,2019-04-27,Banglore,Delhi,08:20,11:20,3h,non-stop,7229
10681,Vistara,2019-03-01,Banglore,New Delhi,11:30,14:10,2h 40m,non-stop,12648
10682,Air India,2019-05-09,Delhi,Cochin,10:55,19:15,8h 20m,2 stops,11753

In [265]:
df["Date_of_Journey"].dtypes

dtype('<M8[ns]')

## Source

In [266]:
df["Source"].isna().sum()

np.int64(0)

In [267]:
df["Source"].value_counts()

Source
Delhi       4537
Kolkata     2871
Banglore    2197
Mumbai       697
Chennai      381
Name: count, dtype: int64

In [268]:
df["Source"].unique()

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

## Destination

In [269]:
df["Destination"].isna().sum()

np.int64(0)

In [270]:
df["Destination"].unique()

array(['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad'],
      dtype=object)

In [271]:
df=df.replace({"Destination":{"New Delhi":"Delhi"}})

In [272]:
df["Destination"].unique()

array(['Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Hyderabad'],
      dtype=object)

In [273]:
df["Destination"].value_counts()

Destination
Cochin       4537
Banglore     2871
Delhi        2197
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

## Dep_Time

In [274]:
df["Dep_Time"].isna().sum()

np.int64(0)

In [275]:
df["Dep_Time"].dtypes

dtype('O')

In [276]:
df["Dep_Time"].unique()

array(['22:20', '05:50', '09:25', '18:05', '16:50', '09:00', '18:55',
       '08:00', '08:55', '11:25', '09:45', '20:20', '11:40', '21:10',
       '17:15', '16:40', '08:45', '14:00', '20:15', '16:00', '14:10',
       '22:00', '04:00', '21:25', '21:50', '07:00', '07:05', '09:50',
       '14:35', '10:35', '15:05', '14:15', '06:45', '20:55', '11:10',
       '05:45', '19:00', '23:05', '11:00', '09:35', '21:15', '23:55',
       '19:45', '08:50', '15:40', '06:05', '15:00', '13:55', '05:55',
       '13:20', '05:05', '06:25', '17:30', '08:20', '19:55', '06:30',
       '14:05', '02:00', '09:40', '08:25', '20:25', '13:15', '02:15',
       '16:55', '20:45', '05:15', '19:50', '20:00', '06:10', '19:30',
       '04:45', '12:55', '18:15', '17:20', '15:25', '23:00', '12:00',
       '14:45', '11:50', '11:30', '14:40', '19:10', '06:00', '23:30',
       '07:35', '13:05', '12:30', '15:10', '12:50', '18:25', '16:30',
       '00:40', '06:50', '13:00', '19:15', '01:30', '17:00', '10:00',
       '19:35', '15:30', '12:10', '16:10', '20:35', '22:25', '21:05',
       '05:35', '05:10', '06:40', '15:15', '00:30', '08:30', '07:10',
       '05:30', '14:25', '05:25', '10:20', '17:45', '13:10', '22:10',
       '04:55', '17:50', '21:20', '06:20', '15:55', '20:30', '17:25',
       '09:30', '07:30', '02:35', '10:55', '17:10', '09:10', '18:45',
       '15:20', '22:50', '14:55', '14:20', '13:25', '22:15', '11:05',
       '16:15', '20:10', '06:55', '19:05', '07:55', '07:45', '10:10',
       '08:15', '11:35', '21:00', '17:55', '16:45', '18:20', '03:50',
       '08:35', '19:20', '20:05', '17:40', '04:40', '17:35', '09:55',
       '05:00', '18:00', '02:55', '20:40', '22:55', '22:40', '21:30',
       '08:10', '17:05', '07:25', '15:45', '09:15', '15:50', '11:45',
       '22:05', '18:35', '00:25', '19:40', '20:50', '22:45', '10:30',
       '23:25', '11:55', '10:45', '11:15', '12:20', '14:30', '07:15',
       '01:35', '18:40', '09:20', '21:55', '13:50', '01:40', '00:20',
       '04:15', '13:45', '18:30', '06:15', '02:05', '12:15', '13:30',
       '06:35', '10:05', '08:40', '03:05', '21:35', '16:35', '02:30',
       '16:25', '05:40', '15:35', '13:40', '07:20', '04:50', '12:45',
       '10:25', '12:05', '11:20', '21:40', '03:00'], dtype=object)

In [277]:
df["Dep_Time"]= pd.to_datetime(df["Dep_Time"], format= "%H:%M")

In [278]:
df["Dep_Time"] = df["Dep_Time"].dt.strftime("%H:%M")

In [279]:
df["Dep_Time"].value_counts()

Dep_Time
18:55    233
17:00    227
07:05    205
10:00    203
07:10    202
        ...
16:25      1
01:35      1
21:35      1
04:15      1
03:00      1
Name: count, Length: 222, dtype: int64

In [280]:
df["Dep_Time"].dtypes

dtype('O')

## Arrival_Time

In [281]:
df["Arrival_Time"].isna().sum()

np.int64(0)

In [282]:
df["Arrival_Time"].dtypes

dtype('O')

In [283]:
df["Arrival_Time"].value_counts()

Arrival_Time
19:00           423
21:00           360
19:15           333
16:10           154
12:35           122
               ...
00:25 02 Jun      1
08:55 13 Mar      1
11:05 19 May      1
12:30 22 May      1
21:20 13 Mar      1
Name: count, Length: 1343, dtype: int64

In [284]:
df["Arrival_Time"].unique()

array(['01:10 22 Mar', '13:15', '04:25 10 Jun', ..., '06:50 10 Mar',
       '00:05 19 Mar', '21:20 13 Mar'], shape=(1343,), dtype=object)

In [285]:
df["Arrival_Time"] = df["Arrival_Time"].str[:5]

In [286]:
df["Arrival_Time"]= pd.to_datetime(df["Arrival_Time"], format="%H:%M")

In [287]:
df["Arrival_Time"] = df["Arrival_Time"].dt.strftime("%H:%M")

In [288]:
df["Arrival_Time"].unique()

array(['01:10', '13:15', '04:25', '23:30', '21:35', '11:25', '10:25',
       '05:05', '19:15', '23:00', '22:55', '13:55', '09:20', '19:50',
       '12:35', '19:20', '13:20', '06:50', '21:50', '08:15', '03:35',
       '12:55', '23:15', '21:00', '20:20', '16:45', '19:00', '18:10',
       '15:15', '08:35', '11:05', '14:15', '10:55', '00:15', '02:45',
       '12:00', '23:55', '01:30', '09:25', '15:25', '15:35', '08:30',
       '10:05', '14:30', '07:55', '10:35', '22:35', '04:40', '07:25',
       '20:45', '14:25', '22:30', '23:20', '07:40', '22:50', '14:35',
       '08:55', '18:50', '09:05', '01:35', '09:40', '16:25', '11:10',
       '17:05', '17:50', '23:10', '08:45', '07:45', '16:10', '00:55',
       '23:35', '20:00', '00:40', '21:45', '18:15', '03:25', '04:15',
       '21:10', '21:05', '09:45', '18:05', '22:00', '15:30', '08:50',
       '08:00', '19:35', '11:20', '10:15', '12:45', '02:20', '07:15',
       '11:50', '18:30', '19:45', '21:20', '20:05', '09:10', '22:20',
       '10:10', '01:00', '23:50', '12:20', '20:25', '22:45', '21:25',
       '14:05', '00:05', '19:55', '16:20', '07:05', '19:10', '12:05',
       '04:05', '19:40', '17:55', '17:25', '00:30', '23:40', '23:05',
       '00:50', '13:45', '09:15', '20:35', '07:10', '09:35', '14:20',
       '04:45', '10:30', '19:25', '05:35', '09:00', '22:40', '14:45',
       '13:25', '21:55', '10:45', '10:40', '13:00', '22:10', '18:35',
       '05:25', '22:15', '12:10', '12:15', '14:00', '02:15', '12:50',
       '17:15', '07:35', '23:45', '22:25', '12:25', '06:35', '01:20',
       '18:45', '09:30', '04:20', '10:50', '23:25', '22:05', '13:30',
       '13:35', '17:35', '08:20', '18:25', '10:20', '15:50', '11:30',
       '14:10', '00:25', '03:15', '15:55', '00:45', '04:35', '18:00',
       '12:30', '02:10', '00:20', '21:40', '08:40', '16:55', '20:30',
       '17:20', '00:35', '20:15', '14:50', '13:40', '16:50', '15:05',
       '17:45', '18:40', '03:10', '16:40', '09:50', '13:05', '17:40',
       '20:40', '17:10', '20:50', '00:10', '08:10', '16:15', '16:05',
       '10:00', '16:35', '18:20', '04:00', '21:15', '14:40', '01:45',
       '16:30', '11:55', '15:20', '20:10', '15:00', '15:45', '12:40',
       '15:10', '13:10', '11:15', '03:40', '16:00', '11:35'], dtype=object)

## Duration

In [289]:
df["Duration"].isna().sum()

np.int64(0)

In [290]:
df["Duration"].unique()

array(['2h 50m', '7h 25m', '19h', '5h 25m', '4h 45m', '2h 25m', '15h 30m',
       '21h 5m', '25h 30m', '7h 50m', '13h 15m', '2h 35m', '2h 15m',
       '12h 10m', '26h 35m', '4h 30m', '22h 35m', '23h', '20h 35m',
       '5h 10m', '15h 20m', '2h 55m', '13h 20m', '15h 10m', '5h 45m',
       '5h 55m', '13h 25m', '22h', '5h 30m', '10h 25m', '5h 15m',
       '2h 30m', '6h 15m', '11h 55m', '11h 5m', '8h 30m', '22h 5m',
       '2h 45m', '12h', '16h 5m', '19h 55m', '3h 15m', '25h 20m', '3h',
       '16h 15m', '15h 5m', '6h 30m', '25h 5m', '12h 25m', '27h 20m',
       '10h 15m', '10h 30m', '1h 30m', '1h 25m', '26h 30m', '7h 20m',
       '13h 30m', '5h', '19h 5m', '14h 50m', '2h 40m', '22h 10m',
       '9h 35m', '10h', '21h 20m', '18h 45m', '12h 20m', '18h', '9h 15m',
       '17h 30m', '16h 35m', '12h 15m', '7h 30m', '24h', '8h 55m',
       '7h 10m', '14h 30m', '30h 20m', '15h', '12h 45m', '10h 10m',
       '15h 25m', '14h 5m', '20h 15m', '23h 10m', '18h 10m', '16h',
       '2h 20m', '8h', '16h 55m', '3h 10m', '14h', '23h 50m', '21h 40m',
       '21h 15m', '10h 50m', '8h 15m', '8h 35m', '11h 50m', '27h 35m',
       '8h 25m', '20h 55m', '4h 50m', '8h 10m', '24h 25m', '23h 35m',
       '25h 45m', '26h 10m', '28h 50m', '25h 15m', '9h 20m', '9h 10m',
       '3h 5m', '11h 30m', '9h 30m', '17h 35m', '5h 5m', '25h 50m', '20h',
       '13h', '18h 25m', '24h 10m', '4h 55m', '25h 35m', '6h 20m',
       '18h 40m', '19h 25m', '29h 20m', '9h 5m', '10h 45m', '11h 40m',
       '22h 55m', '37h 25m', '25h 40m', '13h 55m', '8h 40m', '23h 30m',
       '12h 35m', '24h 15m', '1h 20m', '11h', '11h 15m', '14h 35m',
       '12h 55m', '9h', '7h 40m', '11h 45m', '24h 55m', '17h 5m',
       '29h 55m', '22h 15m', '14h 40m', '7h 15m', '20h 10m', '20h 45m',
       '27h', '24h 30m', '20h 25m', '5h 35m', '14h 45m', '5h 40m',
       '4h 5m', '15h 55m', '7h 45m', '28h 20m', '4h 20m', '3h 40m',
       '8h 50m', '23h 45m', '24h 45m', '21h 35m', '8h 5m', '6h 25m',
       '15h 50m', '26h 25m', '24h 50m', '26h', '23h 5m', '7h 55m',
       '26h 20m', '23h 15m', '5h 20m', '4h', '9h 45m', '8h 20m',
       '17h 25m', '7h 5m', '34h 5m', '6h 5m', '5h 50m', '7h', '4h 25m',
       '13h 45m', '19h 15m', '22h 30m', '16h 25m', '13h 50m', '27h 5m',
       '28h 10m', '4h 40m', '15h 40m', '4h 35m', '18h 30m', '38h 15m',
       '6h 35m', '12h 30m', '11h 20m', '7h 35m', '29h 35m', '26h 55m',
       '23h 40m', '12h 50m', '9h 50m', '21h 55m', '10h 55m', '21h 10m',
       '20h 40m', '30h', '13h 10m', '8h 45m', '6h 10m', '17h 45m',
       '21h 45m', '3h 55m', '17h 20m', '30h 30m', '21h 25m', '12h 40m',
       '24h 35m', '19h 10m', '22h 40m', '14h 55m', '21h', '6h 45m',
       '28h 40m', '9h 40m', '16h 40m', '16h 20m', '16h 45m', '1h 15m',
       '6h 55m', '11h 25m', '14h 20m', '12h 5m', '24h 5m', '28h 15m',
       '17h 50m', '20h 20m', '28h 5m', '10h 20m', '14h 15m', '35h 15m',
       '35h 35m', '26h 40m', '28h', '14h 25m', '13h 5m', '37h 20m',
       '36h 10m', '25h 55m', '35h 5m', '19h 45m', '27h 55m', '47h',
       '10h 35m', '1h 35m', '16h 10m', '38h 20m', '6h', '16h 50m',
       '14h 10m', '23h 20m', '17h 40m', '11h 35m', '18h 20m', '6h 40m',
       '30h 55m', '24h 40m', '29h 50m', '28h 25m', '17h 15m', '22h 45m',
       '25h 25m', '21h 50m', '33h 15m', '30h 15m', '3h 35m', '27h 40m',
       '30h 25m', '18h 50m', '27h 45m', '15h 15m', '10h 40m', '26h 15m',
       '36h 25m', '26h 50m', '15h 45m', '19h 40m', '22h 25m', '19h 35m',
       '25h', '26h 45m', '38h', '4h 15m', '25h 10m', '18h 15m', '6h 50m',
       '23h 55m', '17h 55m', '23h 25m', '17h 10m', '24h 20m', '28h 30m',
       '27h 10m', '19h 20m', '15h 35m', '9h 25m', '21h 30m', '34h 25m',
       '18h 35m', '29h 40m', '26h 5m', '29h 5m', '27h 25m', '16h 30m',
       '11h 10m', '28h 55m', '29h 10m', '34h', '30h 40m', '30h 45m',
       '32h 55m', '10h 5m', '35h 20m', '32h 5m', '31h 40m', '19h 50m',
       '33h 45m', '30h 10m', '13h 40m', '19h 30m', '31h 30m', '34h 30m',
       '27h 50m', '38h 35m', '42h 5m', '4h 10m', '39h 5m', '3h 50m', '5m',
       '32h 30m', '31h 55m', '33h 20m', '27h 30m', '18h 55m', '9h 55m',
       '41h 20m', '20h 5m', '31h 50m', '42h 45m', '3h 25m', '37h 10m',
       '29h 30m', '32h 20m', '20h 50m', '40h 20m', '13h 35m', '47h 40m'],
      dtype=object)

In [291]:
df["Duration"] = (
    df["Duration"]
    .str.replace("h ", ":", regex=False)
    .str.replace("h", ":00", regex=False)
    .str.replace("m", "", regex=False)
)

In [292]:
df["Duration"].unique()

array(['2:50', '7:25', '19:00', '5:25', '4:45', '2:25', '15:30', '21:5',
       '25:30', '7:50', '13:15', '2:35', '2:15', '12:10', '26:35', '4:30',
       '22:35', '23:00', '20:35', '5:10', '15:20', '2:55', '13:20',
       '15:10', '5:45', '5:55', '13:25', '22:00', '5:30', '10:25', '5:15',
       '2:30', '6:15', '11:55', '11:5', '8:30', '22:5', '2:45', '12:00',
       '16:5', '19:55', '3:15', '25:20', '3:00', '16:15', '15:5', '6:30',
       '25:5', '12:25', '27:20', '10:15', '10:30', '1:30', '1:25',
       '26:30', '7:20', '13:30', '5:00', '19:5', '14:50', '2:40', '22:10',
       '9:35', '10:00', '21:20', '18:45', '12:20', '18:00', '9:15',
       '17:30', '16:35', '12:15', '7:30', '24:00', '8:55', '7:10',
       '14:30', '30:20', '15:00', '12:45', '10:10', '15:25', '14:5',
       '20:15', '23:10', '18:10', '16:00', '2:20', '8:00', '16:55',
       '3:10', '14:00', '23:50', '21:40', '21:15', '10:50', '8:15',
       '8:35', '11:50', '27:35', '8:25', '20:55', '4:50', '8:10', '24:25',
       '23:35', '25:45', '26:10', '28:50', '25:15', '9:20', '9:10', '3:5',
       '11:30', '9:30', '17:35', '5:5', '25:50', '20:00', '13:00',
       '18:25', '24:10', '4:55', '25:35', '6:20', '18:40', '19:25',
       '29:20', '9:5', '10:45', '11:40', '22:55', '37:25', '25:40',
       '13:55', '8:40', '23:30', '12:35', '24:15', '1:20', '11:00',
       '11:15', '14:35', '12:55', '9:00', '7:40', '11:45', '24:55',
       '17:5', '29:55', '22:15', '14:40', '7:15', '20:10', '20:45',
       '27:00', '24:30', '20:25', '5:35', '14:45', '5:40', '4:5', '15:55',
       '7:45', '28:20', '4:20', '3:40', '8:50', '23:45', '24:45', '21:35',
       '8:5', '6:25', '15:50', '26:25', '24:50', '26:00', '23:5', '7:55',
       '26:20', '23:15', '5:20', '4:00', '9:45', '8:20', '17:25', '7:5',
       '34:5', '6:5', '5:50', '7:00', '4:25', '13:45', '19:15', '22:30',
       '16:25', '13:50', '27:5', '28:10', '4:40', '15:40', '4:35',
       '18:30', '38:15', '6:35', '12:30', '11:20', '7:35', '29:35',
       '26:55', '23:40', '12:50', '9:50', '21:55', '10:55', '21:10',
       '20:40', '30:00', '13:10', '8:45', '6:10', '17:45', '21:45',
       '3:55', '17:20', '30:30', '21:25', '12:40', '24:35', '19:10',
       '22:40', '14:55', '21:00', '6:45', '28:40', '9:40', '16:40',
       '16:20', '16:45', '1:15', '6:55', '11:25', '14:20', '12:5', '24:5',
       '28:15', '17:50', '20:20', '28:5', '10:20', '14:15', '35:15',
       '35:35', '26:40', '28:00', '14:25', '13:5', '37:20', '36:10',
       '25:55', '35:5', '19:45', '27:55', '47:00', '10:35', '1:35',
       '16:10', '38:20', '6:00', '16:50', '14:10', '23:20', '17:40',
       '11:35', '18:20', '6:40', '30:55', '24:40', '29:50', '28:25',
       '17:15', '22:45', '25:25', '21:50', '33:15', '30:15', '3:35',
       '27:40', '30:25', '18:50', '27:45', '15:15', '10:40', '26:15',
       '36:25', '26:50', '15:45', '19:40', '22:25', '19:35', '25:00',
       '26:45', '38:00', '4:15', '25:10', '18:15', '6:50', '23:55',
       '17:55', '23:25', '17:10', '24:20', '28:30', '27:10', '19:20',
       '15:35', '9:25', '21:30', '34:25', '18:35', '29:40', '26:5',
       '29:5', '27:25', '16:30', '11:10', '28:55', '29:10', '34:00',
       '30:40', '30:45', '32:55', '10:5', '35:20', '32:5', '31:40',
       '19:50', '33:45', '30:10', '13:40', '19:30', '31:30', '34:30',
       '27:50', '38:35', '42:5', '4:10', '39:5', '3:50', '5', '32:30',
       '31:55', '33:20', '27:30', '18:55', '9:55', '41:20', '20:5',
       '31:50', '42:45', '3:25', '37:10', '29:30', '32:20', '20:50',
       '40:20', '13:35', '47:40'], dtype=object)

In [293]:
df["Duration"]= pd.to_datetime(df["Duration"],errors ='coerce')

C:\Users\bhoom\AppData\Local\Temp\ipykernel_28012\1522469968.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Duration"]= pd.to_datetime(df["Duration"],errors ='coerce')

In [294]:
df["Duration"] = df["Duration"].dt.strftime("%H:%M")

In [295]:
df["Duration_HR"] = df["Duration"].str.split(":").str[0]
df["Duration_MIN"] = df["Duration"].str.split(":").str[1]

In [296]:
df["Duration_HR"] = pd.to_numeric(df["Duration_HR"],errors = 'coerce')

In [297]:
df["Duration_HR"].fillna(0,inplace = True)

C:\Users\bhoom\AppData\Local\Temp\ipykernel_28012\2265744680.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Duration_HR"].fillna(0,inplace = True)

In [298]:
df["Duration_HR"].astype('int')

0         2
1         7
2        19
3         5
4         4
         ..
10678     2
10679     2
10680     3
10681     2
10682     8
Name: Duration_HR, Length: 10683, dtype: int64

In [299]:
df["Duration_MIN"].fillna(0,inplace = True)

C:\Users\bhoom\AppData\Local\Temp\ipykernel_28012\1417406700.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Duration_MIN"].fillna(0,inplace = True)

In [300]:
df["Duration_MIN"].astype('int')

0        50
1        25
2         0
3        25
4        45
         ..
10678    30
10679    35
10680     0
10681    40
10682    20
Name: Duration_MIN, Length: 10683, dtype: int64

In [301]:
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Duration_HR,Duration_MIN
0,IndiGo,2019-03-24,Banglore,Delhi,22:20,01:10,02:50,non-stop,3897,2.0,50
1,Air India,2019-05-01,Kolkata,Banglore,05:50,13:15,07:25,2 stops,7662,7.0,25
2,Jet Airways,2019-06-09,Delhi,Cochin,09:25,04:25,19:00,2 stops,13882,19.0,00
3,IndiGo,2019-05-12,Kolkata,Banglore,18:05,23:30,05:25,1 stop,6218,5.0,25
4,IndiGo,2019-03-01,Banglore,Delhi,16:50,21:35,04:45,1 stop,13302,4.0,45
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,19:55,22:25,02:30,non-stop,4107,2.0,30
10679,Air India,2019-04-27,Kolkata,Banglore,20:45,23:20,02:35,non-stop,4145,2.0,35
10680,Jet Airways,2019-04-27,Banglore,Delhi,08:20,11:20,03:00,non-stop,7229,3.0,00
10681,Vistara,2019-03-01,Banglore,Delhi,11:30,14:10,02:40,non-stop,12648,2.0,40
10682,Air India,2019-05-09,Delhi,Cochin,10:55,19:15,08:20,2 stops,11753,8.0,20

In [303]:
df["Duration"].isna().sum()

np.int64(1668)

In [304]:
df=df.dropna(subset=["Duration"])

In [305]:
df["Duration"].isna().sum()

np.int64(0)

In [306]:
df["Duration_HR"].isna().sum()

np.int64(0)

In [307]:
df["Duration_MIN"].isna().sum()

np.int64(0)

In [308]:
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Duration_HR,Duration_MIN
0,IndiGo,2019-03-24,Banglore,Delhi,22:20,01:10,02:50,non-stop,3897,2.0,50
1,Air India,2019-05-01,Kolkata,Banglore,05:50,13:15,07:25,2 stops,7662,7.0,25
2,Jet Airways,2019-06-09,Delhi,Cochin,09:25,04:25,19:00,2 stops,13882,19.0,00
3,IndiGo,2019-05-12,Kolkata,Banglore,18:05,23:30,05:25,1 stop,6218,5.0,25
4,IndiGo,2019-03-01,Banglore,Delhi,16:50,21:35,04:45,1 stop,13302,4.0,45
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,19:55,22:25,02:30,non-stop,4107,2.0,30
10679,Air India,2019-04-27,Kolkata,Banglore,20:45,23:20,02:35,non-stop,4145,2.0,35
10680,Jet Airways,2019-04-27,Banglore,Delhi,08:20,11:20,03:00,non-stop,7229,3.0,00
10681,Vistara,2019-03-01,Banglore,Delhi,11:30,14:10,02:40,non-stop,12648,2.0,40
10682,Air India,2019-05-09,Delhi,Cochin,10:55,19:15,08:20,2 stops,11753,8.0,20

## Total_Stops

In [309]:
df["Total_Stops"].isna().sum()

np.int64(1)

In [310]:
df=df.dropna(subset=["Total_Stops"])

In [311]:
df["Total_Stops"].isna().sum()

np.int64(0)

In [312]:
df["Total_Stops"].value_counts()

Total_Stops
1 stop      4626
non-stop    3413
2 stops      959
3 stops       16
Name: count, dtype: int64

In [316]:
df["Total_Stops"]= df["Total_Stops"].replace({"1 stop":1,
                                              "non-stop":0,
                                              "2 stops":2,
                                              "3 stops":3})

C:\Users\bhoom\AppData\Local\Temp\ipykernel_28012\3281133807.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Total_Stops"]= df["Total_Stops"].replace({"1 stop":1,
C:\Users\bhoom\AppData\Local\Temp\ipykernel_28012\3281133807.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total_Stops"]= df["Total_Stops"].replace({"1 stop":1,

In [317]:
df["Total_Stops"].value_counts()

Total_Stops
1    4626
0    3413
2     959
3      16
Name: count, dtype: int64

In [318]:
df["Total_Stops"].dtypes

dtype('int64')

## Price

In [319]:
df["Price"].isna().sum()

np.int64(0)

In [320]:
df["Price"].value_counts()

Price
10262    202
4804     160
10844    142
7229     141
4823     130
        ...
11386      1
6251       1
11260      1
5642       1
12648      1
Name: count, Length: 1629, dtype: int64

In [321]:
df["Price"].dtypes

dtype('int64')

In [322]:
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Duration_HR,Duration_MIN
0,IndiGo,2019-03-24,Banglore,Delhi,22:20,01:10,02:50,0,3897,2.0,50
1,Air India,2019-05-01,Kolkata,Banglore,05:50,13:15,07:25,2,7662,7.0,25
2,Jet Airways,2019-06-09,Delhi,Cochin,09:25,04:25,19:00,2,13882,19.0,00
3,IndiGo,2019-05-12,Kolkata,Banglore,18:05,23:30,05:25,1,6218,5.0,25
4,IndiGo,2019-03-01,Banglore,Delhi,16:50,21:35,04:45,1,13302,4.0,45
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,19:55,22:25,02:30,0,4107,2.0,30
10679,Air India,2019-04-27,Kolkata,Banglore,20:45,23:20,02:35,0,4145,2.0,35
10680,Jet Airways,2019-04-27,Banglore,Delhi,08:20,11:20,03:00,0,7229,3.0,00
10681,Vistara,2019-03-01,Banglore,Delhi,11:30,14:10,02:40,0,12648,2.0,40
10682,Air India,2019-05-09,Delhi,Cochin,10:55,19:15,08:20,2,11753,8.0,20

In [323]:
df.to_csv("Airline_Analysis_cleaned_data.csv", index=False)