In [3]:
# 1. Data Quality Audit
# Perform a complete audit of the dataset:
# • shape
# • datatypes
# • missing values
# • duplicate records
# • unique vehicle IDs
# • categorical distributions
# Identify every data-quality problem before modifying the dataset.

import pandas as pd
df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\EV_Resale_Price_Regression - EV_Resale_Price_Regression.csv")
df.head()

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760
2,EV-20654,2025-01-03,2019,Nexora,Crossover,53.9,91.2,NaN,12003.0000,3.6,Yes,1,Chennai,Complete,1830249
3,EV-20935,2025-01-04,2022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.0000,7.8,Yes,2,Delhi,Complete,1726422
4,EV-20827,2025-01-05,2024,GreenDrive,Sedan,53.0,92.0,264.0,28548.0000,6.1,No,1,Pune,Complete,1642232

In [17]:
df.shape

(1000, 15)

In [18]:
df.dtypes

vehicle_id               object
listing_date             object
manufacture_year          int64
brand                    object
vehicle_type             object
battery_capacity_kwh    float64
battery_health_pct      float64
range_km                float64
km_driven               float64
charging_time_hr        float64
fast_charging            object
owner_count               int64
city                     object
service_history          object
resale_price              int64
dtype: object

In [19]:
df.isna().sum()

vehicle_id               0
listing_date             0
manufacture_year         0
brand                    0
vehicle_type             0
battery_capacity_kwh    25
battery_health_pct      30
range_km                20
km_driven                0
charging_time_hr        24
fast_charging            0
owner_count              0
city                     0
service_history         30
resale_price             0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df['vehicle_id'].nunique()

994

In [22]:
df["brand"].value_counts()

brand
Nexora        213
Atheron       207
GreenDrive    196
E-Motion      192
Voltix        192
Name: count, dtype: int64

In [23]:
df['listing_date'].dtype

dtype('O')

In [24]:
# 2. Duplicate Vehicle Investigation
# vehicle_id is expected to uniquely identify a vehicle.
# Determine:
# • how many duplicated vehicle_id values exist
# • which vehicle IDs are duplicated
# • how many records are affected

df["vehicle_id"].duplicated().sum()

np.int64(6)

In [25]:
df[df['vehicle_id'].duplicated(keep=False)]['vehicle_id'].value_counts()

vehicle_id
EV-20515    2
EV-20653    2
EV-20011    2
EV-20544    2
EV-20193    2
EV-20279    2
Name: count, dtype: int64

In [26]:
dr = df[df['vehicle_id'].duplicated(keep=False)]
dr

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
72,EV-20515,2025-03-14,2016,GreenDrive,Hatchback,61.6,100.0,210.0,37482.0,7.0,Yes,1,Mumbai,Complete,1492498
81,EV-20653,2025-03-23,2019,Atheron,Crossover,61.4,92.3,398.0,72412.0,10.6,No,4,Chennai,Complete,1267473
119,EV-20011,2025-04-30,2016,Nexora,Sedan,57.9,99.5,NaN,40831.0,8.4,Yes,4,Mumbai,Complete,1591429
133,EV-20544,2025-05-14,2024,E-Motion,Sedan,38.0,93.9,511.0,67782.0,3.1,Yes,2,Chennai,Complete,1604620
280,EV-20544,2025-10-08,2024,E-Motion,Sedan,38.0,93.9,511.0,67782.0,3.1,Yes,2,Chennai,Complete,1604620
621,EV-20515,2026-09-14,2016,GreenDrive,Hatchback,61.6,100.0,210.0,37482.0,7.0,Yes,1,Mumbai,Complete,1492498
655,EV-20193,2026-10-18,2023,Atheron,Crossover,31.3,97.2,285.0,33740.0,8.1,Yes,4,Chennai,Complete,1444991
797,EV-20193,2027-03-09,2023,Atheron,Crossover,31.3,97.2,285.0,33740.0,8.1,Yes,4,Chennai,Complete,1444991
816,EV-20279,2027-03-28,2019,E-Motion,SUV,65.6,87.1,381.0,116102.0,6.8,No,2,Bengaluru,Complete,1395622
852,EV-20011,2027-05-03,2016,Nexora,Sedan,57.9,99.5,NaN,40831.0,8.4,Yes,4,Mumbai,Complete,1591429
857,EV-20279,2027-05-08,2019,E-Motion,SUV,65.6,87.1,381.0,116102.0,6.8,No,2,Bengaluru,Complete,1395622
989,EV-20653,2027-09-17,2019,Atheron,Crossover,61.4,92.3,398.0,72412.0,10.6,No,4,Chennai,Complete,1267473

In [27]:
# 3. Date Conversion & Validation
# Convert listing_date into a proper datetime column.
# Then investigate:
# • earliest listing date
# • latest listing date
# • invalid/missing dates
# • whether the date column is suitable for feature engineering.

df['listing_date'] = pd.to_datetime(df['listing_date'],errors='coerce')
df['listing_date']

0     2025-01-01
1     2025-01-02
2     2025-01-03
3     2025-01-04
4     2025-01-05
         ...
995   2027-09-23
996   2027-09-24
997   2027-09-25
998   2027-09-26
999   2027-09-27
Name: listing_date, Length: 1000, dtype: datetime64[ns]

In [28]:
df['listing_date'].min()

Timestamp('2025-01-01 00:00:00')

In [29]:
df['listing_date'].max()

Timestamp('2027-09-27 00:00:00')

In [30]:
df['listing_date'].isna().sum()

np.int64(0)

In [31]:
df['listing_year'] = df['listing_date'].dt.year
df['listing_month'] = df['listing_date'].dt.month
df['listing_day'] = df['listing_date'].dt.day
df

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price,listing_year,listing_month,listing_day
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836,2025,1,1
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760,2025,1,2
2,EV-20654,2025-01-03,2019,Nexora,Crossover,53.9,91.2,NaN,12003.0000,3.6,Yes,1,Chennai,Complete,1830249,2025,1,3
3,EV-20935,2025-01-04,2022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.0000,7.8,Yes,2,Delhi,Complete,1726422,2025,1,4
4,EV-20827,2025-01-05,2024,GreenDrive,Sedan,53.0,92.0,264.0,28548.0000,6.1,No,1,Pune,Complete,1642232,2025,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,EV-20357,2027-09-23,2017,E-Motion,Sedan,37.9,89.9,333.0,61861.0000,3.0,No,1,Bengaluru,Complete,1338124,2027,9,23
996,EV-20756,2027-09-24,2020,Atheron,Hatchback,67.5,99.9,290.0,55605.0000,9.2,Yes,1,Bengaluru,Complete,1624596,2027,9,24
997,EV-20984,2027-09-25,2025,Atheron,Crossover,91.1,81.8,434.0,23708.0000,2.0,No,1,Delhi,Partial,1958519,2027,9,25
998,EV-20410,2027-09-26,2019,GreenDrive,Sedan,76.8,98.6,264.0,39435.0000,2.8,Yes,1,Chennai,Complete,1724555,2027,9,26
999,EV-20168,2027-09-27,2019,Voltix,Crossover,63.6,88.2,150.0,103173.0000,NaN,No,3,Pune,Complete,1232571,2027,9,27

In [32]:
# 4. Vehicle Age Feature
# Create vehicle_age using:
# listing year − manufacture year
# Then identify whether any vehicle has:
# • age < 0
# • age = 0
# • unusually high age

df['vehicle_age'] = (df['listing_date'].dt.year - df['manufacture_year'])
df[['listing_date', 'manufacture_year', 'vehicle_age']]

    listing_date  manufacture_year  vehicle_age
0     2025-01-01              2021            4
1     2025-01-02              2025            0
2     2025-01-03              2019            6
3     2025-01-04              2022            3
4     2025-01-05              2024            1
..           ...               ...          ...
995   2027-09-23              2017           10
996   2027-09-24              2020            7
997   2027-09-25              2025            2
998   2027-09-26              2019            8
999   2027-09-27              2019            8

[1000 rows x 3 columns]

In [33]:
df[df['vehicle_age'] < 0]

Empty DataFrame
Columns: [vehicle_id, listing_date, manufacture_year, brand, vehicle_type, battery_capacity_kwh, battery_health_pct, range_km, km_driven, charging_time_hr, fast_charging, owner_count, city, service_history, resale_price, listing_year, listing_month, listing_day, vehicle_age]
Index: []

In [34]:
df[df['vehicle_age'] == 0].head()

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price,listing_year,listing_month,listing_day,vehicle_age
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760,2025,1,2,0
8,EV-20708,2025-01-09,2025,Nexora,Sedan,51.9,92.6,522.0,128031.0000,9.2,Yes,2,Pune,Complete,1608566,2025,1,9,0
9,EV-20059,2025-01-10,2025,Atheron,Sedan,65.2,95.1,378.0,55670.0000,5.7,Yes,1,Pune,Complete,1729157,2025,1,10,0
12,EV-20381,2025-01-13,2025,Nexora,Sedan,60.9,89.4,553.0,46088.0000,7.3,Yes,2,Pune,Missing,1821084,2025,1,13,0
19,EV-20301,2025-01-20,2025,E-Motion,Sedan,53.1,95.4,460.0,54736.0000,5.4,Yes,3,Bengaluru,Complete,1820168,2025,1,20,0

In [35]:
(df['vehicle_age'] > 10).sum()

np.int64(27)

In [36]:
# 5. Battery Data Imputation
# The following columns contain missing values:
# battery_capacity_kwh, battery_health_pct, range_km, charging_time_hr
# Develop an appropriate missing-value strategy for each column.
# Do not automatically use the same statistic for every column.
# Explain why you selected mean, median, or another strategy.

cols = [
    'battery_capacity_kwh',
    'battery_health_pct',
    'range_km',
    'charging_time_hr']

df[cols].describe()

       battery_capacity_kwh  battery_health_pct    range_km  charging_time_hr
count            975.000000          970.000000  980.000000        976.000000
mean              58.288755           91.221546  370.018367          6.125000
std               14.199822            4.835603   84.986135          1.755376
min               25.000000           75.800000  150.000000          2.000000
25%               48.700000           87.900000  310.750000          4.900000
50%               58.200000           91.200000  371.000000          6.250000
75%               67.700000           94.600000  427.250000          7.300000
max              110.405980          100.000000  630.000000         12.000000

In [37]:
df['battery_capacity_kwh'] = df['battery_capacity_kwh'].fillna(df['battery_capacity_kwh'].median())
df['battery_health_pct'] = df['battery_health_pct'].fillna(df['battery_health_pct'].median())
df['range_km'] = df['range_km'].fillna(df['range_km'].median())
df['charging_time_hr'] = df['charging_time_hr'].fillna(df['charging_time_hr'].median())
df[['battery_capacity_kwh', 'battery_health_pct', 'charging_time_hr','range_km']]

     battery_capacity_kwh  battery_health_pct  charging_time_hr  range_km
0                    46.9                89.6             10.00     313.0
1                    80.6                99.5              7.10     543.0
2                    53.9                91.2              3.60     371.0
3                    60.1                89.3              7.80     528.0
4                    53.0                92.0              6.10     264.0
..                    ...                 ...               ...       ...
995                  37.9                89.9              3.00     333.0
996                  67.5                99.9              9.20     290.0
997                  91.1                81.8              2.00     434.0
998                  76.8                98.6              2.80     264.0
999                  63.6                88.2              6.25     150.0

[1000 rows x 4 columns]

In [38]:
df[cols].isnull().sum()

battery_capacity_kwh    0
battery_health_pct      0
range_km                0
charging_time_hr        0
dtype: int64

In [39]:
df['range_km'] = df['range_km'].fillna(df.groupby('vehicle_type')['range_km'].transform('median'))
df['range_km']

0      313.0
1      543.0
2      371.0
3      528.0
4      264.0
       ...
995    333.0
996    290.0
997    434.0
998    264.0
999    150.0
Name: range_km, Length: 1000, dtype: float64

In [40]:
# 6. Battery Health Outlier Investigation
# Analyze battery_health_pct.
# Identify:
# • values below a reasonable minimum
# • values above 100
# • extreme observations
# Then decide whether to remove, cap, or retain suspicious values.

df['battery_health_pct'].describe()

count    1000.000000
mean       91.220900
std         4.762444
min        75.800000
25%        88.000000
50%        91.200000
75%        94.500000
max       100.000000
Name: battery_health_pct, dtype: float64

In [41]:
df[df['battery_health_pct'] < 50]
(df['battery_health_pct'] < 50).sum()

np.int64(0)

In [42]:
df[df['battery_health_pct'] > 100]
(df['battery_health_pct'] > 100).sum()

np.int64(0)

In [43]:
# 7. Range vs Battery Capacity
# Create range_per_kwh using:
# range_km / battery_capacity_kwh
# Identify vehicles with unusually low or high efficiency.

df['range_per_kwh'] = (df['range_km'] / df['battery_capacity_kwh'])
df['range_per_kwh']

0      6.673774
1      6.736973
2      6.883117
3      8.785358
4      4.981132
         ...
995    8.786280
996    4.296296
997    4.763996
998    3.437500
999    2.358491
Name: range_per_kwh, Length: 1000, dtype: float64

In [44]:
# 8. Driving Intensity Feature
# Create km_per_year using:
# km_driven / vehicle_age
# Handle the special case where vehicle_age = 0.
# Identify unusually high annual driving.

import numpy as np

df['km_per_year'] = np.where(df['vehicle_age'] == 0,np.nan,df['km_driven'] / df['vehicle_age'])

In [45]:
df[['vehicle_id', 'km_driven', 'vehicle_age', 'km_per_year']].head(10)

  vehicle_id    km_driven  vehicle_age  km_per_year
0   EV-20170   28454.0000            4     7113.500
1   EV-20530  183935.8448            0          NaN
2   EV-20654   12003.0000            6     2000.500
3   EV-20935   13623.0000            3     4541.000
4   EV-20827   28548.0000            1    28548.000
5   EV-20547   37590.0000            3    12530.000
6   EV-20961   11615.0000            8     1451.875
7   EV-20584    6999.0000            8      874.875
8   EV-20708  128031.0000            0          NaN
9   EV-20059   55670.0000            0          NaN

In [46]:
df[df['vehicle_age'] == 0][['vehicle_id', 'km_driven', 'vehicle_age', 'km_per_year']]
df['km_per_year'].describe()

count       960.000000
mean      14093.312781
std       16705.745134
min         676.222222
25%        4692.193750
50%        8194.476190
75%       16774.067092
max      180000.000000
Name: km_per_year, dtype: float64

In [47]:
# 9. Charging Efficiency
# Create charging_efficiency using:
# range_km / charging_time_hr
# Investigate missing values and extreme values before using this feature in a regression model.

df['charging_efficiency'] = (df['range_km'] / df['charging_time_hr'])
df[['range_km', 'charging_time_hr', 'charging_efficiency']].isnull().sum()

range_km               0
charging_time_hr       0
charging_efficiency    0
dtype: int64

In [48]:
df['range_km'].isnull().sum()

np.int64(0)

In [49]:
df['charging_time_hr'].isnull().sum()

np.int64(0)

In [50]:
(df['charging_time_hr'] == 0).sum()

np.int64(0)

In [51]:
df['charging_efficiency'].describe()

count    1000.000000
mean       66.688480
std        29.645261
min        20.888889
25%        47.223077
50%        59.920635
75%        77.750258
max       230.000000
Name: charging_efficiency, dtype: float64

In [52]:
# 10. Ownership Analysis
# Analyze owner_count.
# Determine:
# • frequency of each ownership level
# • whether any values are invalid
# • whether owner count should be treated as numerical or categorical for regression.
# Justify your decision.

df['owner_count'].value_counts().sort_index()

owner_count
1    532
2    302
3    126
4     40
Name: count, dtype: int64

In [53]:
df['owner_count'].value_counts().sort_index().to_frame('frequency')

             frequency
owner_count
1                  532
2                  302
3                  126
4                   40

In [54]:
df['owner_count'].unique()

array([1, 2, 4, 3])

In [55]:
df['owner_count'].min()

1

In [56]:
df['owner_count'].max()

4

In [57]:
df[df['owner_count'] <= 0]

Empty DataFrame
Columns: [vehicle_id, listing_date, manufacture_year, brand, vehicle_type, battery_capacity_kwh, battery_health_pct, range_km, km_driven, charging_time_hr, fast_charging, owner_count, city, service_history, resale_price, listing_year, listing_month, listing_day, vehicle_age, range_per_kwh, km_per_year, charging_efficiency]
Index: []

[0 rows x 22 columns]

In [58]:
(df['owner_count'] <= 0).sum()

np.int64(0)

In [59]:
df['owner_count'].isnull().sum()

np.int64(0)

In [60]:
# 11. Categorical Data Audit
# Analyze: brand, vehicle_type, fast_charging, city, service_history.
# For each column:
# • count unique categories
# • inspect frequencies
# • identify missing values
# • identify suspicious/inconsistent categories.

categorical_cols = [
    'brand',
    'vehicle_type',
    'fast_charging',
    'city',
    'service_history']

In [61]:
df[categorical_cols].nunique(dropna=False)

brand              5
vehicle_type       4
fast_charging      2
city               6
service_history    4
dtype: int64

In [62]:
df['brand'].value_counts(dropna=False)

brand
Nexora        213
Atheron       207
GreenDrive    196
E-Motion      192
Voltix        192
Name: count, dtype: int64

In [63]:
df['vehicle_type'].value_counts(dropna=False)

vehicle_type
SUV          265
Hatchback    251
Crossover    244
Sedan        240
Name: count, dtype: int64

In [64]:
df['fast_charging'].value_counts(dropna=False)

fast_charging
Yes    692
No     308
Name: count, dtype: int64

In [65]:
df['city'].value_counts(dropna=False)

city
Pune         193
Delhi        174
Chennai      168
Bengaluru    160
Mumbai       155
Hyderabad    150
Name: count, dtype: int64

In [66]:
df['service_history'].value_counts(dropna=False)

service_history
Complete    590
Partial     297
Missing      83
NaN          30
Name: count, dtype: int64

In [67]:
df[categorical_cols].isnull().sum()

brand               0
vehicle_type        0
fast_charging       0
city                0
service_history    30
dtype: int64

In [68]:
# 12. Service History Cleaning
# service_history contains Complete, Partial, Missing, and NaN.
# Determine whether “Missing” and actual NaN represent the same business meaning.
# Then create a consistent representation suitable for ML.

df['service_history'].value_counts(dropna=False)

service_history
Complete    590
Partial     297
Missing      83
NaN          30
Name: count, dtype: int64

In [69]:
df['service_history'] = df['service_history'].fillna('Unknown')
df['service_history']

0      Complete
1      Complete
2      Complete
3      Complete
4      Complete
         ...
995    Complete
996    Complete
997     Partial
998    Complete
999    Complete
Name: service_history, Length: 1000, dtype: object

In [70]:
df['service_history'].isnull().sum()

np.int64(0)

In [71]:
# 13. Fast Charging Transformation
# Transform fast_charging from Yes / No into a binary numerical representation.
# Verify the transformation using frequency counts before and after.

df['fast_charging'].value_counts()

fast_charging
Yes    692
No     308
Name: count, dtype: int64

In [72]:
df['fast_charging'] = df['fast_charging'].replace({'Yes': 1,'No': 0})
df['fast_charging'].value_counts()

C:\Users\bhoom\AppData\Local\Temp\ipykernel_11484\3027445138.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['fast_charging'] = df['fast_charging'].replace({'Yes': 1,'No': 0})

fast_charging
1    692
0    308
Name: count, dtype: int64

In [73]:
df['fast_charging'].dtype

dtype('int64')

In [74]:
# 14. Target Analysis
# Analyze resale_price.
# Calculate and inspect:
# • mean
# • median
# • minimum
# • maximum
# • standard deviation
# • potential extreme values
# Determine whether the target contains suspicious observations that could strongly influence a regression model.

df['resale_price'].describe()

count    1.000000e+03
mean     1.586535e+06
std      1.662044e+05
min      9.151090e+05
25%      1.484011e+06
50%      1.589594e+06
75%      1.698082e+06
max      2.072547e+06
Name: resale_price, dtype: float64

In [75]:
df['resale_price'].mean()

np.float64(1586535.101)

In [76]:
df['resale_price'].median()

1589594.0

In [77]:
df['resale_price'].min()

915109

In [78]:
df['resale_price'].max()

2072547

In [79]:
df['resale_price'].std()

166204.3759912459

In [80]:
# 15. Price-per-Kilometer Feature
# Create price_per_km using:
# resale_price / km_driven
# Investigate whether extremely low/high values are caused by very low mileage, very high price, or data-quality
# problems.

df['price_per_km'] = df['resale_price'] / df['km_driven']
df[['vehicle_id', 'resale_price', 'km_driven', 'price_per_km']].head(10)

  vehicle_id  resale_price    km_driven  price_per_km
0   EV-20170       1527836   28454.0000     53.694946
1   EV-20530       2040760  183935.8448     11.094955
2   EV-20654       1830249   12003.0000    152.482629
3   EV-20935       1726422   13623.0000    126.728474
4   EV-20827       1642232   28548.0000     57.525291
5   EV-20547       1533320   37590.0000     40.790636
6   EV-20961       1605157   11615.0000    138.196901
7   EV-20584       1589566    6999.0000    227.113302
8   EV-20708       1608566  128031.0000     12.563879
9   EV-20059       1729157   55670.0000     31.060841

In [81]:
df['km_driven'].isnull().sum()

np.int64(0)

In [82]:
(df['km_driven'] == 0).sum()

np.int64(0)

In [83]:
(df['km_driven'] < 0).sum()

np.int64(0)

In [84]:
df['price_per_km'].describe()

count    1000.000000
mean       47.898997
std        38.160068
min         5.618022
25%        22.713155
50%        37.871836
75%        61.903746
max       296.870220
Name: price_per_km, dtype: float64

In [85]:
# 16. Battery Health × Usage Feature
# Create a combined feature called battery_usage_index based on battery_health_pct and km_driven.
# Design a meaningful formula and explain why this feature could help predict resale price.

df['battery_usage_index'] = (df['km_driven'] * (100 - df['battery_health_pct']))
df[['vehicle_id','battery_health_pct','km_driven','battery_usage_index']].head(10)

  vehicle_id  battery_health_pct    km_driven  battery_usage_index
0   EV-20170                89.6   28454.0000          295921.6000
1   EV-20530                99.5  183935.8448           91967.9224
2   EV-20654                91.2   12003.0000          105626.4000
3   EV-20935                89.3   13623.0000          145766.1000
4   EV-20827                92.0   28548.0000          228384.0000
5   EV-20547                89.6   37590.0000          390936.0000
6   EV-20961                89.9   11615.0000          117311.5000
7   EV-20584                95.1    6999.0000           34295.1000
8   EV-20708                92.6  128031.0000          947429.4000
9   EV-20059                95.1   55670.0000          272783.0000

In [86]:
df['battery_usage_index'].describe()

count    1.000000e+03
mean     4.720589e+05
std      4.700250e+05
min      0.000000e+00
25%      1.701174e+05
50%      3.394780e+05
75%      6.140992e+05
max      3.636000e+06
Name: battery_usage_index, dtype: float64

In [87]:
df['battery_usage_index_million'] = (df['battery_usage_index'] / 1_000_000)
df['battery_usage_index'] = (df['km_driven'] * (100 - df['battery_health_pct']))
df['battery_usage_index']

0      2.959216e+05
1      9.196792e+04
2      1.056264e+05
3      1.457661e+05
4      2.283840e+05
           ...
995    6.247961e+05
996    5.560500e+03
997    4.314856e+05
998    5.520900e+04
999    1.217441e+06
Name: battery_usage_index, Length: 1000, dtype: float64

In [19]:
# 17. Complete Missing-Value Pipeline
# Build a cleaning pipeline for all columns containing missing values:
# battery_capacity_kwh, battery_health_pct, range_km, charging_time_hr, service_history
# Requirements:
# • numeric missing values → appropriate statistical treatment
# • categorical missing values → appropriate category treatment
# • verify zero unintended missing values afterward
# • preserve the original dataset in a separate DataFrame.

df_original = df.copy()

In [20]:
numeric_cols = [
    'battery_capacity_kwh',
    'battery_health_pct',
    'range_km',
    'charging_time_hr'
]

In [21]:
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [22]:
df['service_history'] = df['service_history'].fillna(df['service_history'].mode()[0])

In [24]:
df[['battery_capacity_kwh',
    'battery_health_pct',
    'range_km',
    'charging_time_hr',
    'service_history']].isnull().sum()

battery_capacity_kwh    0
battery_health_pct      0
range_km                0
charging_time_hr        0
service_history         0
dtype: int64

In [25]:
df.isnull().sum().sum()

np.int64(0)

In [18]:
df.head()

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760
2,EV-20654,2025-01-03,2019,Nexora,Crossover,53.9,91.2,371.0,12003.0000,3.6,Yes,1,Chennai,Complete,1830249
3,EV-20935,2025-01-04,2022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.0000,7.8,Yes,2,Delhi,Complete,1726422
4,EV-20827,2025-01-05,2024,GreenDrive,Sedan,53.0,92.0,264.0,28548.0000,6.1,No,1,Pune,Complete,1642232

In [26]:
# 18. Regression Feature Preparation
# Prepare the dataset for a regression model.
# Separate:
# X = features
# y = resale_price
# Remove columns that should not directly be used as model features, such as identifiers.
# Classify every remaining feature as numerical, categorical, or date-derived.


y = df['resale_price']

In [27]:
X = df.drop(columns=['resale_price'])

identifier_cols = ['CustomerID', 'vehicle_id']

In [28]:
X = X.drop(columns=[col for col in identifier_cols if col in X.columns])

numeric_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

categorical_features = X.select_dtypes(include=['object', 'category']).columns.tolist()

date_features = [
    col for col in X.columns
    if 'date' in col.lower() or 'year' in col.lower()
]

In [29]:
numeric_features = [col for col in numeric_features if col not in date_features]
categorical_features = [col for col in categorical_features if col not in date_features]

In [35]:
X.shape

(1000, 13)

In [36]:
y.shape

(1000,)

In [39]:
numeric_features

['battery_capacity_kwh',
 'battery_health_pct',
 'range_km',
 'km_driven',
 'charging_time_hr',
 'owner_count']

In [32]:
categorical_features

['brand', 'vehicle_type', 'fast_charging', 'city', 'service_history']

In [33]:
date_features

['listing_date', 'manufacture_year']

In [67]:
# 19. Leakage Investigation
# Before training the regression model, inspect every engineered feature and determine whether it could cause
# target leakage.
# Evaluate whether features derived from resale_price should be allowed inside X.
# Identify all problematic features and remove them.
import numpy as np
df.columns.tolist()

['vehicle_id',
 'listing_date',
 'manufacture_year',
 'brand',
 'vehicle_type',
 'battery_capacity_kwh',
 'battery_health_pct',
 'range_km',
 'km_driven',
 'charging_time_hr',
 'fast_charging',
 'owner_count',
 'city',
 'service_history',
 'resale_price',
 'listing_year',
 'listing_month',
 'listing_quarter']

In [41]:
leakage_features = [col for col in X.columns if 'resale_price' in col.lower()]
leakage_features

[]

In [42]:
X = X.drop(columns=leakage_features, errors='ignore')

In [43]:
X = X.drop(columns=['resale_price'], errors='ignore')

In [44]:
X.columns.tolist()

['listing_date',
 'manufacture_year',
 'brand',
 'vehicle_type',
 'battery_capacity_kwh',
 'battery_health_pct',
 'range_km',
 'km_driven',
 'charging_time_hr',
 'fast_charging',
 'owner_count',
 'city',
 'service_history']

In [45]:
y.name

'resale_price'

'''20. Ultimate Hard Problem — Production-Ready EV Dataset
You are given this raw EV resale dataset by a machine-learning team.
Build a clean modeling dataset following this workflow:
Step 1 — Audit: shape, info, missing values, duplicates, categorical distributions.
Step 2 — Clean identifiers: investigate duplicated vehicle_id values and determine an appropriate treatment.
Step 3 — Clean dates: convert listing_date and derive listing_year, listing_month, listing_quarter.
Step 4 — Clean numerical features: handle missing and suspicious values in battery_capacity_kwh,
battery_health_pct, range_km, km_driven, charging_time_hr, owner_count.
Step 5 — Clean categorical features: clean brand, vehicle_type, fast_charging, city, service_history.
Step 6 — Feature engineering: create vehicle_age, range_per_kwh, km_per_year, charging_efficiency,
battery_usage_index.
Step 7 — Leakage check: make sure no feature contains information derived from resale_price.
Step 8 — Final validation: no unintended duplicate vehicles, no invalid dates, no unexplained missing values,
correct numerical datatypes, consistent categorical values, no impossible vehicle ages, no impossible
battery-health values, and no target leakage.
Step 9 — Final output: produce X (cleaned independent variables) and y (resale_price).'''

In [49]:
df.shape

(1000, 15)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   vehicle_id            1000 non-null   object
 1   listing_date          1000 non-null   object
 2   manufacture_year      1000 non-null   int64
 3   brand                 1000 non-null   object
 4   vehicle_type          1000 non-null   object
 5   battery_capacity_kwh  1000 non-null   float64
 6   battery_health_pct    1000 non-null   float64
 7   range_km              1000 non-null   float64
 8   km_driven             1000 non-null   float64
 9   charging_time_hr      1000 non-null   float64
 10  fast_charging         1000 non-null   object
 11  owner_count           1000 non-null   int64
 12  city                  1000 non-null   object
 13  service_history       1000 non-null   object
 14  resale_price          1000 non-null   int64
dtypes: float64(5), int64(3), object(7)
memory usage: 117.3+ KB

In [50]:
df.isna().sum()

vehicle_id              0
listing_date            0
manufacture_year        0
brand                   0
vehicle_type            0
battery_capacity_kwh    0
battery_health_pct      0
range_km                0
km_driven               0
charging_time_hr        0
fast_charging           0
owner_count             0
city                    0
service_history         0
resale_price            0
dtype: int64

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:
categorical_cols = [
    'brand',
    'vehicle_type',
    'fast_charging',
    'city',
    'service_history']

In [54]:
df[col].value_counts(dropna=False)

charging_time_hr
6.4     32
6.5     31
5.5     30
6.9     27
7.1     26
        ..
10.2     1
9.9      1
2.5      1
11.4     1
12.0     1
Name: count, Length: 88, dtype: int64

In [55]:
df['vehicle_id'].duplicated().sum()

np.int64(6)

In [56]:
df[df['vehicle_id'].duplicated(keep=False)].sort_values('vehicle_id')

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
119,EV-20011,2025-04-30,2016,Nexora,Sedan,57.9,99.5,371.0,40831.0,8.4,Yes,4,Mumbai,Complete,1591429
852,EV-20011,2027-05-03,2016,Nexora,Sedan,57.9,99.5,371.0,40831.0,8.4,Yes,4,Mumbai,Complete,1591429
655,EV-20193,2026-10-18,2023,Atheron,Crossover,31.3,97.2,285.0,33740.0,8.1,Yes,4,Chennai,Complete,1444991
797,EV-20193,2027-03-09,2023,Atheron,Crossover,31.3,97.2,285.0,33740.0,8.1,Yes,4,Chennai,Complete,1444991
816,EV-20279,2027-03-28,2019,E-Motion,SUV,65.6,87.1,381.0,116102.0,6.8,No,2,Bengaluru,Complete,1395622
857,EV-20279,2027-05-08,2019,E-Motion,SUV,65.6,87.1,381.0,116102.0,6.8,No,2,Bengaluru,Complete,1395622
72,EV-20515,2025-03-14,2016,GreenDrive,Hatchback,61.6,100.0,210.0,37482.0,7.0,Yes,1,Mumbai,Complete,1492498
621,EV-20515,2026-09-14,2016,GreenDrive,Hatchback,61.6,100.0,210.0,37482.0,7.0,Yes,1,Mumbai,Complete,1492498
133,EV-20544,2025-05-14,2024,E-Motion,Sedan,38.0,93.9,511.0,67782.0,3.1,Yes,2,Chennai,Complete,1604620
280,EV-20544,2025-10-08,2024,E-Motion,Sedan,38.0,93.9,511.0,67782.0,3.1,Yes,2,Chennai,Complete,1604620
81,EV-20653,2025-03-23,2019,Atheron,Crossover,61.4,92.3,398.0,72412.0,10.6,No,4,Chennai,Complete,1267473
989,EV-20653,2027-09-17,2019,Atheron,Crossover,61.4,92.3,398.0,72412.0,10.6,No,4,Chennai,Complete,1267473

In [58]:
df = df.drop_duplicates(subset='vehicle_id', keep='first')
df['vehicle_id'].duplicated().sum()

np.int64(0)

In [60]:
df['listing_date'].isna().sum()

np.int64(0)

In [63]:
numeric_cols = [
    'battery_capacity_kwh',
    'battery_health_pct',
    'range_km',
    'km_driven',
    'charging_time_hr',
    'owner_count']

In [71]:
df.loc[df['battery_capacity_kwh'] <= 0,
       'battery_capacity_kwh'] = np.nan

df.loc[
    (df['battery_health_pct'] < 0) |
    (df['battery_health_pct'] > 100),
    'battery_health_pct'] = np.nan

df.loc[df['range_km'] <= 0,
       'range_km'] = np.nan

df.loc[df['km_driven'] < 0,
       'km_driven'] = np.nan

df.loc[df['charging_time_hr'] <= 0,
       'charging_time_hr'] = np.nan

df.loc[df['owner_count'] < 0,
       'owner_count'] = np.nan