In [1]:
# Q1 Load the dataset and display the first 10 records.

import pandas as pd

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\dataset.csv")

df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [2]:
# Q2 Display the last 15 customers.
df.tail(15)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
288,57,1,0,110,335,0,1,143,1,3.0,1,1,3,0
289,55,0,0,128,205,0,2,130,1,2.0,1,1,3,0
290,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
# Q3 Show 7 random customer records.

df.sample(7)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
138,57,1,0,110,201,0,1,126,1,1.5,1,0,1,1
251,43,1,0,132,247,1,0,143,1,0.1,1,4,3,0
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0
38,65,0,2,155,269,0,1,148,0,0.8,2,0,2,1
173,58,1,2,132,224,0,0,173,0,3.2,2,2,3,0
195,59,1,0,170,326,0,0,140,1,3.4,0,0,3,0

In [4]:
# Q4
# Print complete dataset information and identify:
# • Total columns
# • Data type of each column
# • Missing values

df.shape

(303, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [6]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
# Q5 Find missing values in every column.
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
# Q6 Display only numerical columns.

df.select_dtypes(include = ["int","float"]).columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [9]:
# Q7 Generate the statistical summary of numerical columns.

df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [10]:
# Q8 Find duplicate rows and print how many exist.

df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Length: 303, dtype: bool

In [11]:
# Q9 Remove duplicate rows and store the cleaned dataset.
df.drop_duplicates(inplace = True)
df.drop_duplicates().sum()

age         16435.0
sex           206.0
cp            291.0
trestbps    39744.0
chol        74443.0
fbs            45.0
restecg       159.0
thalach     45170.0
exang          99.0
oldpeak       315.0
slope         422.0
ca            217.0
thal          699.0
target        164.0
dtype: float64

In [12]:
# Q10 Count how many customers have exited and how many have not exited.

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Bank_customer_churn.csv")
df.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [13]:
df['Exited'].value_counts(dropna = True)

Exited
0    7963
1    2037
Name: count, dtype: int64

In [14]:
# Q11
# Rename the following columns:
# CustomerId → Customer_ID
# CreditScore → Credit_Score
# EstimatedSalary → Salary
# Exited → Churn

df.rename(columns = {"CustomerId":"Customer_ID",
                     "CreditScore":"Credit_Score",
                     "EstimatedSalary":"Salary",
                     "Exited":"Churn"},inplace=True)

df.head(1)

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.0,1,1,1,101348.88,1

In [15]:
# Q12
# Add the prefix
# Bank_ to every column name.

df=df.add_prefix("Bank_")

In [16]:
# Q13 Convert the Age column into float datatype.

df['Bank_Age']=df['Bank_Age'].astype("float")
df

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [17]:
# Q14 Convert the Exited column into string datatype.

df['Bank_Churn']=df['Bank_Churn'].astype("str")
df

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [18]:
# Q15
# Suppose the Balance column has missing values.
# Replace them using the mean of the Balance column.

balance_mean = int(df['Bank_Balance'].mean())
balance_mean

76485

In [19]:
balance_mean = df['Bank_Balance'].mean()

df['Bank_Balance'] = df['Bank_Balance'].fillna(0)
df['Bank_Balance'] = df['Bank_Balance'].astype(int)

print(df['Bank_Balance'])

0            0
1        83807
2       159660
3            0
4       125510
         ...
9995         0
9996     57369
9997         0
9998     75075
9999    130142
Name: Bank_Balance, Length: 10000, dtype: int64

In [20]:
df['Bank_Balance'] = df['Bank_Balance'].replace(0, balance_mean)

print(df['Bank_Balance'])

0        76485.889288
1        83807.000000
2       159660.000000
3        76485.889288
4       125510.000000
            ...
9995     76485.889288
9996     57369.000000
9997     76485.889288
9998     75075.000000
9999    130142.000000
Name: Bank_Balance, Length: 10000, dtype: float64

In [21]:
# Q16
# Suppose the Age column has missing values.
# Replace them using the median age.

import numpy as np
dicts = {"Age":[12,14,15,15,16,np.nan,56,70,71,np.nan,np.nan]}
df =pd.DataFrame(dicts)
df

     Age
0   12.0
1   14.0
2   15.0
3   15.0
4   16.0
5    NaN
6   56.0
7   70.0
8   71.0
9    NaN
10   NaN

In [22]:
age_median = df['Age'].median()
age_median

15.5

In [23]:
df['Age'] = df['Age'].fillna(age_median)
df['Age'] = df['Age'].astype("int")
df['Age']

0     12
1     14
2     15
3     15
4     16
5     15
6     56
7     70
8     71
9     15
10    15
Name: Age, dtype: int64

In [24]:
# Q17 Display only the first five rows after renaming the columns.

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Bank_customer_churn.csv")
df.rename(columns = {"CustomerId":"Customer_ID",
                     "CreditScore":"Credit_Score",
                     "EstimatedSalary":"Salary",
                     "Exited":"Churn"},inplace=True)
df.head()

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [25]:
# Q18
# Create a new DataFrame by dropping these columns:
# RowNumber
# CustomerId
# Surname
# Display the first 10 rows.

df1=df.drop("RowNumber",axis=1)
df1=df1.drop("Customer_ID",axis=1)
df1=df1.drop("Surname",axis=1)
df1.head(10)

,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [26]:
# Q19 Drop the Geography column and display dataset information again.

df1=df.drop("Geography",axis=1)
df1.head(1)

,RowNumber,Customer_ID,Surname,Credit_Score,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,Female,42,2,0.0,1,1,1,101348.88,1

In [27]:
# Q20 Rename NumOfProducts to Products and HasCrCard to CreditCard.

df.rename(columns={"NumOfProducts":"Products",
                   "HasCrCard":"CreditCard"},inplace=True)
df.head()

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [28]:
# Q21 (Real Company Task)
# Your manager wants cleaner column names.
# Rename every column as follows:
# RowNumber → Row_No
# CustomerId → Customer_ID
# Surname → Last_Name
# CreditScore → Credit_Score
# Geography → Country
# Gender → Sex
# EstimatedSalary → Salary
# Exited → Target
# Display the first five rows.

df.rename(columns={"RowNumber":"Row_No",
                   "CustomerId":"Customer_ID",
                   "Surname":"Last_Name",
                   "Geography":"Country",
                   "Churn":"Target"},inplace=True)
df

,Row_No,Customer_ID,Last_Name,Credit_Score,Country,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [29]:
# Q22 Create a new DataFrame that contains only numeric columns.
# Then generate its statistical summary.

df1=df.select_dtypes(["int","float"])
df1.describe()

,Row_No,Customer_ID,Credit_Score,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [30]:
# Q23
# Your company received duplicate customer records.
# Tasks:
# • Count duplicates.
# • Remove duplicates.
# • Display dataset information after cleaning.

data = {
    "Customer_ID": [101, 102, 103, 102, 104, 105, 103],
    "Name": ["Amit", "Riya", "John", "Riya", "Sara", "Kiran", "John"],
    "City": ["Pune", "Delhi", "Mumbai", "Delhi", "Chennai", "Hyderabad", "Mumbai"]
}

df = pd.DataFrame(data)


duplicates = df.duplicated().sum()
print(duplicates)

df = df.drop_duplicates()

print(df)

print(df.info())

2
   Customer_ID   Name       City
0          101   Amit       Pune
1          102   Riya      Delhi
2          103   John     Mumbai
4          104   Sara    Chennai
5          105  Kiran  Hyderabad
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 5
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   City         5 non-null      object
dtypes: int64(1), object(2)
memory usage: 160.0+ bytes
None

In [34]:
# Q24
# Management wants every column name to begin with
# Customer_
# Apply this transformation using the appropriate method.

df1=df.add_prefix("Customer_")
df1.head()

,Customer_Row_No,Customer_Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Country,Customer_Gender,Customer_Age,Customer_Tenure,Customer_Balance,Customer_Products,Customer_CreditCard,Customer_IsActiveMember,Customer_Salary,Customer_Target
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [38]:
# Q25
# After renaming the columns, convert
# Age
# Balance
# Salary
# to float datatype.
# Print dataset information.

df2=df1['Customer_Age']=df1['Customer_Age'].astype("float")
df2=df1['Customer_Balance']=df1['Customer_Balance'].astype("float")
df2=df1['Customer_Salary']=df1['Customer_Salary'].astype("float")
df2

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: Customer_Salary, Length: 10000, dtype: float64

In [32]:
# Q26
# Assume CreditScore contains missing values.
# Replace them with the median CreditScore.

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Bank_customer_churn.csv")

median_score = df["CreditScore"].median()
df["CreditScore"] = df["CreditScore"].fillna(median_score)

print(df)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]

In [34]:
# Q27
# Assume EstimatedSalary contains missing values.
# Replace them with the mean salary.
# Then print the first eight rows.

data = {
    "Customer_ID": [101, 102, 103, 102, 104, 105, 103, 106],
    "Name": ["Amit", "Riya", "John", "Riya", "Sara", "Kiran", "John", "Neha"],
    "City": ["Pune", "Delhi", "Mumbai", "Delhi", "Chennai", "Hyderabad", "Mumbai", "Bangalore"],
    "EstimatedSalary": [50000, None, 60000, 55000, None, 70000, 60000, 65000]
}


mean_salary = df["EstimatedSalary"].mean()
df["EstimatedSalary"] = df["EstimatedSalary"].fillna(mean_salary)

df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [35]:
# Q28 (Data Cleaning Challenge)
# Perform all the following:
# • Remove duplicate rows.
# • Rename Exited to Target.
# • Convert Target to string.
# • Display dataset information.

data = {
    "Customer_ID": [101, 102, 103, 102, 104, 105, 103],
    "Name": ["Amit", "Riya", "John", "Riya", "Sara", "Kiran", "John"],
    "Exited": [1, 0, 1, 0, 1, 0, 1]
}

df = df.drop_duplicates()

df = df.rename(columns={"Exited": "Target"})

df["Target"] = df["Target"].astype(str)

print(df.info())

print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Target           10000 non-null  object
dtypes: float64(2), int64(8), object(4)
memory usage: 1.1+ MB
None
      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary Target
0           101348.88      1
1           112542.58      0
2           113931.57      1
3            93826.63      0
4            79084.10      0
...               ...    ...
9995         96270.64      0
9996        101699.77      0
9997         42085.58      1
9998         92888.52      1
9999         38190.78      0

[10000 rows x 14 columns]

In [ ]:
# Q29 (Transformation Challenge)
# Create a copy of the dataset.
# Perform these transformations:
# • Rename Gender to CustomerGender
# • Rename Geography to Country
# • Add prefix Bank_
# • Remove RowNumber
# • Display first 10 rows

In [42]:
# Q30 Real Industry Mini Project
# Your manager asks you to prepare a cleaned dataset for the Machine Learning team.
# Perform all of these steps:
# 1. Load the dataset.
# 2. Display dataset information.
# 3. Check missing values.
# 4. Remove duplicate rows.
# 5. Rename the following columns:
# o CustomerId → Customer_ID
# o CreditScore → Credit_Score
# o EstimatedSalary → Salary
# o Exited → Target
# 6. Convert:
# o Age → float
# o Balance → float
# o Target → string
# 7. Replace missing values:
# o Age → median
# o Balance → mean
# 8. Remove:
# o RowNumber
# o Surname
# 9. Display:
# o First 10 rows
# o Statistical summary
# o Value counts of Target
# o Final dataset information


df.head(1)

,Row_No,Customer_ID,Last_Name,Credit_Score,Country,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42,2,0.0,1,1,1,101348.88,1

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_No          10000 non-null  int64
 1   Customer_ID     10000 non-null  int64
 2   Last_Name       10000 non-null  object
 3   Credit_Score    10000 non-null  int64
 4   Country         10000 non-null  object
 5   Gender          10000 non-null  object
 6   Age             10000 non-null  int64
 7   Tenure          10000 non-null  int64
 8   Balance         10000 non-null  float64
 9   Products        10000 non-null  int64
 10  CreditCard      10000 non-null  int64
 11  IsActiveMember  10000 non-null  int64
 12  Salary          10000 non-null  float64
 13  Target          10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [44]:
df.rename(columns ={"CustomerId":"Customer_ID",
                    "CreditScore":"Credit_Score"},inplace=True)
df

,Row_No,Customer_ID,Last_Name,Credit_Score,Country,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [48]:
# Age → float
# o Balance → float
# o Target → string
df['Age']=df['Age'].astype("float")
df['Balance']=df['Balance'].astype("float")
df['Target']=df['Target'].astype("float")
df.head()

,Row_No,Customer_ID,Last_Name,Credit_Score,Country,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1.0
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0.0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1.0
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0.0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0.0

In [54]:
#  Remove:
# o RowNumber
# o Surname

df=df.drop("Row_No",axis=1)
df=df.drop("Last_Name",axis=1)
df

,Customer_ID,Credit_Score,Country,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
0,15634602,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1.0
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0.0
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1.0
3,15701354,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0.0
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0.0
9996,15569892,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0.0
9997,15584532,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1.0
9998,15682355,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1.0
9999,15628319,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0.0

In [55]:
df.head(10)

,Customer_ID,Credit_Score,Country,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
0,15634602,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1.0
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0.0
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1.0
3,15701354,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0.0
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0.0
5,15574012,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1.0
6,15592531,822,France,Male,50.0,7,0.00,2,1,1,10062.80,0.0
7,15656148,376,Germany,Female,29.0,4,115046.74,4,1,0,119346.88,1.0
8,15792365,501,France,Male,44.0,4,142051.07,2,0,1,74940.50,0.0
9,15592389,684,France,Male,27.0,2,134603.88,1,1,1,71725.73,0.0