In [25]:
# 1. Load the dataset using the appropriate Pandas method and store it in a
# variable named df.

import pandas as pd

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\dataset.csv")

df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [26]:
# 2. Display the first 8 rows of the dataset.

df.head(8)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1

In [27]:
# 3. Display the last 12 rows of the dataset.

df.tail(12)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [28]:
# 4. Show 10 random rows from the dataset.
df.sample(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
90,48,1,2,124,255,1,1,175,0,0.0,2,2,2,1
229,64,1,2,125,309,0,1,131,1,1.8,1,0,3,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2,1
39,65,0,2,160,360,0,0,151,0,0.8,2,0,2,1
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
69,62,0,0,124,209,0,1,163,0,0.0,2,0,2,1
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3,1
161,55,0,1,132,342,0,1,166,0,1.2,2,0,2,1
59,57,0,0,128,303,0,0,159,0,0.0,2,1,2,1

In [29]:
# 5. Find the shape of the dataset.
# o How many rows are there?
# o How many columns are there?

df.shape

(303, 14)

In [30]:
# 6. Display complete information about the dataset using one method.
# o Number of non-null values
# o Data types
# o Memory usage

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [31]:
# 7. Print the names of all columns in the dataset.
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [32]:
# 8. Find the data type of every column.
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [33]:
# 9. Check for missing values in every column using:
# o isnull().sum()
# o isna().sum()

df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [34]:
df.isna().sum

<bound method DataFrame.sum of        age    sex     cp  trestbps   chol    fbs  restecg  thalach  exang  \
0    False  False  False     False  False  False    False    False  False
1    False  False  False     False  False  False    False    False  False
2    False  False  False     False  False  False    False    False  False
3    False  False  False     False  False  False    False    False  False
4    False  False  False     False  False  False    False    False  False
..     ...    ...    ...       ...    ...    ...      ...      ...    ...
298  False  False  False     False  False  False    False    False  False
299  False  False  False     False  False  False    False    False  False
300  False  False  False     False  False  False    False    False  False
301  False  False  False     False  False  False    False    False  False
302  False  False  False     False  False  False    False    False  False

     oldpeak  slope     ca   thal  target
0      False  False  False  False   False
1      False  False  False  False   False
2      False  False  False  False   False
3      False  False  False  False   False
4      False  False  False  False   False
..       ...    ...    ...    ...     ...
298    False  False  False  False   False
299    False  False  False  False   False
300    False  False  False  False   False
301    False  False  False  False   False
302    False  False  False  False   False

[303 rows x 14 columns]>

In [35]:
# 10.Select only one column:
# o CreditScore

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Bank_customer_churn.csv")

df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [36]:
CreditScore = df['CreditScore']
CreditScore

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [37]:
# 11.Select the following multiple columns:
# o CustomerId
# o Surname
# o Balance
# o Exited

multi = df[['CustomerId','Surname','Balance','Exited']]

multi

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

In [38]:
# 12.Display only numeric columns using select_dtypes().

df.select_dtypes(include = ["int","float"]).columns

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [39]:
# 13.Generate the statistical summary of all numeric columns using describe().
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [40]:
# 14.Check for duplicate rows in the dataset.
# o How many duplicate rows exist?
# o Remove all duplicate rows.

df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [42]:
df.drop_duplicates(inplace = True)
df1 = df.drop_duplicates().sum()

In [43]:
df1

RowNumber                                                   50005000
CustomerId                                              156909405694
Surname            HargraveHillOnioBoniMitchellChuBartlettObinnaH...
CreditScore                                                  6505288
Geography          FranceSpainFranceFranceSpainSpainFranceGermany...
Gender             FemaleFemaleFemaleFemaleFemaleMaleMaleFemaleMa...
Age                                                           389218
Tenure                                                         50128
Balance                                                 764858892.88
NumOfProducts                                                  15302
HasCrCard                                                       7055
IsActiveMember                                                  5151
EstimatedSalary                                        1000902398.81
Exited                                                          2037
dtype: object

In [45]:
# 15.Count the number of customers in each class of the Exited column using
# value_counts().

df["Exited"].value_counts(dropna = True)

Exited
0    7963
1    2037
Name: count, dtype: int64

In [47]:
# 1. Take two numbers from user. Perform all arithmetic operations and also check
# which number is greater using comparison operators.

a = int(input("Enter 1st number :"))
b = int(input("Enter 2nd number :"))

print("add :",a+b)
print("sub :",a-b)
print("mult :",a*b)
print("div :",a/b)

print("Greater number")
if a > b:
    print(f"{a} is greater then {b}")
elif b > a:
    print(f"{b} is greater then {a}")
else:
    print("both are equal")

Enter 1st number : 10
Enter 2nd number : 5

add : 15
sub : 5
mult : 50
div : 2.0
Greater number
10 is greater then 5

In [51]:
# 2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop
# completely when number 40 is reached using break.

for i in range(1, 51):

    if i == 40:
        print("Loop stopped at", i)
        break
        
    if i % 5 == 0:
        continue

    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39
Loop stopped at 40

In [55]:
# 3. Take numbers from user until they enter negative number. Calculate sum and
# average using while loop.

total = 0
count = 0

while True:
    num = float(input("Enter a number (negative to stop): "))

    if num < 0:
        break

    total += num
    count += 1

if count > 0:
    average = total / count
    print("\nSum =", total)
    print("Average =", average)
else:
    print("\nNo positive numbers were entered.")

Enter a number (negative to stop):  20
Enter a number (negative to stop):  30
Enter a number (negative to stop):  40
Enter a number (negative to stop):  50
Enter a number (negative to stop):  0
Enter a number (negative to stop):  -1

Sum = 140.0
Average = 28.0

In [63]:
# 4. Print the following pattern using nested loops:
# *****
# ****
# ***
# **
# *

for i in range(5,0,-1):
    for j in range(i):
        print("*", end="")
    print()

*****
****
***
**
*

In [64]:
# 5. Find the factorial of a number using for loop and also using while loop.

num = int(input("Enter a number: "))
factorial = 1

if num < 0:
    print("Factorial does not exist for negative numbers.")
else:
    for i in range(1, num + 1):
        factorial *= i

    print("Factorial =", factorial)

Enter a number:  30

Factorial = 265252859812191058636308480000000

In [65]:
# 6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace
# spaces with -, and check if it starts with “Hello”.

text = input("Enter a string: ")

print(text.upper())

print(text.lower().count('a'))

print(text.replace(" ", "-"))

if text.startswith("Hello"):
    print("The string starts with 'Hello'.")
else:
    print("The string does not start with 'Hello'.")

Enter a string:  hello this is paritosh

HELLO THIS IS PARITOSH
1
hello-this-is-paritosh
The string does not start with 'Hello'.

In [74]:
# 7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending)
# and reverse.

lst=[1,2,3,4,5,6]

lst.append(7)
lst

[1, 2, 3, 4, 5, 6, 7]

In [75]:
lst.insert(1,7)
lst

[1, 7, 2, 3, 4, 5, 6, 7]

In [80]:
lst.remove(7)
lst

[2, 3, 4, 5, 6, 7]

In [81]:
lst.pop()

7

In [87]:
lst.sort(reverse=True)
lst

[6, 5, 4, 3, 2]

In [92]:
# 8. Create a dictionary of 4 students (name:marks). Print only those students who
# scored more than 80 using items().

dct = {"paritosh":80,"sumit":60,"santosh":100}

for key,val in dct.items():
    if val > 80:
        print(key,":",val)

santosh : 100

In [94]:
# 9. Create two sets and perform union, intersection, difference. Also add and discard elements.

set1 = {1,2,3,4,5}
set2 = {3,4,5,6}

set1.union(set2)

{1, 2, 3, 4, 5, 6}

In [95]:
set1.intersection(set2)

{3, 4, 5}

In [96]:
set1.difference(set2)

{1, 2}

In [107]:
# 10. Create a class Student with private attribute __marks. Add getter and setter with
# validation (0–100).

class Student:
    def __init__(self, marks):
        self.__marks = marks

    def get_marks(self):
        print("Marks:", self.__marks)

    def set_marks(self, new):
        if 0 < new < 100:
            self.__marks = new
            print("Marks have been updated successfully.")

c=Student(15)
c.get_marks
c.set_marks(99)
c.get_marks()

Marks have been updated successfully.
Marks: 99

In [109]:
# 11. Create class BankAccount with private __balance. Add deposit and withdraw
# methods. Raise custom exception if balance becomes negative.

class BankAccount:
    def __init__(self,balance):
        self.__balance = balance

    def deposit(self,amount):
        if amount > 0:
            self.__balance += amount
            print("Amount has been deposit")
        else:
            print("please enter valid amount")

    def withdraw(self,amount):
        if amount > self.__balance:
            print("insuffient balance")
        elif amount < 0:
            print("withdraw amount should be in positive")
        else:
            self.__balance -= amount
            print(f"{amount} has been withdrawn successfully")

c= BankAccount(4000)
c.deposit(1000)
c.withdraw(4000)

Amount has been deposit
4000 has been withdrawn successfully

In [111]:
# 12. Create class Employee with class attribute company_name. Show that it is
# shared by all objects. Also update the class attribute.

class Employee:
    def __init__(self,company_name):
        self.company_name = company_name

    def set_company_name(self,new):
        self.company_name = new
        print(self.company_name)

    def display_info(self):
        emp = "paritosh"
        print(f"name : {emp}")
        print(f"company name : {self.company_name}")

c = Employee("IBM")
c.set_company_name("Avengers")
c.display_info()

Avengers
name : paritosh
company name : Avengers

In [112]:
# 13. Create class Product with private __price. Add getter and setter. Setter should
# not allow price less than 100.

class Product:
    def __init__(self,price):
        self.__price = price

    def get_price(self):
        print(self.__price)

    def set_price(self,new):
        if new > 100:
            self.__price = new
            print("price has been updated successfully")
        else:
            print("price should be more then 100")
            
d= Product(400)
d.get_price()

400

In [116]:
d.set_price(199)
d.get_price()

price has been updated successfully
199

In [120]:
# 14. Create class Rectangle with private length and width. Add method to calculate
# area and perimeter.

class Rectangle:
    def __init__(self,length,width):
        self.__length = length
        self.__width = width

    def area(self):
        area = self.__length * self.__width
        print(f"Area of Rectangle: {area}")

    def perimeter(self):
        per = 2 * (self.__length * self.__width)
        print(f"perimeter of Rectangle: {per}")

r = Rectangle(9,8)
r.area()
r.perimeter()

Area of Rectangle: 72
perimeter of Rectangle: 144

In [121]:
# 15. Create single level inheritance: Person → Student. Use super() in constructor.

class Person:
    def __init__(self,name):
        self.name = name

class Student(Person):
    def info(self):
        print("Student info")
        print(self.name)

c = Student("Paritosh")
c.info()

Student info
Paritosh

In [ ]:
# 16. Create multi-level inheritance: Person → Employee → Manager. Override a
# method at each level.

class Person:
    def display(self):
        print("I am a Person.")


class Employee(Person):
    def display(self):
        print("I am an Employee.")


class Manager(Employee):
    def display(self):
        print("I am a Manager.")

p = Person()
e = Employee()
m = Manager()

p.display()
e.display()
m.display()

In [123]:
# 17. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound() method.

class Animal:
    def sound(self):
        pass

class Dog(Animal):
    def sound(self):
        print("Dog barks")

class Cat(Animal):
    def sound(self):
        print("meow")

c = Dog()
c.sound()

d = Cat()
d.sound()

Dog barks
meow

In [125]:
# 18. Create abstract class Shape with abstract method area(). Implement it in Circle
# and Square using super().

from abc import ABC, abstractmethod

class Shape(ABC):
    def __init__(self, value):
        self.value = value

    @abstractmethod
    def area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        super().__init__(radius)

    def area(self):
        return 3.14 * self.value ** 2

class Square(Shape):
    def __init__(self, side):
        super().__init__(side)

    def area(self):
        return self.value ** 2

c = Circle(7)
s = Square(5)

print("Area of Circle =", c.area())
print("Area of Square =", s.area())

Area of Circle = 153.86
Area of Square = 25

In [128]:
# 19. Create multiple inheritance with two classes Father and Mother. Create child
# class and resolve method conflict.

class Father:
    def __init__(self, father_name):
        self.father_name = father_name

    def introduce(self):
        print("I am Father")


class Mother:
    def __init__(self, mother_name):
        self.mother_name = mother_name

    def introduce(self):
        print("I am Mother")


class Child(Father, Mother):
    def __init__(self, father_name, mother_name, child_name):
        Father.__init__(self, father_name)
        Mother.__init__(self, mother_name)
        self.child_name = child_name

    def introduce(self):
        Father.introduce(self)

    def info(self):
        print("Father Name :", self.father_name)
        print("Mother Name :", self.mother_name)
        print("Child Name  :", self.child_name)


c = Child("Jack", "Akane", "Kai")
c.introduce()
c.info()

I am Father
Father Name : Jack
Mother Name : Akane
Child Name  : Kai

In [129]:
# 20. Create a class Calculator that can add 2 or 3 numbers (method overloading using *args).

class Calculator:
    def add(self, *args):
        if len(args) == 2:
            print("Sum of 2 numbers =", args[0] + args[1])
        elif len(args) == 3:
            print("Sum of 3 numbers =", args[0] + args[1] + args[2])
        else:
            print("Please enter only 2 or 3 numbers.")


c = Calculator()
c.add(10, 20)
c.add(10, 20, 30)
c.add(10)

Sum of 2 numbers = 30
Sum of 3 numbers = 60
Please enter only 2 or 3 numbers.

In [140]:
# 21. Create class Point and overload + and > operators.

class Point:
    def __init__(self,val):
        self.val  = val
        
    def __add__(self,other):
        return self.val + other.val

    def __gt__(self,other):
        return self.val > other.val

c = Point(6)
p= Point(7)

print(c+p)
print(c>p)

13
False

In [132]:
# 22. Write a program that handles ZeroDivisionError, ValueError and IndexError using
# multiple except blocks.

try:
    numbers = [10, 20, 30]

    num = int(input("Enter a number: "))
    index = int(input("Enter list index: "))

    print("Division =", 100 / num)
    print("Element =", numbers[index])

except ZeroDivisionError:
    print("Error: Cannot divide by zero.")

except ValueError:
    print("Error: Please enter valid integer values.")

except IndexError:
    print("Error: List index is out of range.")

finally:
    print("Program Ended.")

Enter a number:  0
Enter list index:  1

Error: Cannot divide by zero.
Program Ended.

In [134]:
# 23. Create a custom exception InvalidAgeError. Raise it if age is less than 18.

class InvalidAgeError(Exception):
    pass

try:
    age = int(input("enter ur age"))
    if age > 18:
        print(age)
    else:
        raise InvalidAgeError("Invalid Age Error : age should  be 18+")

except InvalidAgeError as e:
    print(e)

enter ur age 18

Invalid Age Error : age should  be 18+

In [135]:
# 24. Write a program to read a file, count number of words, and write the count into
# another file.

try:
    with open("input.txt", "r") as file:
        content = file.read()

    word_count = len(content.split())

    with open("output.txt", "w") as file:
        file.write(f"Total number of words: {word_count}")

    print("Word count written to output.txt successfully.")

except FileNotFoundError:
    print("Error: input.txt file not found.")

except Exception as e:
    print("Error:", e)

Error: input.txt file not found.

In [136]:
# 25. Create a menu-driven program for file operations: Write, Read, Append, and Exit.
# Handle FileNotFoundError.

while True:
    print("1. Write to File")
    print("2. Read File")
    print("3. Append to File")
    print("4. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        data = input("Enter text :")
        with open("data.txt", "w") as file:
            file.write(data)
        print("Data written successfully.")

    elif choice == "2":
        try:
            with open("data.txt", "r") as file:
                print("\nFile Content:")
                print(file.read())
        except FileNotFoundError:
            print("Error: data.txt file not found.")

    elif choice == "3":
        data = input("Enter text to append: ")
        with open("data.txt", "a") as file:
            file.write("\n" + data)
        print("Data appended successfully.")

    elif choice == "4":
        print("Program Exited.")
        break

    else:
        print("Invalid choice. Please try again.")

1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  1
Enter text : hey this is paritosh

Data written successfully.
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  2

File Content:
hey this is paritosh
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  3
Enter text to append:  in lab

Data appended successfully.
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  2

File Content:
hey this is paritosh
in lab
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice:  4

Program Exited.

In [137]:
# 26. Create a class Student with private marks list.
# • Setter should validate each mark (0-100)
# • Overload > operator to compare two students based on average
# • Raise custom exception if marks list is empty

class EmptyMarksError(Exception):
    pass


class Student:
    def __init__(self, name):
        self.name = name
        self.__marks = []

    def set_marks(self, marks):
        if len(marks) == 0:
            raise EmptyMarksError("Marks list cannot be empty.")

        for mark in marks:
            if mark < 0 or mark > 100:
                raise ValueError("Marks must be between 0 and 100.")

        self.__marks = marks

    def get_marks(self):
        return self.__marks

    def average(self):
        return sum(self.__marks) / len(self.__marks)

    def __gt__(self, other):
        return self.average() > other.average()

try:
    s1 = Student("paritosh")
    s2 = Student("santosh")

    s1.set_marks([80, 90, 85])
    s2.set_marks([75, 88, 82])

    print("paritosh Average:", s1.average())
    print("santosh Average:", s2.average())

    if s1 > s2:
        print("paritosh has a higher average.")
    else:
        print("santosh has a higher average.")

except EmptyMarksError as e:
    print("Custom Exception:", e)

except ValueError as e:
    print("ValueError:", e)

paritosh Average: 85.0
santosh Average: 81.66666666666667
paritosh has a higher average.

In [ ]:
# 27. Write a menu-driven banking system using OOP + File Handling. Store account
# details in a file. Handle FileNotFoundError, ValueError, and custom exceptions.

In [141]:
# 28. Using dictionary + exception handling, create a student management system that can:
# • Add student
# • Update marks
# • Delete student
# • Display all Raise custom exception if student not found.

class StudentNotFoundError(Exception):
    pass

students = {}

while True:
    print("1. Add Student")
    print("2. Update Marks")
    print("3. Delete Student")
    print("4. Display All Students")
    print("5. Exit")

    try:
        choice = int(input("Enter your choice: "))

        if choice == 1:
            name = input("Enter student name: ")
            marks = int(input("Enter marks: "))
            students[name] = marks

        elif choice == 2:
            name = input("Enter student name to update: ")

            if name not in students:
                raise StudentNotFoundError("Student not found!")

            marks = int(input("Enter new marks: "))
            students[name] = marks

        elif choice == 3:
            name = input("Enter student name to delete: ")

            if name not in students:
                raise StudentNotFoundError("Student not found!")

            del students[name]

        elif choice == 4:
            if not students:
                print("No student records available.")
            else:
                print("Student Records")
                print("-"*30)
                for name, marks in students.items():
                    print(f"{name} : {marks}")

        elif choice == 5:
            print("Exiting program...")
            break
        else:
            print("Invalid choice!")

    except ValueError:
        print("Please enter a valid number.")

    except StudentNotFoundError as e:
        print(e)

    except Exception as e:
        print("Error:", e)

1. Add Student
2. Update Marks
3. Delete Student
4. Display All Students
5. Exit

Enter your choice:  1
Enter student name:  paritosh
Enter marks:  90

1. Add Student
2. Update Marks
3. Delete Student
4. Display All Students
5. Exit

Enter your choice:  2
Enter student name to update:  paritosh
Enter new marks:  99

1. Add Student
2. Update Marks
3. Delete Student
4. Display All Students
5. Exit

Enter your choice:  4

Student Records
------------------------------
paritosh : 99
1. Add Student
2. Update Marks
3. Delete Student
4. Display All Students
5. Exit

Enter your choice:  5

Exiting program...

In [155]:
# 29. Create a class Employee with private salary.
# • Setter should not allow more than 15% increase at once
# • Keep history of all salary changes
# • Add static method to calculate tax
# • Overload > operator to compare employees by salary


class Employee:
    count = []
    def __init__(self,salary):
        self.__salary = salary

    def set_salary(self,new):
        if new > self.__salary+(self.__salary*0.15):
            Employee.count.append(new)
            self.__salary = new
            print("sal has been updated")
        else:
            print("sal should be more thn 15% of the old sal")
            
    @staticmethod
    def tax(self):
        tax = self.__salary+(self.__salary*0.15)
        print(f"salary after tax : {tax}")

    def __gt__(self,other):
        return self.__salary > other.__salary

p1 = Employee(1000)
p2 = Employee(2000)

p1.set_salary(15000)
p1.set_salary(20000)
p1.set_salary(30000)

print(p1>p2)
Employee.count

sal has been updated
sal has been updated
sal has been updated
True

[15000, 20000, 30000]

In [1]:
# 30. Design a complete system combining:
# • Abstract class Vehicle
# • Multiple inheritance (Electric + Fuel)
# • Operator overloading (compare by speed)
# • Private attributes + getter/setter
# • Custom exceptions
# • File handling to save vehicle details
# • Duck Typing for start() method


from abc import ABC, abstractmethod

class SpeedError(Exception):
    pass

# Abstract Class
class Vehicle(ABC):
    def __init__(self, speed):
        self.set_speed(speed)

    def get_speed(self):
        return self.__speed

    def set_speed(self, speed):
        if speed < 0:
            raise SpeedError("Invalid Speed")
        self.__speed = speed

    @abstractmethod
    def drive(self):
        pass

    def __gt__(self, other):
        return self.get_speed() > other.get_speed()

class Electric:
    pass

class Fuel:
    pass


class Car(Vehicle, Electric, Fuel):
    def drive(self):
        print("Car is driving")

    def save(self):
        with open("vehicle.txt", "a") as f:
            f.write(f"Speed = {self.get_speed()}\n")

class Bike:
    def start(self):
        print("Bike Started")

class Bus:
    def start(self):
        print("Bus Started")

def begin(x):
    x.start()

try:
    c1 = Car(120)
    c2 = Car(90)

    c1.drive()

    if c1 > c2:
        print("Car 1 is Faster")
    else:
        print("Car 2 is Faster")

    c1.save()

    begin(Bike())
    begin(Bus())

except SpeedError as e:
    print(e)

Car is driving
Car 1 is Faster
Bike Started
Bus Started