In [207]:
# Q1. Load the dataset
# Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
# Then display the first 10 rows.
# Use: pd.read_csv(), head()

import pandas as pd
df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\customer_analytics - customer_analytics.csv")
df.head()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7

In [208]:
# Q2. Inspect the end of the dataset
# Display the last 15 rows.
# Use: tail()

df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [209]:
# Q3. Random inspection
# Display 10 random records.
# Use: sample()

df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1423,101958,70,187331,NaN,501,11,Delhi,Retail,Agent,2023-10-02 00:00:00,Yes,High,NaN,4,4.6
864,100979,47,60262,209182.63,786,4,Pune,Premium,Agent,2022-05-22 00:00:00,Yes,Low,13888.22,29,4.1
1150,101579,64,233015,NaN,338,12,Bangalore,Premium,Online,2024-06-18 00:00:00,Yes,High,23702.31,54,5.9
1114,101164,36,64279,193277.02,667,13,Hyderabad,SME,Online,2024-11-14 00:00:00,Yes,Medium,45906.51,26,9.9
1391,100279,69,99441,174977.25,586,6,Chennai,Corporate,Online,2023-03-29 00:00:00,NaN,Medium,9856.34,112,1.4
828,101855,62,215747,86475.47,375,14,Chennai,Premium,Agent,2026-01-21 00:00:00,No,High,15186.96,31,7.4
1915,100380,20,136822,173752.58,630,7,Pune,Corporate,Branch,2022-04-30 00:00:00,no,Medium,24760.9,132,1.7
139,100465,46,227332,206999.92,656,6,Delhi,Corporate,Online,2024-08-14 00:00:00,Yes,Medium,6078.54,123,7.0
1570,100538,75,57556,132.83,793,4,Bangalore,Retail,Agent,2021-04-01 00:00:00,Yes,High,23017.88,110,2.9
732,100222,23,NaN,220208.93,639,11,Mumbai,Premium,Online,2024-08-01 00:00:00,No,Medium,14970.5,12,9.4

In [210]:
# Q4. Dataset audit
# Use info() to identify:
# • Number of rows
# • Number of columns
# • Columns with missing values
# • Columns having incorrect/object datatypes
# Use: info()

df.info()
df.shape  # count of number of rows and columns
df.size   # counts the number of total values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

30600

In [211]:
# Q5. Missing-value audit
# Calculate the number of missing values in every column.
# Then verify the result using both:
# isnull()
# and
# isna()

df.isnull().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [212]:
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [213]:
# Q6. Duplicate investigation
# Find how many duplicate rows exist.
# Do not remove them yet.
# Use: duplicated()

df.duplicated().sum()

np.int64(40)

In [214]:
# Q7. Remove duplicates
# Remove all duplicate records and store the cleaned result back into df.
# Then verify that duplicates no longer exist.
# Use: drop_duplicates(), duplicated()
df1 = df.drop_duplicates()
df1

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [215]:
df.duplicated().sum()

np.int64(40)

In [216]:
# Q8. Numeric column investigation
# Select only numeric columns.
# Identify which columns are currently numeric and which potentially numeric columns have
# become object because of invalid values.
# Use: select_dtypes()

df.select_dtypes(int).sum()
df.select_dtypes(float).sum()

Satisfaction_Score    10940.0
dtype: float64

In [217]:
# Q9. Fix Age
# The Age column contains:
# • Valid numbers
# • Missing values
# • Invalid text such as unknown, N/A, etc.
# Convert Age into a proper numeric column.
# Invalid values should become missing values.
# Then fill missing Age values using the median age.
# Use: pd.to_numeric(), median(), fillna()

df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [218]:
df["Age"]= pd.to_numeric(df["Age"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [219]:
age_median = df['Age'].median()
age_median

47.0

In [220]:
df['Age'] = df['Age'].fillna(age_median)
df['Age'] = df['Age'].astype("int")
df['Age']

0       55
1       32
2       23
3       66
4       67
        ..
2035    42
2036    31
2037    25
2038    64
2039    55
Name: Age, Length: 2040, dtype: int64

In [221]:
# Q10. Fix Annual Income
# Clean Annual_Income.
# Requirements:
# 1. Convert invalid values to missing.
# 2. Convert the column to a numeric datatype.
# 3. Calculate the median.
# 4. Fill missing values using the median.
# Use: pd.to_numeric(), median(), fillna(), astype()

df["Annual_Income"]= pd.to_numeric(df["Annual_Income"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [222]:
AI = df["Annual_Income"].median()
AI

139999.5

In [223]:
df["Annual_Income"] = df["Annual_Income"].fillna(AI)
df["Annual_Income"] = df["Annual_Income"].astype("int")
df["Annual_Income"]

0        44033
1       215546
2       226403
3        87824
4        31570
         ...
2035     88530
2036    205738
2037    211994
2038     30105
2039    248332
Name: Annual_Income, Length: 2040, dtype: int64

In [224]:
# Q11. Clean Account Balance
# The Account_Balance column contains invalid strings and missing values.
# Clean the column and replace missing values with the mean Account Balance.
# Use:
# • pd.to_numeric()
# • mean()
# • fillna()

df["Account_Balance"]= pd.to_numeric(df["Annual_Income"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [225]:
AB = df["Account_Balance"].median()
AB

139999.0

In [226]:
df["Account_Balance"] = df["Account_Balance"].fillna(AB)
df["Account_Balance"] = df["Account_Balance"].astype("int")
df["Account_Balance"]

0        44033
1       215546
2       226403
3        87824
4        31570
         ...
2035     88530
2036    205738
2037    211994
2038     30105
2039    248332
Name: Account_Balance, Length: 2040, dtype: int64

In [227]:
# Q12. Clean Credit Score
# Clean Credit_Score.
# Invalid values should become missing.
# Then replace missing values with the median Credit Score.
# Finally convert the column to integer.
# Use:
# • pd.to_numeric()
# • median()
# • fillna()
# • astype()

df["Credit_Score"]= pd.to_numeric(df["Credit_Score"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,44033,772.0,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,215546,374.0,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,226403,668.0,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,87824,315.0,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,31570,370.0,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677.0,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,205738,392.0,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,211994,737.0,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,30105,794.0,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,248332,783.0,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [228]:
cs = df["Credit_Score"].median()
cs

570.0

In [229]:
df["Credit_Score"] = df["Credit_Score"].fillna(cs)
df["Credit_Score"]= df["Credit_Score"].astype("int")
df["Credit_Score"]

0       772
1       374
2       668
3       315
4       370
       ...
2035    677
2036    392
2037    737
2038    794
2039    783
Name: Credit_Score, Length: 2040, dtype: int64

In [230]:
# Q13. Clean Monthly Spend
# Clean Monthly_Spend.
# Then:
# • Convert it to numeric.
# • Replace invalid values.
# • Replace missing values using the median.
# • Make sure the final column is numeric.

df["Monthly_Spend"]= pd.to_numeric(df["Monthly_Spend"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [231]:
ms = df["Monthly_Spend"].median()
ms

24646.77

In [232]:
df["Monthly_Spend"] = df["Monthly_Spend"].fillna(ms)
df["Monthly_Spend"] = df["Monthly_Spend"].astype("int")
df["Monthly_Spend"]

0       23066
1       24646
2       28536
3       12869
4       34163
        ...
2035     8455
2036    34087
2037    26518
2038    20943
2039    48511
Name: Monthly_Spend, Length: 2040, dtype: int64

In [233]:
# Q14. Clean Transactions
# The Transactions column contains invalid strings.
# Convert it to numeric and replace invalid values with the median number of transactions.
# Then convert the final column to integer.

df["Transactions"]= pd.to_numeric(df["Transactions"],errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135.0,3.1
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106.0,8.2
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146.0,6.3
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115.0,9.7
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94.0,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119.0,8.6
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134.0,2.6
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87.0,1.3
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107.0,9.3
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119.0,3.1

In [234]:
ts = df["Transactions"].median()
ts

76.0

In [235]:
df["Transactions"] = df["Transactions"].fillna(ts)
df["Transactions"] = df["Transactions"].astype("int")
df["Transactions"]

0       135
1       106
2       146
3       115
4        94
       ...
2035    119
2036    134
2037     87
2038    107
2039    119
Name: Transactions, Length: 2040, dtype: int64

In [236]:
# Q15. Clean Satisfaction Score
# Clean Satisfaction_Score.
# Replace missing/invalid values using the mean Satisfaction Score.
# Then convert the column to float.

df["Satisfaction_Score"]=pd.to_numeric(df["Satisfaction_Score"], errors = "coerce")
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1

In [237]:
ss = df["Satisfaction_Score"].mean()

df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(ss)
df["Satisfaction_Score"] = df["Satisfaction_Score"].astype("float")
df["Satisfaction_Score"]

0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2040, dtype: float64

In [238]:
# Q16. Investigate Join_Date
# Inspect the Join_Date column.
# Identify the problems caused by:
# • Missing dates
# • Different date formats
# • Invalid date strings
# Do not clean it yet.

df["Join_Date"].isna().sum()

np.int64(102)

In [239]:
df['Join_Date'].unique()

array(['2022-08-15 00:00:00', '2025-01-11 00:00:00',
       '2024-08-01 00:00:00', ..., '2025-09-10 00:00:00',
       '2022-10-17 00:00:00', '2023-08-26 00:00:00'],
      shape=(1226,), dtype=object)

In [240]:
dates = pd.to_datetime(df['Join_Date'], errors='coerce')
dates

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039          NaT
Name: Join_Date, Length: 2040, dtype: datetime64[ns]

In [241]:
# Q17. Convert Join_Date
# Convert Join_Date into a proper Pandas datetime column.
# Any invalid dates should become missing values.
# Use: pd.to_datetime()

Join_Date = pd.to_datetime(df['Join_Date'], errors='coerce')
Join_Date

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039          NaT
Name: Join_Date, Length: 2040, dtype: datetime64[ns]

In [242]:
# Q18. Handle missing dates
# After conversion, find how many missing dates remain.
# Then replace missing dates appropriately using a reasonable date-based strategy.

np.int64(102)

In [243]:
# Q19. Clean City
# The City column contains values such as:
# Mumbai
# mumbai
# Mumbai
# mumbai
# Standardize the values so that logically identical cities are represented consistently.
# Then check the unique frequency distribution.
# Use: replace(), value_counts()

df["City"]

0       Bangalore
1           Delhi
2         Chennai
3          Mumbai
4       bangalore
          ...
2035    Hyderabad
2036       Mumbai
2037      Kolkata
2038    Bangalore
2039      Chennai
Name: City, Length: 2040, dtype: object

In [244]:
df.replace({'City': {'mumbai':'Mumbai'}},inplace = True)
df["City"].value_counts()

City
Mumbai       314
Hyderabad    278
Delhi        273
Kolkata      262
Pune         256
Chennai      242
Bangalore    236
hyderabad     20
bangalore     18
pune          18
delhi         15
kolkata       14
chennai       13
Name: count, dtype: int64

In [245]:
# Q20. Analyze Segment
# Check the frequency of:
# Retail
# SME
# Corporate
# Premium
# Also determine whether missing values exist.
# Then replace missing Segment values with the most appropriate category based on your
# analysis.
# Use: value_counts(), fillna()

df["Segment"].value_counts()

Segment
Premium      523
Retail       481
Corporate    475
SME          456
Name: count, dtype: int64

In [246]:
ds= "value"
df["Segment"] = df["Segment"].fillna(ds)
df["Segment"]

0             SME
1          Retail
2         Premium
3         Premium
4          Retail
          ...
2035       Retail
2036    Corporate
2037       Retail
2038       Retail
2039       Retail
Name: Segment, Length: 2040, dtype: object

In [247]:
df["Segment"].value_counts()

Segment
Premium      523
Retail       481
Corporate    475
SME          456
value        105
Name: count, dtype: int64

In [248]:
# Q21. Clean Active
# Active is supposed to be a binary column, but it contains:
# Yes
# No
# Y
# N
# YES
# NO
# yes
# no
# 1
# 0
#Transform these into a consistent representation:
# Yes
#No
#Then verify the result with value_counts().
#Use: replace(), value_counts()
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1

In [249]:
df["Active"].value_counts()

Active
Yes    1313
No      546
0        17
Y        17
N        16
no       16
NO       15
YES      15
yes      14
1        12
Name: count, dtype: int64

In [250]:
df.replace({'Active': {'0':'No', '1':'Yes', 'Y':'Yes', 'N':'No', 'yes':'Yes', 'no':'No'}},inplace = True)
df["Active"].value_counts()

Active
Yes    1356
No      595
NO       15
YES      15
Name: count, dtype: int64

In [251]:
# Q22. Clean Risk_Level
# Check the distribution of:
# High
# Medium
# Low
# Verify whether missing values exist.
# Then display the final class distribution.

df["Risk_Level"].value_counts()

Risk_Level
High      1009
Low        548
Medium     483
Name: count, dtype: int64

In [252]:
n1 = "missing value"
df["Risk_Level"] = df["Risk_Level"].fillna(n1)
df["Risk_Level"].value_counts()

Risk_Level
High      1009
Low        548
Medium     483
Name: count, dtype: int64

In [253]:
# Q23. Rename columns
# Rename these columns:
# Customer_ID → Customer_ID
# Annual_Income → AnnualIncome
# Account_Balance → AccountBalance
# Credit_Score → CreditScore
# Tenure_Years → Tenure
# Join_Date → CustomerJoinDate
# Risk_Level → RiskLevel
# Monthly_Spend → MonthlySpend
# Satisfaction_Score → SatisfactionScore
# Use rename().

df.rename(columns ={"Customer_ID":"Customer_ID",
                    "Annual_Income":"AnnualIncome",
                    "Credit_Score":"CreditScore",
                    "Tenure_Years":"Tenure",
                    "Join_Date":"CustomerJoinDate",
                    "Risk_Level":"RiskLevel",
                    "Monthly_Spend":"MonthlySpend",
                    "Satisfaction_Score":"SatisfactionScore"}, inplace = True)
df

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1

In [254]:
# Q24. Add a prefix
# Add:
# Customer_
# to every column.
# Example:
# Age
# becomes:
# Customer_Age
# Use: add_prefix()

df.add_prefix("Customer_")

,Customer_Customer_ID,Customer_Age,Customer_AnnualIncome,Customer_Account_Balance,Customer_CreditScore,Customer_Tenure,Customer_City,Customer_Segment,Customer_Channel,Customer_CustomerJoinDate,Customer_Active,Customer_RiskLevel,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1

In [255]:
# Q25. Remove unnecessary column
# Determine whether Customer_ID should be retained for analysis.
# Create a cleaned DataFrame without the identifier column.
# Use: drop()

df["Customer_ID"].value_counts()

Customer_ID
101610    2
100375    2
100945    2
100906    2
100030    2
         ..
100907    1
101819    1
101271    1
101188    1
101127    1
Name: count, Length: 2000, dtype: int64

In [256]:
df_cleaned = df.drop("Customer_ID", axis=1)
df_cleaned

,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore
0,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1
1,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2
2,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3
3,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7
4,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6
2036,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6
2037,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3
2038,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3
2039,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1

In [257]:
# Q26. Create Annual Income in Lakhs
# Create:
# Income_Lakhs
# using:
# AnnualIncome / 100000
# Then check the first 10 records.

df["AnnualIncome"] = pd.to_numeric(df["AnnualIncome"], errors="coerce")

df["Income_Lakhs"] = df["AnnualIncome"] / 100000

df

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1,0.44033
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2,2.15546
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3,2.26403
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7,0.87824
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7,0.31570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6,0.88530
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6,2.05738
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3,2.11994
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3,0.30105
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1,2.48332

In [258]:
# Q27. Create Monthly Income
# Create:
# MonthlyIncome
# using:
# AnnualIncome / 12
# Then create:
# Income_After_Spending
# using:
# MonthlyIncome - MonthlySpend


df["MonthlyIncome"] = df["AnnualIncome"] / 12
df["Income_After_Spending"] = df["MonthlyIncome"] - df["MonthlySpend"]
df

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1,0.44033,3669.416667,-19396.583333
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2,2.15546,17962.166667,-6683.833333
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3,2.26403,18866.916667,-9669.083333
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7,0.87824,7318.666667,-5550.333333
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7,0.31570,2630.833333,-31532.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6,0.88530,7377.500000,-1077.500000
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6,2.05738,17144.833333,-16942.166667
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3,2.11994,17666.166667,-8851.833333
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3,0.30105,2508.750000,-18434.250000
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1,2.48332,20694.333333,-27816.666667

In [259]:
# Q28. Create Balance-to-Income Ratio
# Create:
# Balance_Income_Ratio
# using:
# AccountBalance / AnnualIncome
# Then inspect the first 10 rows.
# Think carefully about division by zero and missing values.

df["Balance_Income_Ratio"] = df["Account_Balance"] / df["AnnualIncome"]
df.head(10)

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1,0.44033,3669.416667,-19396.583333,1.0
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2,2.15546,17962.166667,-6683.833333,1.0
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3,2.26403,18866.916667,-9669.083333,1.0
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7,0.87824,7318.666667,-5550.333333,1.0
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7,0.31570,2630.833333,-31532.166667,1.0
5,101334,68,37087,37087,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121,6,8.5,0.37087,3090.583333,-12030.416667,1.0
6,100415,47,67229,67229,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655,31,2.8,0.67229,5602.416667,-12052.583333,1.0
7,100983,65,139999,139999,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720,139,9.7,1.39999,11666.583333,9946.583333,1.0
8,100417,63,153267,153267,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043,76,7.1,1.53267,12772.250000,-25270.750000,1.0
9,101472,42,139999,139999,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472,124,9.1,1.39999,11666.583333,194.583333,1.0

In [260]:
# Q29. Prepare the ML-ready dataset
# Perform the following complete pipeline:
# 1. Load the dataset.
# 2. Inspect the first 10 rows.
# 3. Inspect the last 10 rows.
# 4. Inspect 10 random records.
# 5. Run info().
# 6. Check missing values.
# 7. Check duplicates.
# 8. Remove duplicates.
# 9. Clean all numeric columns.
# 10. Convert invalid numeric values to missing.
# 11. Fill numerical missing values appropriately.
# 12. Convert Join_Date to datetime.
# 13. Handle invalid dates.
# 14. Standardize categorical values.
# 15. Clean the binary Active column.
# 16. Rename the columns.
# 17. Remove unnecessary columns.
# 18. Verify the final datatypes.
# 19. Generate descriptive statistics.
# 20. Check categorical distributions.

df

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1,0.44033,3669.416667,-19396.583333,1.0
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2,2.15546,17962.166667,-6683.833333,1.0
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3,2.26403,18866.916667,-9669.083333,1.0
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7,0.87824,7318.666667,-5550.333333,1.0
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7,0.31570,2630.833333,-31532.166667,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6,0.88530,7377.500000,-1077.500000,1.0
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6,2.05738,17144.833333,-16942.166667,1.0
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3,2.11994,17666.166667,-8851.833333,1.0
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3,0.30105,2508.750000,-18434.250000,1.0
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1,2.48332,20694.333333,-27816.666667,1.0

In [261]:
df.head(10)

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1,0.44033,3669.416667,-19396.583333,1.0
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2,2.15546,17962.166667,-6683.833333,1.0
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3,2.26403,18866.916667,-9669.083333,1.0
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7,0.87824,7318.666667,-5550.333333,1.0
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7,0.31570,2630.833333,-31532.166667,1.0
5,101334,68,37087,37087,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121,6,8.5,0.37087,3090.583333,-12030.416667,1.0
6,100415,47,67229,67229,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655,31,2.8,0.67229,5602.416667,-12052.583333,1.0
7,100983,65,139999,139999,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720,139,9.7,1.39999,11666.583333,9946.583333,1.0
8,100417,63,153267,153267,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043,76,7.1,1.53267,12772.250000,-25270.750000,1.0
9,101472,42,139999,139999,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472,124,9.1,1.39999,11666.583333,194.583333,1.0

In [262]:
df.tail(10)

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
2030,100122,41,201611,201611,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815,58,7.2,2.01611,16800.916667,-2014.083333,1.0
2031,101639,61,128850,128850,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300,83,5.0,1.28850,10737.500000,-23562.500000,1.0
2032,101045,33,88037,88037,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,24646,147,9.7,0.88037,7336.416667,-17309.583333,1.0
2033,101725,43,122756,122756,487,8,Pune,value,Mobile,2021-07-04 00:00:00,No,High,10165,14,6.4,1.22756,10229.666667,64.666667,1.0
2034,101096,18,189232,189232,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227,85,5.9,1.89232,15769.333333,-11457.666667,1.0
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6,0.88530,7377.500000,-1077.500000,1.0
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6,2.05738,17144.833333,-16942.166667,1.0
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3,2.11994,17666.166667,-8851.833333,1.0
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3,0.30105,2508.750000,-18434.250000,1.0
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1,2.48332,20694.333333,-27816.666667,1.0

In [263]:
df.sample(10)

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
1816,101664,26,233139,233139,740,3,Kolkata,Corporate,Agent,2022-05-01 00:00:00,No,Low,23940,115,5.100000,2.33139,19428.250000,-4511.750000,1.0
210,101721,68,244780,244780,612,15,Bangalore,Retail,Mobile,2024-04-01 00:00:00,Yes,Medium,27489,100,3.600000,2.44780,20398.333333,-7090.666667,1.0
1399,100739,56,139999,139999,417,2,Kolkata,Retail,Online,2023-08-11 00:00:00,Yes,High,1720,96,5.300000,1.39999,11666.583333,9946.583333,1.0
199,100307,57,87768,87768,795,15,Kolkata,Corporate,Branch,2025-10-27 00:00:00,No,Low,32050,77,5.800000,0.87768,7314.000000,-24736.000000,1.0
1480,101459,38,212686,212686,348,1,Chennai,Corporate,Agent,2023-09-16 00:00:00,Yes,High,39930,50,3.500000,2.12686,17723.833333,-22206.166667,1.0
111,100240,66,154749,154749,433,11,Kolkata,Retail,Mobile,2021-08-18 00:00:00,Yes,High,40317,47,9.700000,1.54749,12895.750000,-27421.250000,1.0
656,101673,62,157970,157970,554,13,Mumbai,Retail,Branch,2025-08-27 00:00:00,No,Medium,7588,86,1.900000,1.57970,13164.166667,5576.166667,1.0
1963,101391,53,177889,177889,524,8,Mumbai,SME,Online,2021-06-30 00:00:00,No,High,24044,144,5.595908,1.77889,14824.083333,-9219.916667,1.0
1662,100957,21,207184,207184,843,8,Kolkata,Premium,Agent,2023-02-16 00:00:00,Yes,Low,42096,111,5.595908,2.07184,17265.333333,-24830.666667,1.0
1444,101920,47,235223,235223,826,11,Pune,SME,Online,2022-06-28 00:00:00,Yes,High,38821,146,4.200000,2.35223,19601.916667,-19219.083333,1.0

In [264]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            2040 non-null   int64
 1   Age                    2040 non-null   int64
 2   AnnualIncome           2040 non-null   int64
 3   Account_Balance        2040 non-null   int64
 4   CreditScore            2040 non-null   int64
 5   Tenure                 2040 non-null   int64
 6   City                   1959 non-null   object
 7   Segment                2040 non-null   object
 8   Channel                2040 non-null   object
 9   CustomerJoinDate       1938 non-null   object
 10  Active                 1981 non-null   object
 11  RiskLevel              2040 non-null   object
 12  MonthlySpend           2040 non-null   int64
 13  Transactions           2040 non-null   int64
 14  SatisfactionScore      2040 non-null   float64
 15  Income_Lakhs           2040 non-null   float64
 16  MonthlyIncome          2040 non-null   float64
 17  Income_After_Spending  2040 non-null   float64
 18  Balance_Income_Ratio   2040 non-null   float64
dtypes: float64(5), int64(8), object(6)
memory usage: 302.9+ KB

In [265]:
df.value_counts()

Customer_ID  Age  AnnualIncome  Account_Balance  CreditScore  Tenure  City       Segment    Channel  CustomerJoinDate     Active  RiskLevel  MonthlySpend  Transactions  SatisfactionScore  Income_Lakhs  MonthlyIncome  Income_After_Spending  Balance_Income_Ratio
101119       64   32099         32099            444          7       Mumbai     Retail     Agent    2023-09-28 00:00:00  No      High       24085         24            5.595908           0.32099       2674.916667    -21410.083333          1.0                     2
100129       50   139999        139999           667          13      Pune       Corporate  Online   2025-08-11 00:00:00  No      Medium     45092         115           8.700000           1.39999       11666.583333   -33425.416667          1.0                     2
101274       66   139999        139999           626          14      Chennai    Retail     Mobile   2024-05-01 00:00:00  Yes     Medium     28134         129           5.600000           1.39999       11666.583333   -16467.416667          1.0                     2
101084       74   170128        170128           632          7       Pune       SME        Agent    2025-12-11 00:00:00  Yes     Medium     21125         128           5.600000           1.70128       14177.333333   -6947.666667           1.0                     2
100030       29   139999        139999           389          3       Chennai    SME        Mobile   2024-12-07 00:00:00  Yes     High       24646         64            1.000000           1.39999       11666.583333   -12979.416667          1.0                     2
                                                                                                                                                                                                                                                                       ..
100653       34   71819         71819            373          9       Delhi      SME        Online   2021-02-26 00:00:00  Yes     High       42465         92            9.100000           0.71819       5984.916667    -36480.083333          1.0                     1
100652       40   167635        167635           396          8       Hyderabad  Retail     Mobile   2022-11-10 00:00:00  No      High       2429          68            4.800000           1.67635       13969.583333    11540.583333          1.0                     1
100651       52   183670        183670           508          6       Kolkata    Corporate  Branch   2024-01-04 00:00:00  Yes     High       13938         115           8.300000           1.83670       15305.833333    1367.833333           1.0                     1
100649       68   78551         78551            525          3       Pune       Retail     Branch   2024-10-23 00:00:00  Yes     High       1042          16            9.600000           0.78551       6545.916667     5503.916667           1.0                     1
102000       31   79245         79245            324          6       Bangalore  Premium    Online   2025-12-24 00:00:00  Yes     High       5314          16            1.400000           0.79245       6603.750000     1289.750000           1.0                     1
Name: count, Length: 1774, dtype: int64

In [266]:
df.duplicated().value_counts()

False    2000
True       40
Name: count, dtype: int64

In [267]:
df.drop_duplicates()

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1,0.44033,3669.416667,-19396.583333,1.0
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2,2.15546,17962.166667,-6683.833333,1.0
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3,2.26403,18866.916667,-9669.083333,1.0
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7,0.87824,7318.666667,-5550.333333,1.0
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7,0.31570,2630.833333,-31532.166667,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6,0.88530,7377.500000,-1077.500000,1.0
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6,2.05738,17144.833333,-16942.166667,1.0
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3,2.11994,17666.166667,-8851.833333,1.0
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3,0.30105,2508.750000,-18434.250000,1.0
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1,2.48332,20694.333333,-27816.666667,1.0

In [268]:
df["AnnualIncome"] = pd.to_numeric(df["AnnualIncome"], errors="coerce")

ss = df["SatisfactionScore"].mean()

df["SatisfactionScore"] = df["SatisfactionScore"].fillna(ss)
df["SatisfactionScore"] = df["SatisfactionScore"].astype("float")
df["SatisfactionScore"]

0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: SatisfactionScore, Length: 2040, dtype: float64

In [269]:
# 12. Convert Join_Date to datetime.
# 13. Handle invalid dates.
# 14. Standardize categorical values.
# 15. Clean the binary Active column.
# 16. Rename the columns.
# 17. Remove unnecessary columns.
# 18. Verify the final datatypes.
# 19. Generate descriptive statistics.
# 20. Check categorical distributions.


df.rename(columns ={"CustomerJoinDate":"datetime"},inplace = True)
df

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,City,Segment,Channel,datetime,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,101317,55,44033,44033,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066,135,3.1,0.44033,3669.416667,-19396.583333,1.0
1,101001,32,215546,215546,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,24646,106,8.2,2.15546,17962.166667,-6683.833333,1.0
2,101069,23,226403,226403,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536,146,6.3,2.26403,18866.916667,-9669.083333,1.0
3,101968,66,87824,87824,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869,115,9.7,0.87824,7318.666667,-5550.333333,1.0
4,100530,67,31570,31570,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163,94,3.7,0.31570,2630.833333,-31532.166667,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,88530,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455,119,8.6,0.88530,7377.500000,-1077.500000,1.0
2036,101295,31,205738,205738,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087,134,2.6,2.05738,17144.833333,-16942.166667,1.0
2037,100861,25,211994,211994,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518,87,1.3,2.11994,17666.166667,-8851.833333,1.0
2038,101460,64,30105,30105,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943,107,9.3,0.30105,2508.750000,-18434.250000,1.0
2039,101127,55,248332,248332,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511,119,3.1,2.48332,20694.333333,-27816.666667,1.0

In [270]:
df["datetime"].value_counts()

datetime
not_a_date             12
unknown                 8
31/99/2024              6
2022-06-26 00:00:00     5
2022-07-24 00:00:00     5
                       ..
2024-06-13 00:00:00     1
2025-10-10 00:00:00     1
2021-08-11 00:00:00     1
2023-01-25 00:00:00     1
2023-08-26 00:00:00     1
Name: count, Length: 1225, dtype: int64

In [271]:
df.describe()

,Customer_ID,Age,AnnualIncome,Account_Balance,CreditScore,Tenure,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
count,2040.000000,2040.000000,2040.000000,2040.000000,2040.000000,2040.000000,2040.000000,2040.000000,2040.000000,2040.000000,2040.000000,2040.000000,2040.0
mean,100999.696078,47.046569,138410.185784,138410.185784,575.917157,7.566176,24898.325490,75.517157,5.595908,1.384102,11534.182149,-13364.143342,1.0
std,577.289267,16.201868,61976.064320,61976.064320,160.601592,4.614468,13837.407507,42.639630,2.523697,0.619761,5164.672027,14822.880883,0.0
min,100001.000000,18.000000,25163.000000,25163.000000,300.000000,0.000000,559.000000,1.000000,1.000000,0.251630,2096.916667,-46902.666667,1.0
25%,100500.750000,34.000000,88800.500000,88800.500000,434.000000,4.000000,13235.250000,40.000000,3.600000,0.888005,7400.041667,-24620.208333,1.0
50%,100999.500000,47.000000,139999.000000,139999.000000,570.000000,8.000000,24646.000000,76.000000,5.595908,1.399990,11666.583333,-12979.416667,1.0
75%,101498.250000,61.000000,188679.750000,188679.750000,720.000000,12.000000,36371.000000,112.000000,7.700000,1.886798,15723.312500,-1923.895833,1.0
max,102000.000000,75.000000,249977.000000,249977.000000,850.000000,15.000000,49942.000000,149.000000,10.000000,2.499770,20831.416667,19643.083333,1.0

In [272]:
df.to_csv("paritosh.csv")

In [ ]:
# Q30 — Ultimate Pandas Cleaning Project
# You are a Data Scientist at a bank. Your raw customer dataset contains 2,000+ records with:
• Missing values
• Duplicate records
• Invalid numerical values
• Mixed datatypes
• Invalid dates
• Mixed date formats
• Inconsistent categorical values
• Binary text inconsistencies
• Unnecessary identifier columns
Your task is to produce a final clean analytical dataset.

Required workflow
Step 1 — Load
pd.read_csv()
Step 2 — Inspect
head()
tail()
sample()
info()

Step 3 — Missing-value analysis
isnull()
isna()

Step 4 — Duplicate handling
duplicated()
drop_duplicates()

Step 5 — Numeric cleaning
Clean:
Age
Annual_Income
Account_Balance
Credit_Score
Monthly_Spend
Transactions
Satisfaction_Score

Use:
pd.to_numeric()
mean()
median()
fillna()
astype()

Step 6 — Date cleaning
Clean:
Join_Date
using:
pd.to_datetime()

Step 7 — Categorical cleaning
Clean:
City
Segment
Channel
Active
Risk_Level
Use:
replace()
value_counts()
fillna()

Step 8 — Column transformation
Use:
rename()
add_prefix()
drop()

Step 9 — Create analytical features
Create at least these:
Income_Lakhs
MonthlyIncome
Income_After_Spending
Balance_Income_Ratio

Step 10 — Final validation
Your final DataFrame must pass these checks:
No duplicate rows
No invalid numeric values
No unexpected object datatype in numeric columns
No invalid dates
No inconsistent Yes/No values
Missing values handled
Column names standardized

Finally display:
head()
tail()
sample()
info()
describe()
value_counts()