In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("C:\\Users\\bhoom\\Downloads\\Hotel_booking_dataset - Hotel_booking_dataset.csv")
df.head()

,Booking ID,Customer Name,Booking Date,City,Room Type,Booking Channel,Customer Segment,Gender,Age,Room Nights,...,Rating,Guests,Is Member,Cancelled,Payment Method,Gross Amount,Discount Amount,Final Amount,Hotel Cost,Profit
0,BKG01888,Customer_1888,2025-05-17 00:00:00,Mumbai,Suite,Online,Premium,Male,39,4,...,1.4,2,1,0,Credit Card,31674.48,2096.850576,29577.629420,16901.386250,12676.243170
1,BKG00789,Customer_0789,2025-07-29 00:00:00,Bengaluru,Suite,Walk-in,Corporate,Male,25,1,...,2.5,2,1,0,Credit Card,4822.39,735.414475,4086.975525,2746.904163,1340.071362
2,BKG00757,Customer_0757,2025-10-19 00:00:00,Pune,Suite,Corporate,Corporate,Other,50,4,...,1.2,1,0,1,Credit Card,66334.52,15575.345300,50759.174700,40212.657470,10546.517240
3,BKG01079,Customer_1079,2025-12-14 00:00:00,Mumbai,Deluxe,Walk-in,Regular,Male,53,3,...,2.6,6,0,0,Debit Card,19255.92,5328.113064,13927.806940,9639.061764,4288.745172
4,BKG00218,Customer_0218,2025-01-20 00:00:00,Delhi,Suite,Travel Agent,Budget,Male,38,NaN,...,4.2,4,1,0,Cash,15685.38,5160.490020,10524.889980,6545.581304,3979.308676

In [2]:
# 1. Remove leading/trailing spaces from column names
#Explanation: Column names like "Booking ID " and "Customer Name" have extra spaces. This
#causes errors when you try to select columns. Just strip the spaces so names become clean
#(Booking ID, Customer Name).

for i in df.columns:
    print(i)

Booking ID
Customer Name
Booking Date
City
Room Type
Booking Channel
Customer Segment
Gender
Age
Room Nights
Room Rate
Discount %
Rating
Guests
Is Member
Cancelled
Payment Method
Gross Amount
Discount Amount
Final Amount
Hotel Cost
Profit

In [3]:
df.columns = df.columns.str.replace(' ','_')
for i in df.columns:
    print(i)

Booking_ID
Customer_Name
Booking_Date
City
Room_Type
Booking_Channel
Customer_Segment
Gender
Age
Room_Nights
Room_Rate
Discount_%
Rating
Guests
Is_Member
Cancelled
Payment_Method
Gross_Amount
Discount_Amount
Final_Amount
Hotel_Cost
Profit

In [4]:
# 2. Standardize all date formats into one consistent format (YYYY-MM-DD)
#Explanation: Dates appear as 2025-05-17 00:00:00, 2025/02/20, 15/01/2025, and even
#invalid ones like 32/13/2025. Convert everything to a single clean format and turn bad dates
#into missing values.

df["Booking_Date"]

0       2025-05-17 00:00:00
1       2025-07-29 00:00:00
2       2025-10-19 00:00:00
3       2025-12-14 00:00:00
4       2025-01-20 00:00:00
               ...
2020    2025-11-27 00:00:00
2021    2025-10-22 00:00:00
2022    2025-07-11 00:00:00
2023    2025-01-24 00:00:00
2024    2025-04-06 00:00:00
Name: Booking_Date, Length: 2025, dtype: object

In [5]:
df["Booking_Date"] = pd.to_datetime(df["Booking_Date"],errors="coerce")

In [6]:
df["Booking_Date"]

0      2025-05-17
1      2025-07-29
2      2025-10-19
3      2025-12-14
4      2025-01-20
          ...
2020   2025-11-27
2021   2025-10-22
2022   2025-07-11
2023   2025-01-24
2024   2025-04-06
Name: Booking_Date, Length: 2025, dtype: datetime64[ns]

In [7]:
# 3. Handle completely missing Customer Name values
#Explanation: Some rows have blank Customer Name or values like N/A. Decide whether to
#fill them with a placeholder (e.g., “Unknown”) or drop those rows, depending on whether
#the name is critical for analysis.

df["Customer_Name"]= df["Customer_Name"].dropna()

In [8]:
df = df.dropna(subset=["Customer_Name"])

In [9]:
df["Customer_Name"].isna().value_counts()

Customer_Name
False    1991
Name: count, dtype: int64

In [10]:
# 4. Fix inconsistent Gender values
# Explanation: Gender appears as Male, FEMALE, male, F, M, Other, etc. Convert everything to
# a standard set such as Male, Female, Other.

df["Gender"].value_counts()

Gender
Female    975
Male      924
Other      68
FEMALE      8
M           7
female      4
F           4
male        1
Name: count, dtype: int64

In [11]:
df = df.replace({"Gender":{"FEMALE":"Female",
                           "female":"Female",
                           "F":"Female",
                           "M":"Male",
                           "male":"Male"
                          }})
df["Gender"].unique()

array(['Male', 'Other', 'Female'], dtype=object)

In [12]:
# 5. Clean and standardize City names
#Explanation: Cities have typos and casing issues (mumbai, Mumbai , Bangalore, Hydrabad,
#blank). Correct spelling, remove extra spaces, and make casing consistent (e.g., Title Case).

df["City"].unique()

array(['Mumbai', 'Bengaluru', 'Pune', 'Delhi', 'Chennai', 'Hyderabad',
       nan, 'mumbai', 'delhi', 'Bangalore', 'MUMBAI', 'Hydrabad',
       'bangalore'], dtype=object)

In [13]:
df=df.replace({"City":{"delhi":"Delhi",
                       "mumbai":"Mumbai",
                       "MUMBAI":"Mumbai",
                       "Bangalore":"Bengaluru",
                       "Hydrabad":"Hyderabad"
                      }})
df["City"].unique()

array(['Mumbai', 'Bengaluru', 'Pune', 'Delhi', 'Chennai', 'Hyderabad',
       nan, 'bangalore'], dtype=object)

In [14]:
# 6. Standardize Room Type categories
#Explanation: Room Type has Suite, Deluxe, delux, standard, exec, Unknown, and blanks.
#Map similar values to a clean list: Standard, Deluxe, Suite, Executive.

df["Room_Type"].unique()

array(['Suite', 'Deluxe', 'Standard', 'Executive', nan, 'standard',
       'STANDARD', 'delux', 'exec', 'Unknown', 'suite'], dtype=object)

In [15]:
df=df.replace({"Room_Type":{"standard":"Standard",
                            "STANDARD":"Standard",
                            "delux":"Deluxe",
                            "exec":"Executive",
                            "suite":"Suite"
                           }})
df["Room_Type"].unique()

array(['Suite', 'Deluxe', 'Standard', 'Executive', nan, 'Unknown'],
      dtype=object)

In [16]:
# 7. Clean Booking Channel values
#Explanation: Values include Online, online, Walk-in, Travel Agent, TravelAgent, corp,
#Corporate. Unify them into a small consistent set (Online, Walk-in, Corporate, Travel Agent).

df["Booking_Channel"].unique()

array(['Online', 'Walk-in', 'Corporate', 'Travel Agent', 'corp', 'online',
       'walkin', 'ONLINE', 'TravelAgent', 'travel agent'], dtype=object)

In [17]:
df=df.replace({"Booking_Channel":{"corp":"Corporate",
                                  "online":"Online",
                                  "walkin":"Walk-in",
                                  "ONLINE":"Online",
                                  "TravelAgent":"Travel Agent",
                                  "travel agent":"Travel Agent"
                                 }})
df["Booking_Channel"].unique()

array(['Online', 'Walk-in', 'Corporate', 'Travel Agent'], dtype=object)

In [18]:
# 8. Standardize Customer Segment
#Explanation: Segments appear as Premium, regular, REG, Budget , VIP, etc. Create a clean set
#such as Budget, Regular, Premium, Corporate, VIP and map everything to it.

df["Customer_Segment"].unique()

array(['Premium', 'Corporate', 'Regular', 'Budget', 'regular', 'VIP',
       'REG', 'premium', 'budget', 'corporate'], dtype=object)

In [19]:
df=df.replace({"Customer_Segment":{"regular":"Regular",
                                   "REG":"Regular",
                                   "premium":"Premium",
                                   "budget":"Budget",
                                   "corporate":"Corporate"
                                  }})
df["Customer_Segment"].unique()

array(['Premium', 'Corporate', 'Regular', 'Budget', 'VIP'], dtype=object)

In [20]:
# 9. Fix Age column (invalid and non-numeric values)
#Explanation: Age has numbers, blanks, 30 yrs, 25 years, 45Y, and impossible values like 150
#or 100. Extract the number, convert to integer, and set unrealistic ages (e.g., <18 or >100) to
#missing.

df["Age"].unique()

array(['39', '25', '50', '53', '38', '35', '33', '65', '48', '47', '52',
       '44', nan, '29', '49', '34', '58', '42', '19', '28', '62', '64',
       '21', '57', '22', '59', '26', '54', '46', '31', '67', '24', '68',
       '32', '27', '56', '36', '61', '100', '60', '43', '20', '66', '51',
       '30', '40', '18', '23', '63', '45', '69', '41', '150', '37', '55',
       '120', 'unknown', '25 years', '45Y', '30 yrs'], dtype=object)

In [21]:
df=df.replace({"Age":{"30 yrs":30,
                      "45Y":45,
                      "25 years":25,
                      "120":"missing",
                      "150":"missing",
                      "100":"missing"
                     }})
df["Age"].unique()

array(['39', '25', '50', '53', '38', '35', '33', '65', '48', '47', '52',
       '44', nan, '29', '49', '34', '58', '42', '19', '28', '62', '64',
       '21', '57', '22', '59', '26', '54', '46', '31', '67', '24', '68',
       '32', '27', '56', '36', '61', 'missing', '60', '43', '20', '66',
       '51', '30', '40', '18', '23', '63', '45', '69', '41', '37', '55',
       'unknown', 25, 45, 30], dtype=object)

In [22]:
# 10. Clean Room Nights column
#Explanation: Values include numbers, N/A, 3 nights, 100, 30. Extract only the numeric part,
#convert to integer, and decide what to do with extreme values (e.g., 100 nights).

df["Room_Nights"].unique()

array(['4', '1', '3', nan, '2', '5', '100', '7', '6', '30', '3 nights',
       'two', '5 days', '50'], dtype=object)

In [23]:
df=df.replace({"Room_Nights":{"5 days":5,
                              "two":2,
                              "3 nights":3,
                              "100":np.nan,
                              "50":np.nan
                             }})
df["Room_Nights"].unique()

array(['4', '1', '3', nan, '2', '5', '7', '6', '30', 3, 2, 5],
      dtype=object)

In [24]:
# 11. Fix Room Rate (mixed formats and extreme values)
#Explanation: Room Rate contains normal numbers, 15k, $8000, 12000 INR, 100000, 250000,
#and blanks. Convert text formats to numbers, remove currency symbols, and flag or handle
#unrealistic rates.

for i in df["Room_Rate"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

15k
$8000
12000 INR
₹5000
unknown

In [25]:
df=df.replace({"Room_Rate":{"15k":15000,
                            "$8000":8000,
                            "12000 INR":12000,
                            "₹5000":5000
                           }})

In [26]:
for i in df["Room_Rate"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

unknown

In [27]:
df['Room_Rate'] = pd.to_numeric(df['Room_Rate'], errors='coerce')
df['Room_Rate'].dtypes

dtype('float64')

In [28]:
# 12. Clean Discount % column
#Explanation: Discount has numbers, none, 10%, 5 %, N/A, and impossible values like 120.
#Convert everything to a pure number between 0 and 100; treat “none” as 0 and values >100
#as missing or capped.

df["Discount_%"].unique()

array(['6.62', '15.25', '23.48', ..., '34.26', '29.05', '13.41'],
      shape=(1463,), dtype=object)

In [29]:
df["Discount_%"] = df["Discount_%"].replace("none", 0)
df["Discount_%"] = df["Discount_%"].replace("N/A", np.nan)

In [30]:
df["Discount_%"] = df["Discount_%"].astype(str).str.replace("%", "", regex=False)

In [31]:
df["Discount_%"] = pd.to_numeric(df["Discount_%"], errors="coerce")

In [32]:
df.loc[df["Discount_%"] > 100, "Discount_%"] = np.nan

In [33]:
df["Discount_%"].unique()

array([ 6.62, 15.25, 23.48, ..., 34.26, 29.05, 13.41], shape=(1459,))

In [34]:
# 13. Handle missing and invalid Rating values
#Explanation: Rating has numbers, blanks, 5/5, 4 stars, and values above 5 (e.g., 6, 9).
#Convert to a 1–5 scale and set invalid entries to missing.

df["Rating"].unique()

array(['1.4', '2.5', '1.2', '2.6', '4.2', nan, '3.6', '2.3', '4.1', '4.5',
       '4.6', '2.8', '2.4', '4.8', '2.9', '2.7', '4', '1', '1.8', '3.8',
       '1.5', '3.7', '1.7', '3', '2.1', '1.1', '1.9', '3.2', '1.6', '1.3',
       '3.4', '2.2', '3.5', '4.4', '4.9', '4.7', '5', '3.1', '3.9', '4.3',
       '2', '6', '3.3', 'good', '5/5', '4 stars', '0', '9'], dtype=object)

In [35]:
for i in df["Rating"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

good
5/5
4 stars

In [36]:
df=df.replace({"Rating":{"good":"missing",
                         "5/5":5,
                         "4 stars":4,
                         "0":"missing"
                           }})
df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")

In [37]:
df.loc[(df["Rating"] < 1) | (df["Rating"] > 5), "Rating"]

130     6.0
167     6.0
190     6.0
1003    6.0
1578    6.0
1699    6.0
1787    9.0
1789    9.0
Name: Rating, dtype: float64

In [38]:
df.loc[(df["Rating"] < 1) | (df["Rating"] > 5), "Rating"] = np.nan

In [39]:
df["Rating"].unique()

array([1.4, 2.5, 1.2, 2.6, 4.2, nan, 3.6, 2.3, 4.1, 4.5, 4.6, 2.8, 2.4,
       4.8, 2.9, 2.7, 4. , 1. , 1.8, 3.8, 1.5, 3.7, 1.7, 3. , 2.1, 1.1,
       1.9, 3.2, 1.6, 1.3, 3.4, 2.2, 3.5, 4.4, 4.9, 4.7, 5. , 3.1, 3.9,
       4.3, 2. , 3.3])

In [40]:
# 14. Clean Guests column (extreme values)
#Explanation: Most values are reasonable (1–6), but some are 15, 25, or 40. Decide a sensible
#maximum (e.g., 10) and set higher values to missing or investigate them.

df.loc[df["Guests"] > 10, "Guests"] = np.nan

In [41]:
df["Guests"].unique()

array([ 2.,  1.,  6.,  4.,  3.,  5., nan])

In [42]:
# 15. Standardize Is Member column
#Explanation: Values are mixed: 1, 0, Y, Yes, Member, blanks. Convert everything to a clear
#Yes/No or 1/0 format.

df["Is_Member"].unique()

array(['1', '0', 'Y', 'Yes', 'N', 'Non-Member', 'No', 'Member'],
      dtype=object)

In [43]:
df = df.replace({"Is_Member": {
    "1": 1,
    "Y": 1,
    "Yes": 1,
    "Member": 1,
    "0": 0,
    "N": 0,
    "No": 0,
    "Non-Member": 0
}})

C:\Users\bhoom\AppData\Local\Temp\ipykernel_14964\1973563231.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({"Is_Member": {

In [44]:
df["Is_Member"] = df["Is_Member"].replace("", np.nan)
df["Is_Member"].unique()

array([1, 0])

In [45]:
# 16. Standardize Cancelled column
#Explanation: Cancelled appears as 0, 1, Yes, Y, N. Convert to a consistent 0/1 or Yes/No
#format.

df["Cancelled"].unique()

array(['0', '1', 'Yes', 'Y', 'Not Cancelled', 'No', 'N', 'Cancelled'],
      dtype=object)

In [46]:
df= df.replace({"Cancelled":{
    "1": 1,
    "Yes": 1,
    "Y": 1,
    "Cancelled": 1,
    "0": 0,
    "No": 0,
    "N": 0,
    "Not Cancelled": 0
}})

C:\Users\bhoom\AppData\Local\Temp\ipykernel_14964\2698894226.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df= df.replace({"Cancelled":{

In [47]:
df["Cancelled"].unique()

array([0, 1])

In [48]:
# 17. Clean Payment Method values
#Explanation: Payment methods have inconsistent casing and spacing (Credit Card, credit
#card, upi, Net Banking, cash , blanks). Standardize to a clean list (Credit Card, Debit Card, UPI,
#Net Banking, Cash).

df["Payment_Method"].unique()

array(['Credit Card', 'Debit Card', 'Cash', 'UPI', 'netbanking',
       'Net Banking', 'upi', nan, 'cash', 'CreditCard', 'credit card'],
      dtype=object)

In [49]:
df= df.replace({"Payment_Method":{
    "netbanking":"Net Banking",
    "upi":"UPI",
    "cash":"Cash",
    "CreditCard":"Credit Card",
    "credit card":"Credit Card"}})

In [50]:
df["Payment_Method"].unique()

array(['Credit Card', 'Debit Card', 'Cash', 'UPI', 'Net Banking', nan],
      dtype=object)

In [51]:
# 18. Remove or flag duplicate Booking IDs
#Explanation: Some Booking IDs (e.g., BKG00042, BKG01640) appear more than once. Decide
#whether to keep the first occurrence, the most complete row, or mark them for review.

df["Booking_ID"].duplicated().sum()

np.int64(25)

In [52]:
df = df.drop_duplicates(subset="Booking_ID", keep="first")

In [53]:
df["Booking_ID"].duplicated().sum()

np.int64(0)

In [54]:
# 19. Handle missing Room Type values
#Explanation: Some rows have blank Room Type. You can either drop those rows, fill with
#“Unknown”, or try to infer from other columns if possible.

df["Room_Type"].isna().sum()

np.int64(29)

In [55]:
df["Room_Type"].isna().sum()

np.int64(29)

In [56]:
# 20. Fix inconsistent Final Amount calculations
#Explanation: Final Amount should roughly equal Gross Amount − Discount Amount, but
#some rows have missing Final Amount or clear calculation errors. Recalculate or flag
#inconsistencies.

df["Calculated_Final_Amount"] = df["Gross_Amount"] - df["Discount_Amount"]

In [57]:
df[df["Final_Amount"] != df["Calculated_Final_Amount"]][
    ["Gross_Amount", "Discount_Amount", "Final_Amount", "Calculated_Final_Amount"]
]

      Gross_Amount  Discount_Amount  Final_Amount  Calculated_Final_Amount
0         31674.48      2096.850576  29577.629420             29577.629424
1          4822.39       735.414475   4086.975525              4086.975525
3         19255.92      5328.113064  13927.806940             13927.806936
6         22290.58      7663.501404  14627.078600             14627.078596
8         32952.69      5246.068248  27706.621750             27706.621752
...            ...              ...           ...                      ...
2014      11617.18      3302.764274           NaN              8314.415726
2016      29196.96      3001.447488  26195.512510             26195.512512
2019      45711.03       361.117137  45349.912860             45349.912863
2023      18041.10      5910.264360  12130.835640             12130.835640
2024       7644.65      1025.147565   6619.502435              6619.502435

[1130 rows x 4 columns]

In [58]:
df["Final_Amount"] = df["Gross_Amount"] - df["Discount_Amount"]

In [59]:
df[["Gross_Amount", "Discount_Amount", "Final_Amount"]].head()

   Gross_Amount  Discount_Amount  Final_Amount
0      31674.48      2096.850576  29577.629424
1       4822.39       735.414475   4086.975525
2      66334.52     15575.345300  50759.174700
3      19255.92      5328.113064  13927.806936
4      15685.38      5160.490020  10524.889980

In [60]:
# 21. Clean Customer Name (placeholder and invalid names)
#Explanation: Names include Customer_1888, 12345, john doe, N/A, blanks. Decide how to
#treat non-real names (keep as-is, replace with “Unknown”, or drop).

In [61]:
df = df[df["Customer_Name"].astype(str).str.isnumeric()]

In [62]:
df = df[df["Customer_Name"].astype(str).str.startswith("Customer_")]

In [63]:
df["Customer_Name"].unique()

array([], dtype=object)

In [64]:
# 22. Convert all numeric columns to proper numeric data types
#Explanation: Many columns that should be numbers are currently stored as text because of
#mixed formats. Convert them to integer or float so calculations work correctly.

int_columns = [
    "Age",
    "Room_Nights",
    "Guests",
    "Is_Member",
    "Cancelled"
]

In [65]:
for col in int_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [66]:
float_columns = [
    "Room_Rate",
    "Discount_%",
    "Rating",
    "Gross_Amount",
    "Discount_Amount",
    "Final_Amount",
    "Hotel_Cost",
    "Profit"
]

In [67]:
for col in float_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [68]:
df.dtypes

Booking_ID                         object
Customer_Name                      object
Booking_Date               datetime64[ns]
City                               object
Room_Type                          object
Booking_Channel                    object
Customer_Segment                   object
Gender                             object
Age                                 int64
Room_Nights                         int64
Room_Rate                         float64
Discount_%                        float64
Rating                            float64
Guests                            float64
Is_Member                           int64
Cancelled                           int64
Payment_Method                     object
Gross_Amount                      float64
Discount_Amount                   float64
Final_Amount                      float64
Hotel_Cost                        float64
Profit                            float64
Calculated_Final_Amount           float64
dtype: object

In [69]:
# 23. Handle missing values in key financial columns (Gross Amount, Discount Amount, Final
#Amount, Profit)
#Explanation: Some financial columns have blanks. Decide whether to drop those rows, fill
#with 0, or calculate missing values from other columns when possible.

df[["Gross_Amount", "Discount_Amount", "Final_Amount", "Profit"]].isna().sum()

Gross_Amount       0
Discount_Amount    0
Final_Amount       0
Profit             0
dtype: int64

In [70]:
# 24. Remove rows with completely invalid dates
#Explanation: Dates like 32/13/2025 are impossible. Identify and either remove those rows or
#set the date to missing.

df["Booking_Date"] = pd.to_datetime(
    df["Booking_Date"],
    errors="coerce"
)

In [71]:
df["Booking_Date"].isna().sum()

np.int64(0)

In [72]:
#25. Standardize boolean-like columns (Is Member and Cancelled) to the same format
#Explanation: Keeping both columns in the same style (both 0/1 or both Yes/No) makes
#filtering and analysis much easier and less error-prone.
df

Empty DataFrame
Columns: [Booking_ID, Customer_Name, Booking_Date, City, Room_Type, Booking_Channel, Customer_Segment, Gender, Age, Room_Nights, Room_Rate, Discount_%, Rating, Guests, Is_Member, Cancelled, Payment_Method, Gross_Amount, Discount_Amount, Final_Amount, Hotel_Cost, Profit, Calculated_Final_Amount]
Index: []

[0 rows x 23 columns]