In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Data_Train.xlsx - Sheet1.csv")
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [2]:
# 1. Load the Flight Price dataset into a Pandas DataFrame and display the first five rows.
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [3]:
# 2. Find the number of rows and columns in the dataset.
df.shape

(10683, 11)

In [4]:
# 3. Display all column names in the dataset.
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [5]:
# 4. Display the data types of all columns.
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [6]:
# 5. Use df.info() to inspect the structure of the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [7]:
# 6. Check the number of missing values in each column.
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [8]:
# 7. Check the percentage of missing values in each column.
miss_per = (df.isnull().sum() / len(df)) * 100
miss_per

Airline            0.000000
Date_of_Journey    0.000000
Source             0.000000
Destination        0.000000
Route              0.009361
Dep_Time           0.000000
Arrival_Time       0.000000
Duration           0.000000
Total_Stops        0.009361
Additional_Info    0.000000
Price              0.000000
dtype: float64

In [9]:
# 8. Display the unique values and frequency of each value in the Airline column.
df['Airline'].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [10]:
# 9. Display the frequency distribution of Total_Stops, including missing values.
df['Total_Stops'].value_counts(dropna=False)

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
NaN            1
4 stops        1
Name: count, dtype: int64

In [11]:
# 10.Convert Date_of_Journey into a datetime format.
df['Date_of_Journey']= pd.to_datetime(df['Date_of_Journey'], errors = "coerce")
df['Date_of_Journey']

C:\Users\bhoom\AppData\Local\Temp\ipykernel_32728\3341264625.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date_of_Journey']= pd.to_datetime(df['Date_of_Journey'], errors = "coerce")

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
           ...
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10683, dtype: datetime64[ns]

In [12]:
# 11.Extract the day from Date_of_Journey and create a day column.
df['day'] = df['Date_of_Journey'].dt.day
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1

In [13]:
# 13.Extract the year from Date_of_Journey and create a year column.

df['year'] = df['Date_of_Journey'].dt.year
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,year
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,2019
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,2019
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,2019
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,2019
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,2019

In [14]:
# 14.Drop the original Date_of_Journey column after extracting the required features.
df = df.drop(columns = "Date_of_Journey")
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,2019

In [15]:
# 15.Convert Dep_Time into datetime format and extract the departure hour into Dep_Hour.
df['Dep_Time']= pd.to_datetime(df['Dep_Time'], errors = "coerce")
df['Dep_Time']

C:\Users\bhoom\AppData\Local\Temp\ipykernel_32728\3655655017.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dep_Time']= pd.to_datetime(df['Dep_Time'], errors = "coerce")

0       2026-08-11 22:20:00
1       2026-08-11 05:50:00
2       2026-08-11 09:25:00
3       2026-08-11 18:05:00
4       2026-08-11 16:50:00
                ...
10678   2026-08-11 19:55:00
10679   2026-08-11 20:45:00
10680   2026-08-11 08:20:00
10681   2026-08-11 11:30:00
10682   2026-08-11 10:55:00
Name: Dep_Time, Length: 10683, dtype: datetime64[ns]

In [16]:
df['Dep_Hour'] = pd.to_datetime(df['Dep_Time']).dt.hour
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,year,Dep_Hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-08-11 22:20:00,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,2019,22
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-11 05:50:00,13:15,7h 25m,2 stops,No info,7662,1,2019,5
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-08-11 09:25:00,04:25 10 Jun,19h,2 stops,No info,13882,9,2019,9
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-11 18:05:00,23:30,5h 25m,1 stop,No info,6218,12,2019,18
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-11 16:50:00,21:35,4h 45m,1 stop,No info,13302,1,2019,16

In [17]:
# 16.Extract the departure minute from Dep_Time and create Dep_Minute.
df['Dep_Minute'] = pd.to_datetime(df['Dep_Time']).dt.minute
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,year,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-08-11 22:20:00,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-11 05:50:00,13:15,7h 25m,2 stops,No info,7662,1,2019,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-08-11 09:25:00,04:25 10 Jun,19h,2 stops,No info,13882,9,2019,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-11 18:05:00,23:30,5h 25m,1 stop,No info,6218,12,2019,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-11 16:50:00,21:35,4h 45m,1 stop,No info,13302,1,2019,16,50

In [18]:
# 17.Drop the original Dep_Time column after extracting the required features.
df = df.drop(columns = "Dep_Time")
df.head()

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,year,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,2019,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,2019,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,12,2019,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,1,2019,16,50

In [19]:
# # 18.Extract only the time portion from Arrival_Time.
# df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], errors = "coerce").dt.time
# df['Arrival_Time'].head()

In [20]:
# 19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.
df["Arrival_Time"] = pd.to_datetime(df['Arrival_Time'], dayfirst=True)

C:\Users\bhoom\AppData\Local\Temp\ipykernel_32728\2282661471.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Time"] = pd.to_datetime(df['Arrival_Time'], dayfirst=True)

In [21]:
# df['Arrival_Hour'] = df["arrival"].dt.hour
# df['Arrival_Minute'] = df["arrival"].dt.minute

# print(df[['Arrival_Time', 'Arrival_Hour', 'Arrival_Minute']].head())

In [22]:
df['time_portion'] = df['Arrival_Time'].dt.time

In [23]:
df['Arrival_Hour'] = df["Arrival_Time"].dt.hour
df['Arrival_Minute'] = df["Arrival_Time"].dt.minute
df

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,year,Dep_Hour,Dep_Minute,time_portion,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2026-03-22 01:10:00,2h 50m,non-stop,No info,3897,24,2019,22,20,01:10:00,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-08-11 13:15:00,7h 25m,2 stops,No info,7662,1,2019,5,50,13:15:00,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2026-06-10 04:25:00,19h,2 stops,No info,13882,9,2019,9,25,04:25:00,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2026-08-11 23:30:00,5h 25m,1 stop,No info,6218,12,2019,18,5,23:30:00,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2026-08-11 21:35:00,4h 45m,1 stop,No info,13302,1,2019,16,50,21:35:00,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2026-08-11 22:25:00,2h 30m,non-stop,No info,4107,9,2019,19,55,22:25:00,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,2026-08-11 23:20:00,2h 35m,non-stop,No info,4145,27,2019,20,45,23:20:00,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,2026-08-11 11:20:00,3h,non-stop,No info,7229,27,2019,8,20,11:20:00,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2026-08-11 14:10:00,2h 40m,non-stop,No info,12648,1,2019,11,30,14:10:00,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2026-08-11 19:15:00,8h 20m,2 stops,No info,11753,9,2019,10,55,19:15:00,19,15

In [24]:
# 20.Drop the original Arrival_Time column after extracting the required features.

df = df.drop(columns=['Arrival_Time'])

In [25]:
# 21.Extract the hour component from Duration and create Duration_Hour. Handle
# invalid or missing extracted values appropriately.

df['Duration_Hour'] = df['Duration'].str.split('h').str[0]
df['Duration_Hour'] = pd.to_numeric(df['Duration_Hour'], errors='coerce').fillna(0).astype(int)
df['Duration_Hour']

0         2
1         7
2        19
3         5
4         4
         ..
10678     2
10679     2
10680     3
10681     2
10682     8
Name: Duration_Hour, Length: 10683, dtype: int64

In [26]:
# 22.Extract the minute component from Duration and create Duration_Minute.
# Handle invalid or missing extracted values appropriately.

df['Duration_Minute'] = df['Duration'].str.split('m').str[0]
df['Duration_Minute'] = pd.to_numeric(df['Duration_Minute'], errors='coerce').fillna(0).astype(int)
df['Duration_Minute'].value_counts()

Duration_Minute
0    10682
5        1
Name: count, dtype: int64

In [27]:
# 23.Drop the original Duration column after creating the numerical duration features.

df = df.drop(columns=['Duration'])

In [28]:
# 24.Replace non-stop in Total_Stops with 0 stops.

df['Total_Stops'] = df['Total_Stops'].replace('non-stop', 0)

In [29]:
# 25.Extract only the numerical value from Total_Stops and convert the column into
# an integer data type. Handle missing or invalid values appropriately.

df['Total_Stops'] = pd.to_numeric(df['Total_Stops'], errors='coerce').fillna(0).astype(int)

In [30]:
# 26.Split the Route column using → as the separator and create Route_1,
# Route_2, Route_3, Route_4, and Route_5.

# df[['Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5']] = (df['Route'].str.split('→', expand=True))
# df[['Route', 'Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5']].head()

In [31]:
route_cols = df['Route'].str.split('→', expand=True)

for i in range(5):
    df[f'Route_{i+1}'] = route_cols[i] if i in route_cols.columns else None

In [32]:
# 27.Identify the missing values created in Route_3, Route_4, and Route_5 after splitting the route.

df[['Route_3', 'Route_4', 'Route_5']].isnull().sum()

Route_3     3492
Route_4     9117
Route_5    10637
dtype: int64

In [33]:
df[df[['Route_3', 'Route_4', 'Route_5']].isnull().any(axis=1)][
    ['Route', 'Route_3', 'Route_4', 'Route_5']]

                       Route Route_3 Route_4 Route_5
0                  BLR → DEL    None    None    None
1      CCU → IXR → BBI → BLR    BBI      BLR    None
2      DEL → LKO → BOM → COK    BOM      COK    None
3            CCU → NAG → BLR     BLR    None    None
4            BLR → NAG → DEL     DEL    None    None
...                      ...     ...     ...     ...
10678              CCU → BLR    None    None    None
10679              CCU → BLR    None    None    None
10680              BLR → DEL    None    None    None
10681              BLR → DEL    None    None    None
10682  DEL → GOI → BOM → COK    BOM      COK    None

[10637 rows x 4 columns]

In [34]:
df[['Route_3', 'Route_4', 'Route_5']].isnull().mean() * 100

Route_3    32.687447
Route_4    85.341196
Route_5    99.569409
dtype: float64

In [35]:
# 28.Replace the missing values in the route columns with an appropriate value such as None.

route_cols = ['Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5']
df[route_cols] = df[route_cols].fillna('None')

df[route_cols].head()

  Route_1 Route_2 Route_3 Route_4 Route_5
0    BLR      DEL    None    None    None
1    CCU     IXR     BBI      BLR    None
2    DEL     LKO     BOM      COK    None
3    CCU     NAG      BLR    None    None
4    BLR     NAG      DEL    None    None

In [36]:
df[route_cols].isnull().sum()

Route_1    0
Route_2    0
Route_3    0
Route_4    0
Route_5    0
dtype: int64

In [37]:
# 29.Drop the original Route column after creating and cleaning the route features.

df.drop('Route', axis=1, inplace=True)
df.columns

Index(['Airline', 'Source', 'Destination', 'Total_Stops', 'Additional_Info',
       'Price', 'day', 'year', 'Dep_Hour', 'Dep_Minute', 'time_portion',
       'Arrival_Hour', 'Arrival_Minute', 'Duration_Hour', 'Duration_Minute',
       'Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5'],
      dtype='object')

In [38]:
# 30.After completing all data cleaning and feature engineering, separate the
# dataset into X (independent variables) and y (target variable), where Price is the target.

X = df.drop(columns=['Price'])

y = df['Price']

X.shape

(10683, 19)

In [39]:
y.shape

(10683,)

In [41]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,day,year,Dep_Hour,Dep_Minute,time_portion,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute,Route_1,Route_2,Route_3,Route_4,Route_5
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,2019,22,20,01:10:00,1,10,2,0,BLR,DEL,None,None,None
1,Air India,Kolkata,Banglore,0,No info,7662,1,2019,5,50,13:15:00,13,15,7,0,CCU,IXR,BBI,BLR,None
2,Jet Airways,Delhi,Cochin,0,No info,13882,9,2019,9,25,04:25:00,4,25,19,0,DEL,LKO,BOM,COK,None
3,IndiGo,Kolkata,Banglore,0,No info,6218,12,2019,18,5,23:30:00,23,30,5,0,CCU,NAG,BLR,None,None
4,IndiGo,Banglore,New Delhi,0,No info,13302,1,2019,16,50,21:35:00,21,35,4,0,BLR,NAG,DEL,None,None