In [176]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\messy_customer_loan_dataset.csv")
df

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40.0,477723.0,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No
1531,CUST101295,65.0,1394481.0,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1533,CUST101460,45.0,543340.0,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

In [177]:
# 1. Load the CSV file using Pandas and display the first 10 rows.

df.head(10)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
5,CUST100925,32.0,317590.0,690.0,Salaried,Graduate,M,Mumbai,Premium,Auto,235549.0,120,5.0,0.46,No
6,CUST100758,39.0,322966.0,707.0,Contract,Graduate,Married,Chennai,Mass,Personal,563319.0,24,7.0,0.323,No
7,CUST100793,54.0,999108.0,689.0,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783.0,48,NaN,0.233,Yes
8,CUST100965,65.0,478191.0,758.0,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872.0,72,5.0,0.375,No
9,CUST101198,67.0,1063307.0,774.0,SALARIED,Graduate,Married,Jaipur,Affluent,Home,549693.0,120,2.0,0.394,Yes

In [178]:
# 2. Display the number of rows and columns in the dataset.

df.shape

(1535, 15)

In [179]:
# 3. Display all column names and identify which column names have
# leading/trailing spaces.

for i in df.columns:
    print(i)

 Customer ID
Age
Annual Income
credit Score
Employment-Type
Education  Level
marital_status
city
customer_segment
loan_type
Loan Amount (INR)
tenure Months
Monthly Visits
debt_to_income
Loan Approved?

In [180]:
# 4. Clean all column names by removing extra spaces and converting them into a
# consistent format such as snake_case.

df.columns = df.columns.str.replace(' ','_')
for i in df.columns:
    print(i)

_Customer_ID_
Age_
Annual_Income
credit_Score_
Employment-Type
Education__Level
marital_status
city
customer_segment_
loan_type
Loan_Amount_(INR)
tenure_Months
Monthly_Visits_
debt_to_income
Loan_Approved?

In [181]:
# 5. Check the data type of every column.

df.dtypes

_Customer_ID_        object
Age_                 object
Annual_Income        object
credit_Score_        object
Employment-Type      object
Education__Level     object
marital_status       object
city                 object
customer_segment_    object
loan_type            object
Loan_Amount_(INR)    object
tenure_Months         int64
Monthly_Visits_      object
debt_to_income       object
Loan_Approved?       object
dtype: object

In [182]:
# 6. Find the total number of missing values in each column.

df.isna().sum()

_Customer_ID_          0
Age_                  71
Annual_Income         84
credit_Score_         77
Employment-Type       60
Education__Level      46
marital_status         0
city                  52
customer_segment_      0
loan_type              0
Loan_Amount_(INR)    102
tenure_Months          0
Monthly_Visits_       55
debt_to_income        89
Loan_Approved?         0
dtype: int64

In [183]:
# 7. Find the percentage of missing values in each column.

(df.isna().sum()/1535)*100

_Customer_ID_        0.000000
Age_                 4.625407
Annual_Income        5.472313
credit_Score_        5.016287
Employment-Type      3.908795
Education__Level     2.996743
marital_status       0.000000
city                 3.387622
customer_segment_    0.000000
loan_type            0.000000
Loan_Amount_(INR)    6.644951
tenure_Months        0.000000
Monthly_Visits_      3.583062
debt_to_income       5.798046
Loan_Approved?       0.000000
dtype: float64

In [184]:
# 8. Find all rows where Age is missing.

df[df['Age_'].isna()]

,_Customer_ID_,Age_,Annual_Income,credit_Score_,Employment-Type,Education__Level,marital_status,city,customer_segment_,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits_,debt_to_income,Loan_Approved?
21,CUST100354,NaN,302606.0,726.0,NaN,Graduate,Single,Bengaluru,Mass,Auto,269320.0,84,6.0,0.353,No
29,CUST100989,NaN,650000 INR,778.0,Self-Employed,Graduate,Divorced,Pune,unknown,Home,1083921.0,48,5.0,0.4x,No
100,CUST101150,NaN,100,723.0,Self-Employed,12th,Married,NaN,Mass,Education,454937.0,48,five,0.303,Yes
108,CUST100535,NaN,458878.0,782.0,Salaried,Diploma,Married,Mumbai,Mass,Auto,549385.0,36,7.0,0.279,No
113,CUST101055,NaN,1112464.0,120,Salaried,Diploma,Married,Kolkata,Mass,Auto,427759.0,84,3.0,0.102,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,CUST100392,NaN,570532.0,766.0,Contract,Postgraduate,Married,Jaipur,Mass,Home,937612.0,36,3.0,0.51,Yes
1430,CUST101368,NaN,519228.0,728.0,Business,Postgraduate,Married,Hyderabad,Mass,Home,514679.0,12,4.0,0.392,Yes
1498,CUST100700,NaN,658802.0,772.0,Contract,Postgraduate,Married,Mumbai,Mass,Auto,257699.0,24,4.0,0.584,Yes
1503,CUST100748,NaN,338339.0,673.0,Business,Graduate,Married,Chennai,Premium,Business,223704.0,12,7.0,0.02,No
1516,CUST100770,NaN,708229.0,801.0,Business,NaN,Single,Chennai,Premium,Personal,341664.0,120,5.0,0.651,Yes

In [185]:
# 9. Find all rows where Annual Income is missing.

df[df['Annual_Income'].isna()]

,_Customer_ID_,Age_,Annual_Income,credit_Score_,Employment-Type,Education__Level,marital_status,city,customer_segment_,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits_,debt_to_income,Loan_Approved?
41,CUST101081,64.0,NaN,749.0,Self-Employed,Diploma,Single,Kolkata,Premium,Personal,254754.0,24,5.0,0.327,No
103,CUST101403,35.0,NaN,660.0,Self-Employed,Graduate,Married,Delhi,Affluent,Home,NaN,36,4.0,0.402,No
119,CUST101095,36.0,NaN,782.0,self-employed,Postgraduate,Married,Bengaluru,Affluent,Home,225725.0,60,5.0,0.341,Yes
132,CUST101048,49.0,NaN,713.0,Salaried,Postgraduate,Single,Bengaluru,Affluent,auto,301697.0,48,7.0,0.35,Yes
144,CUST100530,64.0,NaN,761.0,Business,Diploma,Single,NaN,Affluent,Business,1182185.0,120,7.0,0.02,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,CUST100776,65.0,NaN,667.0,Self-Employed,GRADUATE,Single,Mumbai,Mass,Personal,995167.0,72,3.0,0.6,Yes
1493,CUST101496,41.0,NaN,662.0,Self-Employed,12th,Single,Kolkata,Affluent,Education,693422.0,48,5.0,0.272,No
1501,CUST100475,50.0,NaN,802.0,Contract,12th,Divorced,Kolkata,Mass,Personal,1488587.0,36,5.0,0.023,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

In [186]:
# 10.Remove completely duplicate rows and report how many duplicate rows were removed.

df[df.duplicated()]

,_Customer_ID_,Age_,Annual_Income,credit_Score_,Employment-Type,Education__Level,marital_status,city,customer_segment_,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits_,debt_to_income,Loan_Approved?
76,CUST100793,54.0,999108.0,689.0,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783.0,48,NaN,0.233,Yes
126,CUST100276,43.0,769913.0,852.0,Salaried,Diploma,Married,Bengaluru,Affluent,Home,363928.0,120,10.0,0.291,No
356,CUST100965,65.0,478191.0,758.0,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872.0,72,5.0,0.375,No
375,CUST101226,66.0,273582.0,695.0,Business,Postgraduate,Single,Pune,SME,Education,262325.0,24,5.0,0.388,No
449,CUST101409,21.0,796057.0,791.0,Contract,Graduate,Single,Hyderabad,Affluent,Auto,345847.0,48,4.0,0.158,Yes
577,CUST101182,64.0,1087024.0,766.0,Contract,12th,Married,Bengaluru,SME,Home,763336.0,12,3.0,0.422,Yes
671,CUST100506,42.0,835866.0,692.0,Contract,Graduate,Single,Hyderabad,Affluent,Business,NaN,24,2.0,0.552,Yes
682,CUST100156,52.0,253877.0,564.0,Contract,Postgraduate,Married,Hyderabad,Affluent,Home,421927.0,84,8.0,0.124,No
704,CUST100121,41.0,1621977.0,807.0,Salaried,Graduate,Single,Mumbai,Mass,Home,290934.0,72,6.0,0.081,Yes
729,CUST100731,55.0,555968.0,642.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Business,525357.0,60,2.0,0.38,No
800,CUST101125,60.0,346551.0,624.0,Business,Graduate,Married,Chennai,Mass,Personal,414208.0,24,5.0,0.2,yes
846,CUST100119,32.0,1570137.0,NaN,Self-Employed,Graduate,unknown,Chennai,Affluent,Auto,450226.0,48,3.0,0.529,Yes
847,CUST101335,46.0,775005.0,772.0,Contract,Postgraduate,Single,Bengaluru,Mass,Home,204197.0,60,9.0,0.238,Yes
850,CUST100880,50.0,389369.0,752.0,Contract,12th,Married,Bengaluru,Affluent,Personal,212916.0,48,4.0,0.135,Yes
868,CUST100502,51.0,1207664.0,795.0,Contract,Postgraduate,Married,Chennai,Premium,Home,1785635.0,84,4.0,0.501,No
882,CUST100103,58.0,372104.0,786.0,self-employed,Graduate,Divorced,Pune,Affluent,Home,154218.0,60,4.0,0.458,Yes
902,CUST101165,45.0,247939.0,710.0,Salaried,Post Graduate,Single,Chennai,Mass,Business,540042.0,48,80,0.638,Yes
1081,CUST101297,33.0,641297.0,743.0,NaN,Graduate,Married,Jaipur,Mass,Auto,691511.0,24,2.0,0.082,Yes
1119,CUST100869,41.0,405117.0,725.0,Contract,Postgraduate,Single,Kolkata,SME,Home,255203.0,72,4.0,0.454,No
1139,CUST100608,45.0,303172.0,834.0,Self-Employed,Postgraduate,Single,Mumbai,Mass,Home,NaN,36,five,0.308,Yes
1152,CUST101294,NaN,646827.0,782.0,Business,Other,Single,Mumbai,Affluent,Personal,324249.0,120,10.0,0.349,0
1176,CUST100471,55.0,1355907.0,636.0,Business,Graduate,Single,Kolkata,Premium,Home,156009.0,72,4.0,0.366,Yes
1179,CUST100400,35.0,₹720000,818.0,Self-Employed,12th,Married,Hyderabad,Mass,Home,869924.0,72,2.0,0.357,No
1206,CUST100583,26.0,872901.0,769.0,Self-Employed,12th,Married,Pune,Mass,Business,916271.0,60,4.0,0.292,Yes
1209,CUST100986,NaN,1620302.0,694.0,Business,Postgraduate,Single,Delhi,Affluent,Business,183992.0,12,7.0,0.171,No
1212,CUST100993,30.0,884169.0,759.0,Self-Employed,Postgraduate,Single,Kolkata,Mass,Business,608754.0,12,2.0,0.411,No
1229,CUST100644,43.0,983121.0,905.0,Contract,Graduate,Single,Jaipur,Mass,Personal,463446.0,120,4.0,0.177,Yes
1249,CUST101145,36.0,747039.0,745.0,Salaried,Graduate,Single,Jaipur,Mass,Auto,1127779.0,24,3.0,0.629,Yes
1269,CUST101136,23.0,466307.0,547.0,Business,Postgraduate,Married,Jaipur,Affluent,Education,123020.0,36,3.0,0.317,Yes
1301,CUST100166,59.0,NaN,677.0,Self-Employed,Graduate,Married,Chennai,Mass,Business,316551.0,48,6.0,0.45,Yes
1365,CUST101255,51.0,341587.0,634.0,Business,Graduate,Single,Mumbai,Mass,Education,483070.0,24,6.0,0.435,No
1449,CUST100456,47.0,301531.0,738.0,Salaried,Graduate,Single,Pune,Mass,Business,695043.0,48,7.0,0.385,No
1450,CUST100243,25.0,401757.0,705.0,Salaried,Diploma,Divorced,Bengaluru,Affluent,Home,246699.0,24,2.0,0.451,Yes
1471,CUST100114,42.0,541674.0,713.0,Self-Employed,NaN,Divorced,Pune,Mass,Business,273522.0,12,4.0,0.489,Yes
1506,CUST101338,34.0,272618.0,740.0,Business,Graduate,Married,Bengaluru,Premium,Personal,200194.0,48,NaN,0.564,0

In [187]:
df=df.drop_duplicates()
df

,_Customer_ID_,Age_,Annual_Income,credit_Score_,Employment-Type,Education__Level,marital_status,city,customer_segment_,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits_,debt_to_income,Loan_Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40.0,477723.0,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No
1531,CUST101295,65.0,1394481.0,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1533,CUST101460,45.0,543340.0,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

In [188]:
# 11.The Age column contains numbers as well as values like "unknown" and
# "twenty five". Clean this column and convert it into a proper numeric column.

df['Age_'].unique()

array(['37.0', '36.0', '55.0', '54.0', '27.0', '32.0', '39.0', '65.0',
       '67.0', '45.0', '52.0', '21.0', '60.0', '34.0', '42.0', '57.0',
       '26.0', nan, '61.0', '58.0', 'twenty five', '38.0', '64.0', '43.0',
       '49.0', '66.0', '29.0', '53.0', '48.0', '35.0', '23.0', '30.0',
       '63.0', '56.0', '22.0', '47.0', '25.0', '62.0', '41.0', '24.0',
       '40.0', '51.0', '59.0', '50.0', 'unknown', '33.0', '31.0', '46.0',
       '44.0', '105', '5', '28.0', ' 42 ', '12', '-3', '130'],
      dtype=object)

In [189]:
for i in df["Age_"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

twenty five
unknown

In [190]:
df=df.replace({'Age_':{"twenty five":25,
                       "unknown":np.nan,
                      -3:3}})
df['Age_'].unique()

array(['37.0', '36.0', '55.0', '54.0', '27.0', '32.0', '39.0', '65.0',
       '67.0', '45.0', '52.0', '21.0', '60.0', '34.0', '42.0', '57.0',
       '26.0', nan, '61.0', '58.0', 25, '38.0', '64.0', '43.0', '49.0',
       '66.0', '29.0', '53.0', '48.0', '35.0', '23.0', '30.0', '63.0',
       '56.0', '22.0', '47.0', '25.0', '62.0', '41.0', '24.0', '40.0',
       '51.0', '59.0', '50.0', '33.0', '31.0', '46.0', '44.0', '105', '5',
       '28.0', ' 42 ', '12', '-3', '130'], dtype=object)

In [191]:
df['Age_'] = pd.to_numeric(df['Age_'], errors='coerce')
df['Age_'].unique()

array([ 37.,  36.,  55.,  54.,  27.,  32.,  39.,  65.,  67.,  45.,  52.,
        21.,  60.,  34.,  42.,  57.,  26.,  nan,  61.,  58.,  25.,  38.,
        64.,  43.,  49.,  66.,  29.,  53.,  48.,  35.,  23.,  30.,  63.,
        56.,  22.,  47.,  62.,  41.,  24.,  40.,  51.,  59.,  50.,  33.,
        31.,  46.,  44., 105.,   5.,  28.,  12.,  -3., 130.])

In [192]:
# 12.The Annual Income column contains values such as 650000 INR, ₹720000,
# 1.2L, and N/A. Clean the column and convert the valid values into numeric
# format.

for i in df["Annual_Income"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

650000 INR
unknown
1.2L
₹720000

In [193]:
df=df.replace({"Annual_Income":{"650000 INR":650000,
                                "unknown":np.nan,
                                "1.2L":120000,
                                "₹720000":720000}})
df['Age_'].unique()

array([ 37.,  36.,  55.,  54.,  27.,  32.,  39.,  65.,  67.,  45.,  52.,
        21.,  60.,  34.,  42.,  57.,  26.,  nan,  61.,  58.,  25.,  38.,
        64.,  43.,  49.,  66.,  29.,  53.,  48.,  35.,  23.,  30.,  63.,
        56.,  22.,  47.,  62.,  41.,  24.,  40.,  51.,  59.,  50.,  33.,
        31.,  46.,  44., 105.,   5.,  28.,  12.,  -3., 130.])

In [194]:
# 13.Clean the Credit Score column and identify values that cannot be converted
# into numbers.

for i in df["credit_Score_"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

unknown
seven hundred
720 points

In [195]:
df=df.replace({"credit_Score_":{"unknown":np.nan,
                                "seven hundred":700,
                                "720 points":750}})
df['credit_Score_'].unique()

array(['698.0', '874.0', '661.0', '722.0', '727.0', '690.0', '707.0',
       '689.0', '758.0', '774.0', '759.0', '662.0', '849.0', '752.0',
       '740.0', '720.0', '651.0', '687.0', '637.0', '681.0', '726.0',
       '765.0', nan, '731.0', '743.0', '701.0', '673.0', '749.0', '778.0',
       '807.0', '815.0', '757.0', '667.0', '751.0', '783.0', '679.0',
       '812.0', '723.0', '653.0', '644.0', '710.0', '660.0', '592.0',
       '650.0', '779.0', '712.0', '818.0', '547.0', '817.0', '647.0',
       '852.0', '785.0', '603.0', '666.0', '773.0', '692.0', '635.0',
       '623.0', '694.0', '745.0', '741.0', '678.0', '782.0', '704.0',
       '803.0', '834.0', '856.0', '797.0', '579.0', '835.0', '827.0',
       '600.0', '703.0', '724.0', '705.0', '838.0', '905.0', '813.0',
       '734.0', '796.0', '596.0', '791.0', '670.0', '719.0', '780.0',
       '787.0', '775.0', '120', '744.0', '738.0', '665.0', '699.0', '999',
       '715.0', '776.0', '728.0', '713.0', '659.0', '769.0', '700.0',
       '766.0', '762.0', '630.0', '624.0', '711.0', '761.0', '664.0',
       '695.0', '654.0', '684.0', '657.0', '545.0', '842.0', '643.0',
       '649.0', '721.0', '770.0', '688.0', '639.0', '793.0', '754.0',
       '636.0', '854.0', '781.0', '832.0', '806.0', '682.0', '658.0',
       '628.0', '840.0', '808.0', 700, '804.0', '640.0', '732.0', '777.0',
       '671.0', '737.0', '663.0', '708.0', '725.0', '843.0', '755.0',
       '706.0', '750.0', '683.0', '709.0', '631.0', '652.0', '609.0',
       '696.0', '669.0', '763.0', '789.0', '799.0', '729.0', '753.0',
       '668.0', '790.0', '718.0', '788.0', '655.0', '601.0', '819.0',
       '714.0', '638.0', '250', '0', '747.0', '795.0', '686.0', '634.0',
       '615.0', '739.0', '619.0', '786.0', '746.0', '646.0', '802.0',
       '794.0', '672.0', '648.0', '685.0', '576.0', '674.0', '837.0',
       '858.0', '617.0', '889.0', '772.0', '717.0', '621.0', '568.0',
       '642.0', '691.0', '625.0', '575.0', '564.0', '863.0', '735.0',
       '716.0', '733.0', '641.0', '736.0', '676.0', '767.0', '656.0', 750,
       '809.0', '633.0', '771.0', '590.0', '756.0', '828.0', '680.0',
       '571.0', '629.0', '821.0', '764.0', '730.0', '697.0', '632.0',
       '675.0', '612.0', '831.0', '605.0', '586.0', '597.0', '748.0',
       '607.0', '618.0', '693.0', '620.0', '824.0', '598.0', '792.0',
       '805.0', '760.0', '860.0', '589.0', '677.0', '585.0', '702.0',
       '577.0', '525.0', '584.0', '616.0', '742.0', '903.0', '800.0',
       '784.0', '836.0', '801.0', '768.0', '595.0', '559.0', '588.0',
       '816.0', '645.0', '544.0', '627.0', '870.0', '872.0', '829.0',
       '878.0', '608.0', '593.0', '626.0', '867.0', '868.0', '613.0',
       '583.0', '844.0', '841.0', '811.0', '865.0', '814.0', '538.0',
       '614.0', '822.0', '861.0', '887.0', '622.0', '602.0', '876.0',
       '820.0', '851.0', '823.0', '825.0', '810.0', '582.0', '798.0',
       '846.0', '606.0', '611.0'], dtype=object)

In [196]:
# 14.The Loan Amount column contains currency symbols, text, and numeric
# values. Remove the unwanted characters and convert it into numeric format.

df["Loan_Amount_(INR)"].unique()

array(['378342.0', '751792.0', '892792.0', ..., '222828.0', '302389.0',
       '753995.0'], shape=(1367,), dtype=object)

In [197]:
for i in df["Loan_Amount_(INR)"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

450000 INR
₹5,00,000
pending

In [198]:
df=df.replace({"Loan_Amount_(INR)":{"450000 INR":450000,
                                    "₹5,00,000":500000,
                                    "pending":np.nan}})

In [199]:
for i in df["Loan_Amount_(INR)"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

In [200]:
# 15.The Monthly Visits column contains values such as "five", "N/A", and "-".
# Convert valid values into numeric values and handle invalid values.

for i in df["Monthly_Visits_"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

unknown
five
-

In [201]:
df=df.replace({"Monthly_Visits_":{"unknown":np.nan,
                                    "five":5,
                                    "-":np.nan}})

In [202]:
for i in df["Monthly_Visits_"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

In [203]:
# 16.Clean the Debt to Income column where some values are written like 35%
# and 0.4x. Convert the valid values into a consistent numeric format.

for i in df["debt_to_income"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

0.4x
35%
unknown

In [204]:
df=df.replace({"debt_to_income":{"unknown":np.nan,
                                    "0.4x":0.40,
                                    "35%":0.35}})

In [205]:
for i in df["debt_to_income"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

In [206]:
# 17.After cleaning the numerical columns, check which columns are still stored as
# object data type.

df.dtypes.value_counts()

object     13
float64     1
int64       1
Name: count, dtype: int64

In [207]:
# 18.Find all unique values in the Employment-Type column.

df['Employment-Type'].unique()

array(['Self-Employed', 'Contract', 'Salaried', ' SALARIED ',
       'Self employed', 'Business', nan, 'Unknown', 'self-employed',
       'salaried'], dtype=object)

In [208]:
# 19.Standardize the Employment-Type column so that values such as salaried,
# SALARIED, and Salaried become one consistent value.

df=df.replace({"Employment-Type":{"Self-employed":"Self-Employed",
                                  "Self employed":"Self-Employed",
                                  "self-employed":"Self-Employed",
                                  "salaried":"Salaried",
                                  " SALARIED ":"Salaried",
                                 "Unknown":np.nan}})

In [209]:
df['Employment-Type'].unique()

array(['Self-Employed', 'Contract', 'Salaried', 'Business', nan],
      dtype=object)

In [210]:
# 20.Clean the Education Level column and make values such as graduate,
# GRADUATE, and Graduate consistent.

df['Education__Level'].unique()

array(['12th', 'Graduate', 'Postgraduate', 'Diploma', nan,
       'Post Graduate', 'Other', ' GRADUATE', 'postgraduate ', 'graduate'],
      dtype=object)

In [211]:
df=df.replace({"Education__Level":{"Post Graduate":"Postgraduate",
                                   " GRADUATE":"Graduate",
                                   "graduate":"Graduate",
                                   "postgraduate ":"Postgraduate"}})

In [212]:
df['Education__Level'].value_counts()

Education__Level
Graduate        649
Postgraduate    378
12th            207
Diploma         156
Other            65
Name: count, dtype: int64

In [213]:
# 21.Clean the City column. Identify incorrect or inconsistent values such as
# hyderbad, Hyd, Bangalore, and Bengaluru.

df.columns

Index(['_Customer_ID_', 'Age_', 'Annual_Income', 'credit_Score_',
       'Employment-Type', 'Education__Level', 'marital_status', 'city',
       'customer_segment_', 'loan_type', 'Loan_Amount_(INR)', 'tenure_Months',
       'Monthly_Visits_', 'debt_to_income', 'Loan_Approved?'],
      dtype='object')

In [214]:
df['city'].unique()

array(['Mumbai', 'Jaipur', 'Kolkata', 'Hyderabad', 'Chennai', 'Bengaluru',
       nan, 'Delhi', 'Pune', 'MUMBAI', 'Hyd', 'mumbai ', 'Bangalore',
       ' Bengaluru ', 'hyderbad'], dtype=object)

In [215]:
df=df.replace({"city":{"MUMBAI":"Mumbai",
                       "mumbai ":"Mumbai",
                       " Bengaluru ":"Bangalore",
                       "Bengaluru":"Bangalore",
                       "hyderbad":"Hyderabad",
                      "Hyd":"Hyderabad"}})

In [216]:
df['city'].value_counts()

city
Jaipur       195
Hyderabad    187
Mumbai       186
Bangalore    185
Delhi        179
Chennai      178
Pune         171
Kolkata      167
Name: count, dtype: int64

In [217]:
# 22.Find all unique values in the Customer Segment column and identify invalid
# categories.

df['customer_segment_'].unique()

array(['Mass', ' PREMIUM', 'Affluent', 'Premium', 'SME', 'premium ',
       'unknown', 'High Value', 'mass'], dtype=object)

In [218]:
df=df.replace({"customer_segment_":{" PREMIUM":"Premium",
                                    "premium ":"Premium",
                                    "unknown":np.nan,
                                    "mass":"Mass"}})

In [219]:
df['customer_segment_'].value_counts()

customer_segment_
Mass          658
Affluent      455
Premium       262
SME           107
High Value      9
Name: count, dtype: int64

In [220]:
# 23.Clean the Loan Type column so that values such as personal, PERSONAL,
# and personal loan are standardized.

df['loan_type'].unique()

array(['Education', 'Auto', 'Home', 'Personal', 'Business',
       'personal loan', 'Home Loan', 'PERSONAL', 'auto ', 'Unknown'],
      dtype=object)

In [221]:
df=df.replace({"loan_type":{"auto ":"Auto",
                            "Unknown":np.nan,
                            "PERSONAL":"Personal",
                            "Home Loan":"Home",
                           "personal loan":"Personal"}})

In [222]:
df['loan_type'].value_counts()

loan_type
Auto         309
Personal     309
Education    299
Home         299
Business     271
Name: count, dtype: int64

In [223]:
# 24.Clean the Loan Approved column where values include Yes, yes, Y, 1, No,
# NO, N, and 0. Convert them into only Yes/No.

df['Loan_Approved?'].unique()

array(['No', 'Yes', '0', 'yes', 'N', 'pending', '1', 'approved', 'NO',
       'Y'], dtype=object)

In [224]:
df=df.replace({"Loan_Approved?":{"0":"No",
                                 "1":"Yes",
                                 "approved":"Yes",
                                 "NO":"No",
                                 "Y":"Yes",
                                 "N":"No",
                                 "pending":"No",
                                 "yes":"Yes"
                                }})

In [225]:
df['Loan_Approved?'].value_counts()

Loan_Approved?
Yes    1015
No      485
Name: count, dtype: int64

In [226]:
# 25.Check the Age column and identify unrealistic ages such as negative ages or
# ages above 100.

df['Age_'].value_counts()

Age_
 57.0     44
 42.0     44
 25.0     41
 60.0     39
 64.0     39
 41.0     38
 66.0     38
 35.0     37
 27.0     36
 44.0     36
 40.0     35
 26.0     35
 58.0     35
 50.0     34
 52.0     33
 46.0     33
 55.0     33
 67.0     31
 45.0     31
 32.0     31
 28.0     30
 61.0     30
 23.0     29
 49.0     29
 21.0     29
 34.0     29
 38.0     28
 47.0     28
 36.0     27
 54.0     27
 22.0     27
 43.0     26
 56.0     26
 29.0     26
 33.0     25
 24.0     25
 53.0     25
 48.0     25
 65.0     24
 63.0     23
 51.0     23
 62.0     23
 39.0     22
 30.0     22
 59.0     21
 31.0     19
 37.0     17
 105.0     6
-3.0       5
 5.0       3
 12.0      3
 130.0     1
Name: count, dtype: int64

In [227]:
# 26.Check the Credit Score column and identify values outside the valid credit-
# score range.

df['credit_Score_'].unique()

array(['698.0', '874.0', '661.0', '722.0', '727.0', '690.0', '707.0',
       '689.0', '758.0', '774.0', '759.0', '662.0', '849.0', '752.0',
       '740.0', '720.0', '651.0', '687.0', '637.0', '681.0', '726.0',
       '765.0', nan, '731.0', '743.0', '701.0', '673.0', '749.0', '778.0',
       '807.0', '815.0', '757.0', '667.0', '751.0', '783.0', '679.0',
       '812.0', '723.0', '653.0', '644.0', '710.0', '660.0', '592.0',
       '650.0', '779.0', '712.0', '818.0', '547.0', '817.0', '647.0',
       '852.0', '785.0', '603.0', '666.0', '773.0', '692.0', '635.0',
       '623.0', '694.0', '745.0', '741.0', '678.0', '782.0', '704.0',
       '803.0', '834.0', '856.0', '797.0', '579.0', '835.0', '827.0',
       '600.0', '703.0', '724.0', '705.0', '838.0', '905.0', '813.0',
       '734.0', '796.0', '596.0', '791.0', '670.0', '719.0', '780.0',
       '787.0', '775.0', '120', '744.0', '738.0', '665.0', '699.0', '999',
       '715.0', '776.0', '728.0', '713.0', '659.0', '769.0', '700.0',
       '766.0', '762.0', '630.0', '624.0', '711.0', '761.0', '664.0',
       '695.0', '654.0', '684.0', '657.0', '545.0', '842.0', '643.0',
       '649.0', '721.0', '770.0', '688.0', '639.0', '793.0', '754.0',
       '636.0', '854.0', '781.0', '832.0', '806.0', '682.0', '658.0',
       '628.0', '840.0', '808.0', 700, '804.0', '640.0', '732.0', '777.0',
       '671.0', '737.0', '663.0', '708.0', '725.0', '843.0', '755.0',
       '706.0', '750.0', '683.0', '709.0', '631.0', '652.0', '609.0',
       '696.0', '669.0', '763.0', '789.0', '799.0', '729.0', '753.0',
       '668.0', '790.0', '718.0', '788.0', '655.0', '601.0', '819.0',
       '714.0', '638.0', '250', '0', '747.0', '795.0', '686.0', '634.0',
       '615.0', '739.0', '619.0', '786.0', '746.0', '646.0', '802.0',
       '794.0', '672.0', '648.0', '685.0', '576.0', '674.0', '837.0',
       '858.0', '617.0', '889.0', '772.0', '717.0', '621.0', '568.0',
       '642.0', '691.0', '625.0', '575.0', '564.0', '863.0', '735.0',
       '716.0', '733.0', '641.0', '736.0', '676.0', '767.0', '656.0', 750,
       '809.0', '633.0', '771.0', '590.0', '756.0', '828.0', '680.0',
       '571.0', '629.0', '821.0', '764.0', '730.0', '697.0', '632.0',
       '675.0', '612.0', '831.0', '605.0', '586.0', '597.0', '748.0',
       '607.0', '618.0', '693.0', '620.0', '824.0', '598.0', '792.0',
       '805.0', '760.0', '860.0', '589.0', '677.0', '585.0', '702.0',
       '577.0', '525.0', '584.0', '616.0', '742.0', '903.0', '800.0',
       '784.0', '836.0', '801.0', '768.0', '595.0', '559.0', '588.0',
       '816.0', '645.0', '544.0', '627.0', '870.0', '872.0', '829.0',
       '878.0', '608.0', '593.0', '626.0', '867.0', '868.0', '613.0',
       '583.0', '844.0', '841.0', '811.0', '865.0', '814.0', '538.0',
       '614.0', '822.0', '861.0', '887.0', '622.0', '602.0', '876.0',
       '820.0', '851.0', '823.0', '825.0', '810.0', '582.0', '798.0',
       '846.0', '606.0', '611.0'], dtype=object)

In [228]:
# 27.Detect outliers in Annual Income using the IQR method.

df["Annual_Income"]=pd.to_numeric(df["Annual_Income"],errors = "coerce")

In [229]:
Q1 = df['Annual_Income'].quantile(0.25)
Q3 = df['Annual_Income'].quantile(0.75)

In [230]:
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Annual_Income'] < lower) | (df['Annual_Income'] > upper)]

outliers

,_Customer_ID_,Age_,Annual_Income,credit_Score_,Employment-Type,Education__Level,marital_status,city,customer_segment_,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits_,debt_to_income,Loan_Approved?
14,CUST101158,60.0,1548824.0,698.0,Contract,Graduate,Married,Pune,SME,Home,333121.0,24,10.0,0.529,No
61,CUST100757,55.0,1777657.0,666.0,Contract,Postgraduate,Single,Hyderabad,Premium,Education,900253.0,72,3.0,0.304,Yes
74,CUST100238,41.0,1907548.0,678.0,Business,Graduate,Single,Mumbai,Mass,Business,242378.0,72,0,NaN,Yes
180,CUST100421,64.0,1483255.0,751.0,Contract,Postgraduate,Married,Hyderabad,Mass,Auto,2033263.0,72,3.0,0.134,Yes
184,CUST100692,NaN,1895511.0,832.0,Self-Employed,Graduate,Married,Jaipur,SME,Personal,518143.0,48,2.0,0.637,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1409,CUST100407,41.0,1521141.0,799.0,Self-Employed,Graduate,Single,Kolkata,Affluent,Auto,573489.0,120,2.0,0.078,Yes
1464,CUST101412,47.0,1996474.0,789.0,Contract,Postgraduate,Married,Kolkata,High Value,Personal,460487.0,72,4.0,0.157,Yes
1466,CUST100206,33.0,1604257.0,785.0,Contract,12th,Single,Mumbai,Affluent,Business,NaN,24,3.0,0.355,No
1467,CUST100035,62.0,1531271.0,779.0,Business,Postgraduate,Single,Hyderabad,Mass,Personal,327941.0,24,4.0,0.179,Yes
1515,CUST100344,45.0,80000000.0,819.0,Self-Employed,Postgraduate,Single,Mumbai,Mass,Personal,636933.0,12,6.0,0.384,Yes

In [231]:
# 28.Detect outliers in Loan Amount using the IQR method.

df["Loan_Amount_(INR)"]=pd.to_numeric(df["Loan_Amount_(INR)"],errors = "coerce")

In [232]:
Q1 = df['Loan_Amount_(INR)'].quantile(0.25)
Q3 = df['Loan_Amount_(INR)'].quantile(0.75)

In [233]:
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Loan_Amount_(INR)'] < lower) | (df['Loan_Amount_(INR)'] > upper)]

outliers

,_Customer_ID_,Age_,Annual_Income,credit_Score_,Employment-Type,Education__Level,marital_status,city,customer_segment_,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits_,debt_to_income,Loan_Approved?
11,CUST100679,45.0,856826.0,662.0,Self-Employed,Postgraduate,Divorced,NaN,Affluent,Education,1412363.0,12,5.0,0.487,Yes
25,CUST100071,58.0,454340.0,743.0,Business,Graduate,Single,Jaipur,Premium,Business,1545154.0,72,3.0,0.333,Yes
58,CUST100345,63.0,477076.0,785.0,Salaried,Graduate,MARRIED,Chennai,SME,Education,1575763.0,24,8.0,0.419,No
157,CUST101362,24.0,782709.0,842.0,Salaried,12th,Married,NaN,Premium,Personal,120000000.0,48,6.0,NaN,No
180,CUST100421,64.0,1483255.0,751.0,Contract,Postgraduate,Married,Hyderabad,Mass,Auto,2033263.0,72,3.0,0.134,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1406,CUST100684,66.0,513360.0,682.0,Self-Employed,Graduate,Married,Mumbai,Premium,Auto,1309079.0,60,2.0,0.02,Yes
1439,CUST100764,64.0,761542.0,731.0,NaN,Graduate,MARRIED,Bangalore,Mass,Auto,2170814.0,72,2.0,0.247,Yes
1469,CUST100509,33.0,850268.0,829.0,Business,NaN,Married,Kolkata,Mass,Personal,1647932.0,72,4.0,0.329,Yes
1501,CUST100475,50.0,NaN,802.0,Contract,12th,Divorced,Kolkata,Mass,Personal,1488587.0,36,5.0,0.023,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes

In [234]:
# 29.Check the Debt to Income column and identify impossible values such as
# negative values or values greater than 1.

df["debt_to_income"].unique()

array(['0.258', '0.558', nan, '0.356', '0.169', '0.46', '0.323', '0.233',
       '0.375', '0.394', '0.476', '0.487', '0.494', '0.364', '0.529',
       '0.564', '0.303', '0.386', '0.177', '0.353', '0.657', '0.234',
       '0.195', '0.333', '0.485', '0.42', 0.4, '0.231', '-0.2', '0.291',
       '0.366', '0.449', '0.397', '0.287', '0.508', '0.533', '1.2',
       '0.112', '0.327', '0.348', '0.079', '0.328', '0.653', '0.228',
       '0.361', '0.164', '0.538', '0.381', '0.274', '0.741', '0.357',
       '0.317', '0.02', '0.419', '0.341', '0.304', '0.3', '0.32', '0.555',
       '0.44', '0.552', '0.259', '0.377', '0.331', '0.083', '0.619',
       '0.418', '9.0', '0.617', '0.246', '0.238', '0.308', '0.645',
       '0.723', '0.354', '0.682', '0.167', '0.457', '0.31', '0.368',
       '0.181', '0.241', '0.413', '0.048', '0.268', '0.441', '0.133',
       '0.365', '0.402', '0.276', '0.158', '0.352', '0.553', '0.279',
       '0.722', '0.193', '0.102', '0.622', '3.5', '0.629', '0.416',
       '0.199', '0.513', '0.215', '0.334', '0.29', '0.282', '0.608',
       '0.426', '0.35', '0.115', '0.343', 0.35, '0.495', '0.444', '0.172',
       '0.596', '0.173', '0.2', '0.252', '0.398', '0.399', '0.031',
       '0.313', '0.211', '0.236', '0.423', '0.424', '0.292', '0.261',
       '0.183', '0.683', '0.285', '0.321', '0.4', '0.445', '0.464',
       '0.256', '0.165', '0.408', '0.237', '0.521', '0.094', '0.383',
       '0.157', '0.296', '0.134', '0.182', '0.637', '0.483', '0.493',
       '0.455', '0.16', '0.251', '0.213', '0.288', '0.509', '0.107',
       '0.243', '0.422', '0.325', '0.224', '0.283', '0.36', '0.401',
       '0.728', '0.492', '0.216', '0.209', '0.175', '0.545', '0.119',
       '0.139', '0.524', '0.324', '0.373', '0.561', '0.219', '0.09',
       '0.153', '0.459', '0.403', '0.551', '0.454', '0.319', '0.514',
       '0.272', '0.411', '0.128', '0.125', '0.489', '0.143', '0.523',
       '0.436', '0.269', '0.098', '0.548', '0.574', '0.472', '0.137',
       '0.189', '0.567', '0.142', '0.446', '0.433', '0.388', '0.415',
       '0.254', '0.186', '0.203', '0.477', '0.51', '0.267', '0.166',
       '0.369', '0.121', '0.147', '0.271', '0.469', '0.486', '0.473',
       '0.439', '0.748', '0.322', '0.136', '0.275', '0.295', '0.212',
       '0.501', '0.382', '0.479', '0.065', '0.226', '0.385', '0.38',
       '0.468', '0.185', '0.318', '0.539', '0.5', '0.421', '0.198',
       '0.248', '0.171', '0.289', '0.431', '0.581', '0.478', '0.432',
       '0.335', '0.652', '0.097', '0.435', '0.376', '0.355', '0.338',
       '0.222', '0.425', '0.427', '0.515', '0.417', '0.103', '0.404',
       '0.559', '0.384', '0.14', '0.18', '0.488', '0.148', '0.161',
       '0.229', '0.249', '0.387', '0.526', '0.344', '0.371', '0.255',
       '0.096', '0.124', '0.178', '0.482', '0.311', '0.544', '0.24',
       '0.108', '0.264', '0.37', '0.347', '0.309', '0.463', '0.168',
       '0.461', '0.442', '0.541', '0.174', '0.221', '0.242', '0.475',
       '0.214', '0.598', '0.247', '0.316', '0.208', '0.277', '0.499',
       '0.095', '0.342', '0.326', '0.346', '0.45', '0.456', '0.504',
       '0.606', '0.122', '0.345', '0.578', '0.336', '0.359', '0.379',
       '0.263', '0.497', '0.298', '0.41', '0.618', '0.281', '0.412',
       '0.438', '0.306', '0.135', '0.041', '0.106', '0.126', '0.563',
       '0.414', '0.23', '0.266', '0.245', '0.315', '0.636', '0.407',
       '0.075', '0.577', '0.676', '0.244', '0.48', '0.329', '0.13',
       '0.101', '0.151', '0.196', '0.027', '0.297', '0.536', '0.588',
       '0.54', '0.374', '0.047', '0.584', '0.451', '0.556', '0.518',
       '0.613', '0.081', '0.447', '0.078', '0.12', '0.273', '0.191',
       '0.428', '0.305', '0.253', '0.349', '0.638', '0.542', '0.159',
       '0.516', '0.39', '0.307', '0.698', '0.507', '0.406', '0.512',
       '0.755', '0.465', '0.474', '0.301', '0.063', '0.27', '0.184',
       '0.074', '0.572', '0.57', '0.484', '0.481', '0.284', '0.294',
       '0.179', '0.064', '0.207', '0.672', '0.491', '0.503', '0.114',
       '0.188', '0.197', '0.156', '0.076', '0.59', '0.389', '0.458',
       '0.648', '0.144', '0.293', '0.217', '0.235', '0.05', '0.395',
       '0.68', '0.066', '0.339', '0.032', '0.78', '0.19', '0.547', '0.55',
       '0.466', '0.227', '0.358', '0.362', '0.15', '0.084', '0.53',
       '0.257', '0.367', '0.64', '0.363', '0.614', '0.405', '0.129',
       '0.34', '0.739', '0.332', '0.141', '0.314', '0.537', '0.434',
       '0.579', '0.43', '0.452', '0.082', '0.735', '0.554', '0.517',
       '0.665', '0.605', '0.239', '0.505', '0.26', '0.639', '0.163',
       '0.351', '0.534', '0.204', '0.532', '0.378', '0.74', '0.206',
       '0.569', '0.149', '0.396', '0.49', '0.462', '0.409', '0.146',
       '0.594', '0.123', '0.67', '0.506', '0.771', '0.21', '0.372',
       '0.104', '0.202', '0.176', '0.691', '0.58', '0.582', '0.635',
       '0.674', '0.22', '0.117', '0.528', '0.688', '0.392', '0.429',
       '0.527', '0.393', '0.17', '0.28', '0.087', '0.437', '0.225',
       '0.597', '0.6', '0.059', '0.549', '0.33', '0.25', '0.089', '0.522',
       '0.391', '0.724', '0.337', '0.633', '0.145', '0.223', '0.496',
       '0.302', '0.023', '0.651', '0.628'], dtype=object)

In [235]:
df["debt_to_income"]=pd.to_numeric(df["debt_to_income"],errors = "coerce")

In [236]:
df[ (df["debt_to_income"]<0) | (df["debt_to_income"]>1)]["debt_to_income"].value_counts()

debt_to_income
 1.2    5
 9.0    5
 3.5    5
-0.2    3
Name: count, dtype: int64

In [237]:
df=df.replace({"debt_to_income":{1.2:np.nan,
                                 9.0:np.nan,
                                 3.5:np.nan,
                                 -0.2:np.nan}})

In [238]:
df[ (df["debt_to_income"]<0) | (df["debt_to_income"]>1)]["debt_to_income"].value_counts()

Series([], Name: count, dtype: int64)

In [239]:
# 30.Final cleaning task: Create a completely cleaned version of the dataset by:
# • Cleaning column names
# • Removing duplicates
# • Handling missing values
# • Fixing data types
# • Cleaning numerical columns
# • Standardizing categorical values
# • Handling invalid values
# • Detecting and treating outliers
# • Checking the final dataset for remaining errors

In [240]:
df.columns

Index(['_Customer_ID_', 'Age_', 'Annual_Income', 'credit_Score_',
       'Employment-Type', 'Education__Level', 'marital_status', 'city',
       'customer_segment_', 'loan_type', 'Loan_Amount_(INR)', 'tenure_Months',
       'Monthly_Visits_', 'debt_to_income', 'Loan_Approved?'],
      dtype='object')

In [241]:
df.columns.drop_duplicates()

Index(['_Customer_ID_', 'Age_', 'Annual_Income', 'credit_Score_',
       'Employment-Type', 'Education__Level', 'marital_status', 'city',
       'customer_segment_', 'loan_type', 'Loan_Amount_(INR)', 'tenure_Months',
       'Monthly_Visits_', 'debt_to_income', 'Loan_Approved?'],
      dtype='object')

In [245]:
numeric_col = df.select_dtypes(include=["int","float"]).columns
for i in numeric_col:
    mean = df[i].mean()
    df[i]=df[i].fillna(mean)

In [246]:
ct_col = df.select_dtypes(include=["object"]).columns
for i in ct_col:
    mode = df[i].mode()
    df[i]=df[i].fillna(mode[0])

In [249]:
df

,_Customer_ID_,Age_,Annual_Income,credit_Score_,Employment-Type,Education__Level,marital_status,city,customer_segment_,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits_,debt_to_income,Loan_Approved?
0,CUST101160,37.0,2.978090e+05,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258000,No
1,CUST100077,36.0,1.048283e+06,874.0,Contract,Graduate,Single,Jaipur,Premium,Auto,751792.0,48,11.0,0.558000,Yes
2,CUST100317,55.0,1.043481e+06,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,0.343654,Yes
3,CUST101041,54.0,3.695910e+05,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356000,Yes
4,CUST101358,27.0,6.669890e+05,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169000,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40.0,4.777230e+05,719.0,Self-Employed,Graduate,Single,Jaipur,Mass,Home,1106455.0,48,5.0,0.569000,No
1531,CUST101295,65.0,1.394481e+06,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344000,Yes
1532,CUST100861,66.0,9.400665e+05,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084000,Yes
1533,CUST101460,45.0,5.433400e+05,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089000,No
1534,CUST101127,61.0,9.400665e+05,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259000,No