In [1]:
# Challenge 1 – Complete Data Cleaning
# Your manager gives you a messy dataset.
# Perform all of the following:
# • Load the dataset.
# • Display dataset information.
# • Find missing values.
# • Remove duplicate rows.
# • Fill missing values:
# o Age → median
# o Balance → mean
# • Rename:
# o Target → CustomerStatus
# o AnnualIncome → Income
# • Display the first 15 rows.
# Methods expected:
# read_csv()
# info()
# isnull()
# drop_duplicates()
# median()
# mean()
# fillna()
# rename()
# head()

import pandas as pd

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [3]:
df.isnull().sum()

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [8]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1015     True
1016     True
1017     True
1018     True
1019     True
Length: 1020, dtype: bool

In [9]:
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [21]:
age_median = df['Age'].median()
age_median

df['Age'] = df['Age'].fillna(age_median)
df['Age'] = df['Age'].astype("int")
df['Age']
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184.0,2139,581,97523,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620.0,7121,644,60353,2,USA,Other,Corporate,Stay
1016,10753,25,54490.0,13794,303,124512,4,India,NaN,Corporate,Churn
1017,10810,49,82062.0,47170,813,53850,8,Germany,Female,Retail,Stay
1018,10267,38,NaN,10424,722,138100,6,Germany,Other,Corporate,Stay
1019,10059,62,97504.0,36833,430,97523,10,Canada,Other,NaN,Churn

In [22]:
Balance_mean = df['Balance'].mean()
Balance_mean

df['Balance']=df['Balance'].fillna(Balance_mean)
df['Balance']=df['Balance'].astype("int")
df['Balance']
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184.0,2139,581,97523,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620.0,7121,644,60353,2,USA,Other,Corporate,Stay
1016,10753,25,54490.0,13794,303,124512,4,India,NaN,Corporate,Churn
1017,10810,49,82062.0,47170,813,53850,8,Germany,Female,Retail,Stay
1018,10267,38,NaN,10424,722,138100,6,Germany,Other,Corporate,Stay
1019,10059,62,97504.0,36833,430,97523,10,Canada,Other,NaN,Churn

In [25]:
df.rename(columns = {"Target":"CustomerStatus",
                     "AnnualIncome":"Income"},inplace = True)
df

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58,49184.0,2139,581,97523,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620.0,7121,644,60353,2,USA,Other,Corporate,Stay
1016,10753,25,54490.0,13794,303,124512,4,India,NaN,Corporate,Churn
1017,10810,49,82062.0,47170,813,53850,8,Germany,Female,Retail,Stay
1018,10267,38,NaN,10424,722,138100,6,Germany,Other,Corporate,Stay
1019,10059,62,97504.0,36833,430,97523,10,Canada,Other,NaN,Churn

In [26]:
df.head(15)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58,49184.0,2139,581,97523,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985,5,UK,Other,Corporate,Churn
5,10006,69,31390.0,48323,770,107245,6,India,Other,Corporate,Stay
6,10007,58,182141.0,24200,891,38457,1,India,Other,Retail,Churn
7,10008,67,95861.0,5729,538,173296,6,UK,Female,SME,Stay
8,10009,41,62638.0,24760,663,41901,4,France,Other,SME,Stay
9,10010,22,179680.0,42113,475,106827,3,USA,Female,Corporate,Churn
10,10011,44,187772.0,45599,870,43923,5,India,NaN,Retail,Stay
11,10012,69,102694.0,26790,574,13237,9,France,Female,Retail,Churn
12,10013,59,150870.0,26428,769,28574,2,USA,Other,SME,Stay
13,10014,52,88876.0,49456,898,85686,9,Canada,Female,Retail,Stay
14,10015,26,153569.0,32843,393,151156,1,USA,Other,Retail,Churn

In [28]:
# Challenge 2 – Banking Report
# The bank wants a numeric report.
# Tasks
# • Select only numeric columns.
# • Display summary statistics.
# • Convert Age and CreditScore to float.
# • Display information again.

df1=df.select_dtypes(["int","float"])
df1.describe()

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,967.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112505.928645,25232.615686,602.659804,97523.041176,5.261765
std,288.022115,15.136428,52303.362541,14219.393105,176.560690,54382.352688,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.000000,0.000000
25%,10252.750000,31.000000,66149.000000,13134.750000,440.750000,52145.500000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.000000,5.000000
75%,10752.250000,57.000000,158000.500000,37956.000000,757.250000,142086.000000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.000000,10.000000

In [29]:
df1['Age']=df1['Age'].astype("float")
df1

      CustomerID   Age    Income  Spending  CreditScore  Balance  Tenure
0          10001  58.0   49184.0      2139          581    97523       2
1          10002  65.0  162964.0      6197          732     6356       1
2          10003  56.0   26956.0     37281          503   143203       8
3          10004  55.0   92926.0       925          463   139627       5
4          10005  66.0  108236.0      7198          394    75985       5
...          ...   ...       ...       ...          ...      ...     ...
1015       10450  43.0  173620.0      7121          644    60353       2
1016       10753  25.0   54490.0     13794          303   124512       4
1017       10810  49.0   82062.0     47170          813    53850       8
1018       10267  38.0       NaN     10424          722   138100       6
1019       10059  62.0   97504.0     36833          430    97523      10

[1020 rows x 7 columns]

In [30]:
df1['CreditScore']=df1['CreditScore'].astype("float")
df1

      CustomerID   Age    Income  Spending  CreditScore  Balance  Tenure
0          10001  58.0   49184.0      2139        581.0    97523       2
1          10002  65.0  162964.0      6197        732.0     6356       1
2          10003  56.0   26956.0     37281        503.0   143203       8
3          10004  55.0   92926.0       925        463.0   139627       5
4          10005  66.0  108236.0      7198        394.0    75985       5
...          ...   ...       ...       ...          ...      ...     ...
1015       10450  43.0  173620.0      7121        644.0    60353       2
1016       10753  25.0   54490.0     13794        303.0   124512       4
1017       10810  49.0   82062.0     47170        813.0    53850       8
1018       10267  38.0       NaN     10424        722.0   138100       6
1019       10059  62.0   97504.0     36833        430.0    97523      10

[1020 rows x 7 columns]

In [31]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   1020 non-null   int64
 1   Age          1020 non-null   float64
 2   Income       967 non-null    float64
 3   Spending     1020 non-null   int64
 4   CreditScore  1020 non-null   float64
 5   Balance      1020 non-null   int64
 6   Tenure       1020 non-null   int64
dtypes: float64(3), int64(4)
memory usage: 55.9 KB

In [44]:
# Challenge 3 – Duplicate Investigation
# Find duplicate customers.
# Then
# • Count duplicate rows.
# • Remove duplicates.
# • Print information before and after removing duplicates.
# • Show the last 20 rows.

df.duplicated().sum()
df.tail(20)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
1000,10643,41,125012.0,18825,761,35977,2,Germany,Other,Retail,Stay
1001,10763,56,102965.0,17517,838,115028,9,UK,NaN,SME,Stay
1002,10910,66,118506.0,6296,306,81892,4,Canada,Male,SME,Churn
1003,10200,19,115052.0,20741,484,190233,5,Canada,Male,Retail,Churn
1004,10587,29,NaN,40255,383,168358,2,Germany,Male,Corporate,Churn
1005,10798,22,176830.0,7626,688,65481,10,France,Male,Retail,Stay
1006,10653,32,NaN,21266,598,142086,9,France,Female,Corporate,Stay
1007,10756,53,74430.0,3705,489,29651,10,UK,Male,Retail,Churn
1008,10417,70,40417.0,37956,681,23880,10,India,Male,Retail,Stay
1009,10499,34,166546.0,12497,643,130886,3,UK,Male,SME,Stay
1010,10515,62,199762.0,41808,309,60223,10,India,Other,SME,Churn
1011,10457,44,63604.0,27633,804,176354,5,Germany,Female,Retail,Stay
1012,10882,61,115417.0,3879,413,76591,7,NaN,Male,Corporate,Churn
1013,10531,64,85162.0,32083,654,132742,10,Canada,Male,SME,Stay
1014,10181,50,166466.0,44281,662,14415,0,Canada,Male,Corporate,Churn
1015,10450,43,173620.0,7121,644,60353,2,USA,Other,Corporate,Stay
1016,10753,25,54490.0,13794,303,124512,4,India,NaN,Corporate,Churn
1017,10810,49,82062.0,47170,813,53850,8,Germany,Female,Retail,Stay
1018,10267,38,NaN,10424,722,138100,6,Germany,Other,Corporate,Stay
1019,10059,62,97504.0,36833,430,97523,10,Canada,Other,NaN,Churn

In [46]:
df1=df.drop_duplicates()
df1.tail(20)

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
980,10981,41,199633.0,8498,847,173390,7,Canada,Male,Corporate,Stay
981,10982,34,98876.0,6414,541,59484,2,Canada,Other,Corporate,Stay
982,10983,69,188933.0,27126,334,97523,1,Canada,Female,SME,Churn
983,10984,44,107221.0,47514,732,175352,1,USA,Other,Corporate,Churn
984,10985,50,37397.0,23559,730,120423,8,France,Female,Corporate,Stay
985,10986,62,27169.0,3914,488,126031,10,USA,Male,Corporate,Churn
986,10987,30,184704.0,20524,621,115161,1,USA,Male,SME,Churn
987,10988,63,190178.0,9025,720,158528,5,NaN,Female,SME,Stay
988,10989,26,88335.0,11869,635,159905,3,India,Female,Corporate,Stay
989,10990,29,123152.0,25228,884,44897,0,Germany,Other,SME,Churn
990,10991,58,79954.0,6331,773,39653,2,India,Female,SME,Stay
991,10992,45,NaN,17549,452,17812,5,USA,Other,Retail,Churn
992,10993,18,157845.0,29018,764,165451,7,India,Male,SME,Stay
993,10994,31,69950.0,17945,594,149288,6,USA,Female,Retail,Stay
994,10995,56,76509.0,19044,493,83666,6,USA,Male,Corporate,Churn
995,10996,34,81731.0,40980,761,181465,5,Germany,Other,SME,Stay
996,10997,47,42475.0,1176,780,26640,5,France,Female,SME,Stay
997,10998,31,120531.0,46929,733,147220,4,India,Male,SME,Stay
998,10999,21,33661.0,22314,540,94186,5,NaN,Other,SME,Stay
999,11000,63,31930.0,851,559,100908,6,UK,Female,NaN,Stay

In [48]:
# Challenge 4 – HR Department
# HR wants better column names.
# Rename
# CustomerID → Employee_ID
# Age → EmployeeAge
# Gender → EmployeeGender
# AnnualIncome → Salary
# Target → PromotionStatus
# Then
# • Add prefix
# HR_
# to every column.
# Display 10 random records.


df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [50]:
df.rename(columns = {"CustomerID":"Employee_ID",
                      "Age":"EmployeeAge",
                      "Gender":"EmployeeGender",
                      "AnnualIncome":"Salary",
                      "Target":"PromotionStatus"},inplace = True)

df

,Employee_ID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [51]:
df.add_prefix("HR_")

,HR_Employee_ID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [52]:
df.sample(10)

,Employee_ID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
641,10642,57.0,109940.0,24481,488,99754.00,3,Canada,Other,Corporate,Churn
822,10823,66.0,NaN,3942,471,92802.99,7,UK,Female,NaN,Churn
989,10990,29.0,123152.0,25228,884,44897.43,0,Germany,Other,SME,Churn
53,10054,43.0,198131.0,35641,639,187847.43,1,UK,Male,SME,Churn
539,10540,40.0,186110.0,19635,860,104397.02,1,India,Male,Corporate,Churn
661,10662,46.0,100705.0,24471,722,51961.41,4,India,Male,SME,Stay
982,10983,69.0,188933.0,27126,334,NaN,1,Canada,Female,SME,Churn
705,10706,22.0,105116.0,32123,477,97655.28,9,India,Other,SME,Churn
498,10499,34.0,166546.0,12497,643,130886.93,3,UK,Male,SME,Stay
906,10907,40.0,100762.0,29701,874,17519.73,7,NaN,Female,Corporate,Churn

In [124]:
# Challenge 5 – Finance Cleaning
# Finance department reports missing values.
# Tasks
# Fill
# AnnualIncome → Median
# Balance → Mean
# Age → Median
# Then
# Generate descriptive statistics.

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [125]:
AnnualIncome_median = df['AnnualIncome'].median()
AnnualIncome_median

df['AnnualIncome'] = df['AnnualIncome'].fillna(AnnualIncome_median)
df['AnnualIncome'] = df['AnnualIncome'].astype("int")
df['AnnualIncome']
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,112358,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504,36833,430,NaN,10,Canada,Other,NaN,Churn

In [126]:
age_median = df['Age'].median()
age_median

df['Age'] = df['Age'].fillna(age_median)
df['Age'] = df['Age'].astype("int")
df['Age']
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65,162964,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56,26956,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55,92926,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66,108236,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25,54490,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49,82062,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38,112358,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62,97504,36833,430,NaN,10,Canada,Other,NaN,Churn

In [127]:
Balance_mean = df['AnnualIncome'].mean()
Balance_mean

df['Balance'] = df['Balance'].fillna(Balance_mean)
df['Balance'] = df['Balance'].astype("int")
df['Balance']
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184,2139,581,112498,2,France,Male,SME,Stay
1,10002,65,162964,6197,732,6356,1,USA,Male,SME,Churn
2,10003,56,26956,37281,503,143203,8,Canada,Male,Corporate,Stay
3,10004,55,92926,925,463,139627,5,NaN,Male,Retail,Churn
4,10005,66,108236,7198,394,75985,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620,7121,644,60353,2,USA,Other,Corporate,Stay
1016,10753,25,54490,13794,303,124512,4,India,NaN,Corporate,Churn
1017,10810,49,82062,47170,813,53850,8,Germany,Female,Retail,Stay
1018,10267,38,112358,10424,722,138100,6,Germany,Other,Corporate,Stay
1019,10059,62,97504,36833,430,112498,10,Canada,Other,NaN,Churn

In [128]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,98271.791176,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54480.295338,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.000000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.500000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,99929.000000,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.000000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.000000,10.000000

In [129]:
# Challenge 6 – Data Type Audit
# The company says
# Age and AnnualIncome are stored incorrectly.
# Tasks
# Convert
# Age → int
# AnnualIncome → float
# Balance → float
# Target → string
# Print information.

df['Age']=df['Age'].astype("int")
df['AnnualIncome']=df['AnnualIncome'].astype("float")
df['Balance']=df['Balance'].astype("float")
df['Target']=df['Target'].astype("str")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB

In [130]:
# Challenge 7 – Customer Analytics
# Create a new DataFrame that
# • removes Segment
# • removes Geography
# • removes duplicate rows
# Display
# • first 10 rows
# • dataset information
# • statistical summary

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184.0,2139,581,112498.0,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.0,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.0,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.0,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.0,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43,173620.0,7121,644,60353.0,2,USA,Other,Corporate,Stay
1016,10753,25,54490.0,13794,303,124512.0,4,India,NaN,Corporate,Churn
1017,10810,49,82062.0,47170,813,53850.0,8,Germany,Female,Retail,Stay
1018,10267,38,112358.0,10424,722,138100.0,6,Germany,Other,Corporate,Stay
1019,10059,62,97504.0,36833,430,112498.0,10,Canada,Other,NaN,Churn

In [131]:
df.drop('Segment', axis = 1)
df.drop('Geography',axis = 1)
df.drop_duplicates(inplace = True)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184.0,2139,581,112498.0,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.0,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.0,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.0,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.0,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34,81731.0,40980,761,181465.0,5,Germany,Other,SME,Stay
996,10997,47,42475.0,1176,780,26640.0,5,France,Female,SME,Stay
997,10998,31,120531.0,46929,733,147220.0,4,India,Male,SME,Stay
998,10999,21,33661.0,22314,540,94186.0,5,NaN,Other,SME,Stay
999,11000,63,31930.0,851,559,100908.0,6,UK,Female,NaN,Stay

In [132]:
df.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184.0,2139,581,112498.0,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.0,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.0,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.0,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.0,5,UK,Other,Corporate,Churn
5,10006,69,31390.0,48323,770,107245.0,6,India,Other,Corporate,Stay
6,10007,58,182141.0,24200,891,38457.0,1,India,Other,Retail,Churn
7,10008,67,95861.0,5729,538,173296.0,6,UK,Female,SME,Stay
8,10009,41,62638.0,24760,663,41901.0,4,France,Other,SME,Stay
9,10010,22,179680.0,42113,475,106827.0,3,USA,Female,Corporate,Churn

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           1000 non-null   int64
 2   AnnualIncome  1000 non-null   float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       1000 non-null   float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 93.8+ KB

In [134]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112453.288000,25285.558000,603.088000,98304.117000,5.241000
std,288.819436,15.130834,51081.479931,14211.735656,176.605486,54527.473952,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.000000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52073.500000,2.000000
50%,10500.500000,44.000000,112358.000000,24901.000000,606.500000,99929.000000,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.000000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.000000,10.000000

In [135]:
# Challenge 8 – ML Dataset Preparation
# Prepare a machine learning dataset.
# Perform
# • Remove duplicates
# • Remove CustomerID
# • Remove Segment
# • Fill missing values
# • Rename Target to Output
# Finally
# Display
# head()
# info()
# describe()
# value_counts(Output)

df.drop_duplicates(inplace=True)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184.0,2139,581,112498.0,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.0,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.0,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.0,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.0,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34,81731.0,40980,761,181465.0,5,Germany,Other,SME,Stay
996,10997,47,42475.0,1176,780,26640.0,5,France,Female,SME,Stay
997,10998,31,120531.0,46929,733,147220.0,4,India,Male,SME,Stay
998,10999,21,33661.0,22314,540,94186.0,5,NaN,Other,SME,Stay
999,11000,63,31930.0,851,559,100908.0,6,UK,Female,NaN,Stay

In [136]:
df.drop('CustomerID', axis = 1 , inplace = True)
df.drop('Segment', axis = 1 , inplace = True)
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Target
0,58,49184.0,2139,581,112498.0,2,France,Male,Stay
1,65,162964.0,6197,732,6356.0,1,USA,Male,Churn
2,56,26956.0,37281,503,143203.0,8,Canada,Male,Stay
3,55,92926.0,925,463,139627.0,5,NaN,Male,Churn
4,66,108236.0,7198,394,75985.0,5,UK,Other,Churn
...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465.0,5,Germany,Other,Stay
996,47,42475.0,1176,780,26640.0,5,France,Female,Stay
997,31,120531.0,46929,733,147220.0,4,India,Male,Stay
998,21,33661.0,22314,540,94186.0,5,NaN,Other,Stay
999,63,31930.0,851,559,100908.0,6,UK,Female,Stay

In [137]:
df.value_counts()

Age  AnnualIncome  Spending  CreditScore  Balance   Tenure  Geography  Gender  Target
18   21864.0       38378     835          23565.0   0       Canada     Other   Churn     1
50   123395.0      13243     802          63551.0   9       Germany    Male    Stay      1
52   88876.0       49456     898          85686.0   9       Canada     Female  Stay      1
     102766.0      32391     607          50194.0   9       India      Female  Stay      1
     106960.0      25655     443          158099.0  1       Germany    Other   Churn     1
                                                                                        ..
37   28449.0       29973     569          69715.0   1       Canada     Male    Churn     1
     29796.0       48393     890          76309.0   0       UK         Female  Churn     1
     55947.0       25582     436          128315.0  10      USA        Male    Churn     1
     63163.0       11114     630          186947.0  3       UK         Other   Stay      1
70   195168.0      3679      306          82478.0   10      USA        Male    Churn     1
Name: count, Length: 901, dtype: int64

In [138]:
df.rename(columns = {"Target":"Output"}, inplace = True)
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output
0,58,49184.0,2139,581,112498.0,2,France,Male,Stay
1,65,162964.0,6197,732,6356.0,1,USA,Male,Churn
2,56,26956.0,37281,503,143203.0,8,Canada,Male,Stay
3,55,92926.0,925,463,139627.0,5,NaN,Male,Churn
4,66,108236.0,7198,394,75985.0,5,UK,Other,Churn
...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465.0,5,Germany,Other,Stay
996,47,42475.0,1176,780,26640.0,5,France,Female,Stay
997,31,120531.0,46929,733,147220.0,4,India,Male,Stay
998,21,33661.0,22314,540,94186.0,5,NaN,Other,Stay
999,63,31930.0,851,559,100908.0,6,UK,Female,Stay

In [139]:
df.value_counts()

Age  AnnualIncome  Spending  CreditScore  Balance   Tenure  Geography  Gender  Output
18   21864.0       38378     835          23565.0   0       Canada     Other   Churn     1
50   123395.0      13243     802          63551.0   9       Germany    Male    Stay      1
52   88876.0       49456     898          85686.0   9       Canada     Female  Stay      1
     102766.0      32391     607          50194.0   9       India      Female  Stay      1
     106960.0      25655     443          158099.0  1       Germany    Other   Churn     1
                                                                                        ..
37   28449.0       29973     569          69715.0   1       Canada     Male    Churn     1
     29796.0       48393     890          76309.0   0       UK         Female  Churn     1
     55947.0       25582     436          128315.0  10      USA        Male    Churn     1
     63163.0       11114     630          186947.0  3       UK         Other   Stay      1
70   195168.0      3679      306          82478.0   10      USA        Male    Churn     1
Name: count, Length: 901, dtype: int64

In [140]:
# Challenge 9 – Column Transformation
# Create these new columns
# NetWorth = Balance + AnnualIncome
# AgeAfterRetirement = Age + 20
# DoubleCreditScore = CreditScore * 2
# IncomePerMonth = AnnualIncome / 12
# Then
# Display first 15 rows.

df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output
0,58,49184.0,2139,581,112498.0,2,France,Male,Stay
1,65,162964.0,6197,732,6356.0,1,USA,Male,Churn
2,56,26956.0,37281,503,143203.0,8,Canada,Male,Stay
3,55,92926.0,925,463,139627.0,5,NaN,Male,Churn
4,66,108236.0,7198,394,75985.0,5,UK,Other,Churn
...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465.0,5,Germany,Other,Stay
996,47,42475.0,1176,780,26640.0,5,France,Female,Stay
997,31,120531.0,46929,733,147220.0,4,India,Male,Stay
998,21,33661.0,22314,540,94186.0,5,NaN,Other,Stay
999,63,31930.0,851,559,100908.0,6,UK,Female,Stay

In [141]:
df["NetWorth"]=df["Balance"]+df["AnnualIncome"]
df["AgeAfterRetirement"]= df["Age"] + 20
df["DoubleCreditScore"]=df["CreditScore"]*2
df["IncomePerMonth"]=df["AnnualIncome"]/12
df.head(15)

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,58,49184.0,2139,581,112498.0,2,France,Male,Stay,161682.0,78,1162,4098.666667
1,65,162964.0,6197,732,6356.0,1,USA,Male,Churn,169320.0,85,1464,13580.333333
2,56,26956.0,37281,503,143203.0,8,Canada,Male,Stay,170159.0,76,1006,2246.333333
3,55,92926.0,925,463,139627.0,5,NaN,Male,Churn,232553.0,75,926,7743.833333
4,66,108236.0,7198,394,75985.0,5,UK,Other,Churn,184221.0,86,788,9019.666667
5,69,31390.0,48323,770,107245.0,6,India,Other,Stay,138635.0,89,1540,2615.833333
6,58,182141.0,24200,891,38457.0,1,India,Other,Churn,220598.0,78,1782,15178.416667
7,67,95861.0,5729,538,173296.0,6,UK,Female,Stay,269157.0,87,1076,7988.416667
8,41,62638.0,24760,663,41901.0,4,France,Other,Stay,104539.0,61,1326,5219.833333
9,22,179680.0,42113,475,106827.0,3,USA,Female,Churn,286507.0,42,950,14973.333333
10,44,187772.0,45599,870,43923.0,5,India,NaN,Stay,231695.0,64,1740,15647.666667
11,69,102694.0,26790,574,13237.0,9,France,Female,Churn,115931.0,89,1148,8557.833333
12,59,150870.0,26428,769,28574.0,2,USA,Other,Stay,179444.0,79,1538,12572.500000
13,52,88876.0,49456,898,85686.0,9,Canada,Female,Stay,174562.0,72,1796,7406.333333
14,26,153569.0,32843,393,151156.0,1,USA,Other,Churn,304725.0,46,786,12797.416667

In [142]:
# Challenge 10 – Company Report
# Display
# • first five rows
# • last five rows
# • ten random rows
# • dataset information
# • descriptive statistics
# Finally rename
# Target → Customer_Status

df.head()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,58,49184.0,2139,581,112498.0,2,France,Male,Stay,161682.0,78,1162,4098.666667
1,65,162964.0,6197,732,6356.0,1,USA,Male,Churn,169320.0,85,1464,13580.333333
2,56,26956.0,37281,503,143203.0,8,Canada,Male,Stay,170159.0,76,1006,2246.333333
3,55,92926.0,925,463,139627.0,5,NaN,Male,Churn,232553.0,75,926,7743.833333
4,66,108236.0,7198,394,75985.0,5,UK,Other,Churn,184221.0,86,788,9019.666667

In [143]:
df.tail()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
995,34,81731.0,40980,761,181465.0,5,Germany,Other,Stay,263196.0,54,1522,6810.916667
996,47,42475.0,1176,780,26640.0,5,France,Female,Stay,69115.0,67,1560,3539.583333
997,31,120531.0,46929,733,147220.0,4,India,Male,Stay,267751.0,51,1466,10044.250000
998,21,33661.0,22314,540,94186.0,5,NaN,Other,Stay,127847.0,41,1080,2805.083333
999,63,31930.0,851,559,100908.0,6,UK,Female,Stay,132838.0,83,1118,2660.833333

In [144]:
df.sample(10)

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
75,39,195341.0,45008,714,144836.0,7,USA,Other,Stay,340177.0,59,1428,16278.416667
701,56,24273.0,34422,438,198682.0,4,India,Female,Churn,222955.0,76,876,2022.750000
132,27,84014.0,35310,721,113185.0,2,USA,Male,Stay,197199.0,47,1442,7001.166667
544,55,65521.0,48373,431,20710.0,10,Germany,Other,Churn,86231.0,75,862,5460.083333
629,67,140284.0,45168,771,179304.0,0,Canada,Male,Churn,319588.0,87,1542,11690.333333
472,27,175988.0,17400,627,182160.0,1,India,Female,Churn,358148.0,47,1254,14665.666667
123,46,112358.0,32241,653,112498.0,8,Canada,Female,Stay,224856.0,66,1306,9363.166667
307,68,157484.0,21388,726,81651.0,4,Canada,Male,Stay,239135.0,88,1452,13123.666667
322,27,22396.0,14834,817,91201.0,0,Germany,Other,Churn,113597.0,47,1634,1866.333333
356,24,87826.0,15049,822,149370.0,8,Germany,Other,Stay,237196.0,44,1644,7318.833333

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 1000 non-null   int64
 1   AnnualIncome        1000 non-null   float64
 2   Spending            1000 non-null   int64
 3   CreditScore         1000 non-null   int64
 4   Balance             1000 non-null   float64
 5   Tenure              1000 non-null   int64
 6   Geography           950 non-null    object
 7   Gender              950 non-null    object
 8   Output              1000 non-null   object
 9   NetWorth            1000 non-null   float64
 10  AgeAfterRetirement  1000 non-null   int64
 11  DoubleCreditScore   1000 non-null   int64
 12  IncomePerMonth      1000 non-null   float64
dtypes: float64(4), int64(6), object(3)
memory usage: 109.4+ KB

In [146]:
df.describe()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,44.202000,112453.288000,25285.558000,603.088000,98304.117000,5.241000,210757.405000,64.202000,1206.176000,9371.107333
std,15.130834,51081.479931,14211.735656,176.605486,54527.473952,3.179155,73214.440097,15.130834,353.210972,4256.789994
min,18.000000,20227.000000,537.000000,300.000000,547.000000,0.000000,33432.000000,38.000000,600.000000,1685.583333
25%,31.000000,68437.250000,13213.000000,441.000000,52073.500000,2.000000,157635.000000,51.000000,882.000000,5703.104167
50%,44.000000,112358.000000,24901.000000,606.500000,99929.000000,5.000000,210218.000000,64.000000,1213.000000,9363.166667
75%,57.000000,155570.750000,37960.250000,758.250000,142297.000000,8.000000,264245.750000,77.000000,1516.500000,12964.229167
max,70.000000,199967.000000,49995.000000,900.000000,199885.000000,10.000000,390628.000000,90.000000,1800.000000,16663.916667

In [147]:
df.rename(columns = {"Output":"Customer_Status"},inplace = True)
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Customer_Status,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,58,49184.0,2139,581,112498.0,2,France,Male,Stay,161682.0,78,1162,4098.666667
1,65,162964.0,6197,732,6356.0,1,USA,Male,Churn,169320.0,85,1464,13580.333333
2,56,26956.0,37281,503,143203.0,8,Canada,Male,Stay,170159.0,76,1006,2246.333333
3,55,92926.0,925,463,139627.0,5,NaN,Male,Churn,232553.0,75,926,7743.833333
4,66,108236.0,7198,394,75985.0,5,UK,Other,Churn,184221.0,86,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465.0,5,Germany,Other,Stay,263196.0,54,1522,6810.916667
996,47,42475.0,1176,780,26640.0,5,France,Female,Stay,69115.0,67,1560,3539.583333
997,31,120531.0,46929,733,147220.0,4,India,Male,Stay,267751.0,51,1466,10044.250000
998,21,33661.0,22314,540,94186.0,5,NaN,Other,Stay,127847.0,41,1080,2805.083333
999,63,31930.0,851,559,100908.0,6,UK,Female,Stay,132838.0,83,1118,2660.833333

In [148]:
# Challenge 11 – Missing Value Report
# Create a report showing
# • Total missing values
# • Numerical columns
# • Mean of Balance
# • Median of Age
# • Fill missing values
# • Display information again

df.describe()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,44.202000,112453.288000,25285.558000,603.088000,98304.117000,5.241000,210757.405000,64.202000,1206.176000,9371.107333
std,15.130834,51081.479931,14211.735656,176.605486,54527.473952,3.179155,73214.440097,15.130834,353.210972,4256.789994
min,18.000000,20227.000000,537.000000,300.000000,547.000000,0.000000,33432.000000,38.000000,600.000000,1685.583333
25%,31.000000,68437.250000,13213.000000,441.000000,52073.500000,2.000000,157635.000000,51.000000,882.000000,5703.104167
50%,44.000000,112358.000000,24901.000000,606.500000,99929.000000,5.000000,210218.000000,64.000000,1213.000000,9363.166667
75%,57.000000,155570.750000,37960.250000,758.250000,142297.000000,8.000000,264245.750000,77.000000,1516.500000,12964.229167
max,70.000000,199967.000000,49995.000000,900.000000,199885.000000,10.000000,390628.000000,90.000000,1800.000000,16663.916667

In [149]:
Age_median = df['Age'].median()
Age_median

df['Age'] = df['Age'].fillna(Age_median)
df['Age'] = df['Age'].astype("int")
df['Age']

Balance_median = df['Balance'].median()
Balance_median

df['Balance'] = df['Balance'].fillna(Balance_median)
df['Balance'] = df['Balance'].astype("int")
df['Balance']
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Customer_Status,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,58,49184.0,2139,581,112498,2,France,Male,Stay,161682.0,78,1162,4098.666667
1,65,162964.0,6197,732,6356,1,USA,Male,Churn,169320.0,85,1464,13580.333333
2,56,26956.0,37281,503,143203,8,Canada,Male,Stay,170159.0,76,1006,2246.333333
3,55,92926.0,925,463,139627,5,NaN,Male,Churn,232553.0,75,926,7743.833333
4,66,108236.0,7198,394,75985,5,UK,Other,Churn,184221.0,86,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465,5,Germany,Other,Stay,263196.0,54,1522,6810.916667
996,47,42475.0,1176,780,26640,5,France,Female,Stay,69115.0,67,1560,3539.583333
997,31,120531.0,46929,733,147220,4,India,Male,Stay,267751.0,51,1466,10044.250000
998,21,33661.0,22314,540,94186,5,NaN,Other,Stay,127847.0,41,1080,2805.083333
999,63,31930.0,851,559,100908,6,UK,Female,Stay,132838.0,83,1118,2660.833333

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 1000 non-null   int64
 1   AnnualIncome        1000 non-null   float64
 2   Spending            1000 non-null   int64
 3   CreditScore         1000 non-null   int64
 4   Balance             1000 non-null   int64
 5   Tenure              1000 non-null   int64
 6   Geography           950 non-null    object
 7   Gender              950 non-null    object
 8   Customer_Status     1000 non-null   object
 9   NetWorth            1000 non-null   float64
 10  AgeAfterRetirement  1000 non-null   int64
 11  DoubleCreditScore   1000 non-null   int64
 12  IncomePerMonth      1000 non-null   float64
dtypes: float64(3), int64(7), object(3)
memory usage: 109.4+ KB

In [151]:
# Challenge 12 – Customer Classification
# Count
# Stay
# Churn
# Then
# Rename
# Target → Customer_Class
# Convert it into string.

df.value_counts("Customer_Status")

Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

In [152]:
df.rename(columns = {"Customer_Status":"Customer_Class"}, inplace = True)
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Customer_Class,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,58,49184.0,2139,581,112498,2,France,Male,Stay,161682.0,78,1162,4098.666667
1,65,162964.0,6197,732,6356,1,USA,Male,Churn,169320.0,85,1464,13580.333333
2,56,26956.0,37281,503,143203,8,Canada,Male,Stay,170159.0,76,1006,2246.333333
3,55,92926.0,925,463,139627,5,NaN,Male,Churn,232553.0,75,926,7743.833333
4,66,108236.0,7198,394,75985,5,UK,Other,Churn,184221.0,86,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465,5,Germany,Other,Stay,263196.0,54,1522,6810.916667
996,47,42475.0,1176,780,26640,5,France,Female,Stay,69115.0,67,1560,3539.583333
997,31,120531.0,46929,733,147220,4,India,Male,Stay,267751.0,51,1466,10044.250000
998,21,33661.0,22314,540,94186,5,NaN,Other,Stay,127847.0,41,1080,2805.083333
999,63,31930.0,851,559,100908,6,UK,Female,Stay,132838.0,83,1118,2660.833333

In [153]:
df['Customer_Class'] = df['Customer_Class'].astype("str")
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Customer_Class,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,58,49184.0,2139,581,112498,2,France,Male,Stay,161682.0,78,1162,4098.666667
1,65,162964.0,6197,732,6356,1,USA,Male,Churn,169320.0,85,1464,13580.333333
2,56,26956.0,37281,503,143203,8,Canada,Male,Stay,170159.0,76,1006,2246.333333
3,55,92926.0,925,463,139627,5,NaN,Male,Churn,232553.0,75,926,7743.833333
4,66,108236.0,7198,394,75985,5,UK,Other,Churn,184221.0,86,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465,5,Germany,Other,Stay,263196.0,54,1522,6810.916667
996,47,42475.0,1176,780,26640,5,France,Female,Stay,69115.0,67,1560,3539.583333
997,31,120531.0,46929,733,147220,4,India,Male,Stay,267751.0,51,1466,10044.250000
998,21,33661.0,22314,540,94186,5,NaN,Other,Stay,127847.0,41,1080,2805.083333
999,63,31930.0,851,559,100908,6,UK,Female,Stay,132838.0,83,1118,2660.833333

In [154]:
# Challenge 13 – Sales Department
# Rename
# Balance → AccountBalance
# AnnualIncome → Salary
# CreditScore → Score
# Add prefix
# Sales_
# Then
# Display
# sample(20)

df.rename(columns={"Balance":"AccountBalance",
                   "AnnualIncome":"Salary",
                   "CreditScore":"Score"},inplace = True)
df.add_prefix("Sales_")
df.sample(20)

,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Customer_Class,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
447,69,54207.0,22831,481,183756,5,India,Male,Churn,237963.0,89,962,4517.250000
30,46,164264.0,6916,351,130428,8,India,Male,Churn,294692.0,66,702,13688.666667
33,27,69780.0,19945,522,193741,9,France,Other,Stay,263521.0,47,1044,5815.000000
737,48,190280.0,25007,488,170425,7,Canada,Male,Churn,360705.0,68,976,15856.666667
834,42,107203.0,4436,564,191121,4,USA,Female,Stay,298324.0,62,1128,8933.583333
736,44,26837.0,24044,381,137628,7,USA,Other,Churn,164465.0,64,762,2236.416667
755,53,74430.0,3705,489,29651,10,UK,Male,Churn,104081.0,73,978,6202.500000
526,55,112358.0,37786,748,112498,6,UK,Other,Stay,224856.0,75,1496,9363.166667
965,70,142498.0,18059,845,161786,6,Germany,Other,Stay,304284.0,90,1690,11874.833333
692,47,187488.0,4478,669,111603,6,UK,Other,Stay,299091.0,67,1338,15624.000000
273,34,145587.0,14523,506,165590,4,Germany,Other,Stay,311177.0,54,1012,12132.250000
100,70,37129.0,26760,803,112498,10,France,Male,Churn,149627.0,90,1606,3094.083333
422,24,73790.0,35221,543,83963,0,USA,Other,Churn,157753.0,44,1086,6149.166667
696,67,187411.0,38285,666,134898,10,Canada,Male,Stay,322309.0,87,1332,15617.583333
794,31,174919.0,28755,745,113442,5,Germany,Other,Stay,288361.0,51,1490,14576.583333
900,69,168172.0,48245,752,67736,1,France,NaN,Churn,235908.0,89,1504,14014.333333
626,56,70993.0,30303,713,114981,4,USA,Female,Stay,185974.0,76,1426,5916.083333
560,57,193510.0,20236,802,157981,8,UK,Male,Stay,351491.0,77,1604,16125.833333
820,70,60409.0,33002,722,154073,3,France,Female,Stay,214482.0,90,1444,5034.083333
753,49,162475.0,876,805,47575,9,France,Female,Stay,210050.0,69,1610,13539.583333

In [155]:
# Challenge 14 – Interview Challenge
# Without creating another DataFrame,
# perform
# • remove duplicates
# • rename Target
# • fill missing values
# • convert Balance to float
# • display summary

df.drop_duplicates()

,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Customer_Class,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,58,49184.0,2139,581,112498,2,France,Male,Stay,161682.0,78,1162,4098.666667
1,65,162964.0,6197,732,6356,1,USA,Male,Churn,169320.0,85,1464,13580.333333
2,56,26956.0,37281,503,143203,8,Canada,Male,Stay,170159.0,76,1006,2246.333333
3,55,92926.0,925,463,139627,5,NaN,Male,Churn,232553.0,75,926,7743.833333
4,66,108236.0,7198,394,75985,5,UK,Other,Churn,184221.0,86,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465,5,Germany,Other,Stay,263196.0,54,1522,6810.916667
996,47,42475.0,1176,780,26640,5,France,Female,Stay,69115.0,67,1560,3539.583333
997,31,120531.0,46929,733,147220,4,India,Male,Stay,267751.0,51,1466,10044.250000
998,21,33661.0,22314,540,94186,5,NaN,Other,Stay,127847.0,41,1080,2805.083333
999,63,31930.0,851,559,100908,6,UK,Female,Stay,132838.0,83,1118,2660.833333

In [156]:
df['AccountBalance'] = df['AccountBalance'].astype("float")
df

,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Customer_Class,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,58,49184.0,2139,581,112498.0,2,France,Male,Stay,161682.0,78,1162,4098.666667
1,65,162964.0,6197,732,6356.0,1,USA,Male,Churn,169320.0,85,1464,13580.333333
2,56,26956.0,37281,503,143203.0,8,Canada,Male,Stay,170159.0,76,1006,2246.333333
3,55,92926.0,925,463,139627.0,5,NaN,Male,Churn,232553.0,75,926,7743.833333
4,66,108236.0,7198,394,75985.0,5,UK,Other,Churn,184221.0,86,788,9019.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465.0,5,Germany,Other,Stay,263196.0,54,1522,6810.916667
996,47,42475.0,1176,780,26640.0,5,France,Female,Stay,69115.0,67,1560,3539.583333
997,31,120531.0,46929,733,147220.0,4,India,Male,Stay,267751.0,51,1466,10044.250000
998,21,33661.0,22314,540,94186.0,5,NaN,Other,Stay,127847.0,41,1080,2805.083333
999,63,31930.0,851,559,100908.0,6,UK,Female,Stay,132838.0,83,1118,2660.833333

In [175]:
# Challenge 15 – Data Engineer Task
# Load the dataset.
# Create another DataFrame containing only numeric columns.
# Drop
# CustomerID
# Target
# Display summary.

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [158]:
df1=df.describe()
df1

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [159]:
df.drop("CustomerID",axis = 1)
df.drop("Target",axis = 1)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [160]:
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [161]:
# Challenge 16 – Mixed Cleaning
# Perform
# drop_duplicates()
# fillna()
# astype()
# rename()
# head()
# info()
# using only one DataFrame variable.

df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [163]:
Age_median = df['Age'].median()
Age_median

df['Age'] = df['Age'].fillna(Age_median)
df['Age'] = df['Age'].astype("int")
df['Age']

0       58
1       65
2       56
3       55
4       66
        ..
1015    43
1016    25
1017    49
1018    38
1019    62
Name: Age, Length: 1020, dtype: int64

In [164]:
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [165]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB

In [181]:
# Challenge 17 – Real Company Dataset
# Manager asks
# Remove duplicate records
# Fill missing values
# Rename all business columns
# Add company prefix
# Display summary
# Display target counts


df.rename(columns={
    "Surname": "CustomerName",
    "Geography": "Country",
    "Gender": "CustomerGender",
    "Exited": "Target"},inplace = True)

df.add_prefix("Em_")
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [180]:
df.value_counts("Target")

Target
Churn    515
Stay     505
Name: count, dtype: int64

In [182]:
# Challenge 18 – Customer Summary
# Generate
# Mean Balance
# Median Balance
# Mean Age
# Median AnnualIncome
# Then
# fill missing values using these statistics.

mean_balance = df["Balance"].mean()
median_balance = df["Balance"].median()

mean_age = df["Age"].mean()

median_income = df["AnnualIncome"].median()

print("Mean Balance:", mean_balance)
print("Median Balance:", median_balance)
print("Mean Age:", mean_age)
print("Median AnnualIncome:", median_income)

Mean Balance: 97523.53566563467
Median Balance: 95100.06
Mean Age: 44.24948453608248
Median AnnualIncome: 112358.0

In [184]:
df["Balance"] = df["Balance"].fillna(mean_balance)
df["Age"] = df["Age"].fillna(mean_age)
df["AnnualIncome"] = df["AnnualIncome"].fillna(median_income)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Segment,Target
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,112358.0,10424,722,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn

In [185]:
df.isnull().sum()

CustomerID         0
Age                0
AnnualIncome       0
Spending           0
CreditScore        0
Balance            0
Tenure             0
Country           51
CustomerGender    52
Segment           51
Target             0
dtype: int64

In [187]:
# Challenge 19 – Transformation Challenge
# Create
# Income_in_Lakhs
# Balance_in_Lakhs
# SeniorCitizen
# HighCreditScore
# where
# SeniorCitizen = Age + 0
# HighCreditScore = CreditScore * 1
# (No conditional statements.)

df["Income_in_Lakhs"] = df["AnnualIncome"] / 100000
df["Balance_in_Lakhs"] = df["Balance"] / 100000
df["SeniorCitizen"] = df["Age"] + 0
df["HighCreditScore"] = df["CreditScore"] * 1
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Segment,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,0.49184,0.975235,58.0,581
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,1.62964,0.063565,65.0,732
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,0.26956,1.432039,56.0,503
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,0.92926,1.396279,55.0,463
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,1.08236,0.759855,66.0,394

# Challenge 20 – Final Interview Project
Your manager gives you a dirty customer dataset.
Prepare the final dataset.
Requirements
Load dataset
Check information
Find missing values
Remove duplicates
Rename
CustomerID
AnnualIncome
CreditScore
Target

Convert
Age

Sumit Sir Notes
AnnualIncome
Balance

Fill missing values
Remove
Segment
CustomerID
Create new columns
TotalMoney = Balance + AnnualIncome
AgeAfter5Years = Age + 5
MonthlyIncome = AnnualIncome / 12
CreditScoreDouble = CreditScore * 2Display
• Head
• Tail
• Sample
• Describe
• Target counts
• Final information

In [188]:
df = df.drop_duplicates()

df = df.rename(columns={
    "CustomerId": "CustomerID",
    "EstimatedSalary": "AnnualIncome",
    "Exited": "Target"})
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Segment,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,0.49184,0.975235,58.0,581
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,1.62964,0.063565,65.0,732
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,0.26956,1.432039,56.0,503
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,0.92926,1.396279,55.0,463
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,1.08236,0.759855,66.0,394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.650000,5,Germany,Other,SME,Stay,0.81731,1.814656,34.0,761
996,10997,47.0,42475.0,1176,780,26640.990000,5,France,Female,SME,Stay,0.42475,0.266410,47.0,780
997,10998,31.0,120531.0,46929,733,147220.820000,4,India,Male,SME,Stay,1.20531,1.472208,31.0,733
998,10999,21.0,33661.0,22314,540,94186.480000,5,NaN,Other,SME,Stay,0.33661,0.941865,21.0,540
999,11000,63.0,31930.0,851,559,100908.400000,6,UK,Female,NaN,Stay,0.31930,1.009084,63.0,559

In [202]:
df["Age"] = df["Age"].astype(int)
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,58,49184.0,2139,581,97523.535666,2,France,Male,Stay,0.49184,0.975235,58.0,581,146707.535666,63,4098.666667,1162
1,65,162964.0,6197,732,6356.540000,1,USA,Male,Churn,1.62964,0.063565,65.0,732,169320.540000,70,13580.333333,1464
2,56,26956.0,37281,503,143203.920000,8,Canada,Male,Stay,0.26956,1.432039,56.0,503,170159.920000,61,2246.333333,1006
3,55,92926.0,925,463,139627.880000,5,NaN,Male,Churn,0.92926,1.396279,55.0,463,232553.880000,60,7743.833333,926
4,66,108236.0,7198,394,75985.460000,5,UK,Other,Churn,1.08236,0.759855,66.0,394,184221.460000,71,9019.666667,788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465.650000,5,Germany,Other,Stay,0.81731,1.814656,34.0,761,263196.650000,39,6810.916667,1522
996,47,42475.0,1176,780,26640.990000,5,France,Female,Stay,0.42475,0.266410,47.0,780,69115.990000,52,3539.583333,1560
997,31,120531.0,46929,733,147220.820000,4,India,Male,Stay,1.20531,1.472208,31.0,733,267751.820000,36,10044.250000,1466
998,21,33661.0,22314,540,94186.480000,5,NaN,Other,Stay,0.33661,0.941865,21.0,540,127847.480000,26,2805.083333,1080
999,63,31930.0,851,559,100908.400000,6,UK,Female,Stay,0.31930,1.009084,63.0,559,132838.400000,68,2660.833333,1118

In [201]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].mean())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["CreditScore"] = df["CreditScore"].fillna(df["CreditScore"].mean())
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,58,49184.0,2139,581,97523.535666,2,France,Male,Stay,0.49184,0.975235,58.0,581,146707.535666,63,4098.666667,1162
1,65,162964.0,6197,732,6356.540000,1,USA,Male,Churn,1.62964,0.063565,65.0,732,169320.540000,70,13580.333333,1464
2,56,26956.0,37281,503,143203.920000,8,Canada,Male,Stay,0.26956,1.432039,56.0,503,170159.920000,61,2246.333333,1006
3,55,92926.0,925,463,139627.880000,5,NaN,Male,Churn,0.92926,1.396279,55.0,463,232553.880000,60,7743.833333,926
4,66,108236.0,7198,394,75985.460000,5,UK,Other,Churn,1.08236,0.759855,66.0,394,184221.460000,71,9019.666667,788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465.650000,5,Germany,Other,Stay,0.81731,1.814656,34.0,761,263196.650000,39,6810.916667,1522
996,47,42475.0,1176,780,26640.990000,5,France,Female,Stay,0.42475,0.266410,47.0,780,69115.990000,52,3539.583333,1560
997,31,120531.0,46929,733,147220.820000,4,India,Male,Stay,1.20531,1.472208,31.0,733,267751.820000,36,10044.250000,1466
998,21,33661.0,22314,540,94186.480000,5,NaN,Other,Stay,0.33661,0.941865,21.0,540,127847.480000,26,2805.083333,1080
999,63,31930.0,851,559,100908.400000,6,UK,Female,Stay,0.31930,1.009084,63.0,559,132838.400000,68,2660.833333,1118

In [200]:
df = df.drop(columns=["Segment", "CustomerID"], errors="ignore")
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,58,49184.0,2139,581,97523.535666,2,France,Male,Stay,0.49184,0.975235,58.0,581,146707.535666,63,4098.666667,1162
1,65,162964.0,6197,732,6356.540000,1,USA,Male,Churn,1.62964,0.063565,65.0,732,169320.540000,70,13580.333333,1464
2,56,26956.0,37281,503,143203.920000,8,Canada,Male,Stay,0.26956,1.432039,56.0,503,170159.920000,61,2246.333333,1006
3,55,92926.0,925,463,139627.880000,5,NaN,Male,Churn,0.92926,1.396279,55.0,463,232553.880000,60,7743.833333,926
4,66,108236.0,7198,394,75985.460000,5,UK,Other,Churn,1.08236,0.759855,66.0,394,184221.460000,71,9019.666667,788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465.650000,5,Germany,Other,Stay,0.81731,1.814656,34.0,761,263196.650000,39,6810.916667,1522
996,47,42475.0,1176,780,26640.990000,5,France,Female,Stay,0.42475,0.266410,47.0,780,69115.990000,52,3539.583333,1560
997,31,120531.0,46929,733,147220.820000,4,India,Male,Stay,1.20531,1.472208,31.0,733,267751.820000,36,10044.250000,1466
998,21,33661.0,22314,540,94186.480000,5,NaN,Other,Stay,0.33661,0.941865,21.0,540,127847.480000,26,2805.083333,1080
999,63,31930.0,851,559,100908.400000,6,UK,Female,Stay,0.31930,1.009084,63.0,559,132838.400000,68,2660.833333,1118

In [199]:
df["TotalMoney"] = df["Balance"] + df["AnnualIncome"]
df["AgeAfter5Years"] = df["Age"] + 5
df["MonthlyIncome"] = df["AnnualIncome"] / 12
df["CreditScoreDouble"] = df["CreditScore"] * 2
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,58,49184.0,2139,581,97523.535666,2,France,Male,Stay,0.49184,0.975235,58.0,581,146707.535666,63,4098.666667,1162
1,65,162964.0,6197,732,6356.540000,1,USA,Male,Churn,1.62964,0.063565,65.0,732,169320.540000,70,13580.333333,1464
2,56,26956.0,37281,503,143203.920000,8,Canada,Male,Stay,0.26956,1.432039,56.0,503,170159.920000,61,2246.333333,1006
3,55,92926.0,925,463,139627.880000,5,NaN,Male,Churn,0.92926,1.396279,55.0,463,232553.880000,60,7743.833333,926
4,66,108236.0,7198,394,75985.460000,5,UK,Other,Churn,1.08236,0.759855,66.0,394,184221.460000,71,9019.666667,788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,81731.0,40980,761,181465.650000,5,Germany,Other,Stay,0.81731,1.814656,34.0,761,263196.650000,39,6810.916667,1522
996,47,42475.0,1176,780,26640.990000,5,France,Female,Stay,0.42475,0.266410,47.0,780,69115.990000,52,3539.583333,1560
997,31,120531.0,46929,733,147220.820000,4,India,Male,Stay,1.20531,1.472208,31.0,733,267751.820000,36,10044.250000,1466
998,21,33661.0,22314,540,94186.480000,5,NaN,Other,Stay,0.33661,0.941865,21.0,540,127847.480000,26,2805.083333,1080
999,63,31930.0,851,559,100908.400000,6,UK,Female,Stay,0.31930,1.009084,63.0,559,132838.400000,68,2660.833333,1118

In [193]:
df.head()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,58,49184.0,2139,581,97523.535666,2,France,Male,Stay,0.49184,0.975235,58.0,581,146707.535666,63,4098.666667,1162
1,65,162964.0,6197,732,6356.540000,1,USA,Male,Churn,1.62964,0.063565,65.0,732,169320.540000,70,13580.333333,1464
2,56,26956.0,37281,503,143203.920000,8,Canada,Male,Stay,0.26956,1.432039,56.0,503,170159.920000,61,2246.333333,1006
3,55,92926.0,925,463,139627.880000,5,NaN,Male,Churn,0.92926,1.396279,55.0,463,232553.880000,60,7743.833333,926
4,66,108236.0,7198,394,75985.460000,5,UK,Other,Churn,1.08236,0.759855,66.0,394,184221.460000,71,9019.666667,788

In [194]:
df.tail()

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
995,34,81731.0,40980,761,181465.65,5,Germany,Other,Stay,0.81731,1.814656,34.0,761,263196.65,39,6810.916667,1522
996,47,42475.0,1176,780,26640.99,5,France,Female,Stay,0.42475,0.266410,47.0,780,69115.99,52,3539.583333,1560
997,31,120531.0,46929,733,147220.82,4,India,Male,Stay,1.20531,1.472208,31.0,733,267751.82,36,10044.250000,1466
998,21,33661.0,22314,540,94186.48,5,NaN,Other,Stay,0.33661,0.941865,21.0,540,127847.48,26,2805.083333,1080
999,63,31930.0,851,559,100908.40,6,UK,Female,Stay,0.31930,1.009084,63.0,559,132838.40,68,2660.833333,1118

In [195]:
df.sample(5)

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
624,60,123584.0,27071,900,40062.080000,0,France,Other,Churn,1.23584,0.400621,60.000000,900,163646.080000,65,10298.666667,1800
961,44,171569.0,6708,644,54672.990000,9,Germany,Female,Stay,1.71569,0.546730,44.249485,644,226241.990000,49,14297.416667,1288
986,30,184704.0,20524,621,115161.870000,1,USA,Male,Churn,1.84704,1.151619,30.000000,621,299865.870000,35,15392.000000,1242
465,23,188261.0,36159,696,97523.535666,6,UK,Male,Stay,1.88261,0.975235,23.000000,696,285784.535666,28,15688.416667,1392
265,27,112358.0,16372,332,114514.050000,1,USA,Male,Churn,1.12358,1.145141,27.000000,332,226872.050000,32,9363.166667,664

In [196]:
df.describe(include="all")

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Country,CustomerGender,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,950,950,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,6,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,India,Other,Churn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,166,330,506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,44.202000,112453.288000,25285.558000,603.088000,97555.864273,5.241000,NaN,NaN,NaN,1.124533,0.975559,44.214474,603.088000,210009.152273,49.202000,9371.107333,1206.176000
std,15.130834,51081.479931,14211.735656,176.605486,54430.062511,3.179155,NaN,NaN,NaN,0.510815,0.544301,15.130765,176.605486,73150.826517,15.130834,4256.789994,353.210972
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,NaN,NaN,NaN,0.202270,0.005476,18.000000,300.000000,33432.390000,23.000000,1685.583333,600.000000
25%,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000,NaN,NaN,NaN,0.684373,0.520742,31.000000,441.000000,156611.867500,36.000000,5703.104167,882.000000
50%,44.000000,112358.000000,24901.000000,606.500000,97523.535666,5.000000,NaN,NaN,NaN,1.123580,0.975235,44.249485,606.500000,209905.132833,49.000000,9363.166667,1213.000000
75%,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000,NaN,NaN,NaN,1.555708,1.422979,57.000000,758.250000,263534.286416,62.000000,12964.229167,1516.500000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,NaN,NaN,NaN,1.999670,1.998859,70.000000,900.000000,390628.400000,75.000000,16663.916667,1800.000000

In [197]:
df["Target"].value_counts()

Target
Churn    506
Stay     494
Name: count, dtype: int64

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   AnnualIncome       1000 non-null   float64
 2   Spending           1000 non-null   int64
 3   CreditScore        1000 non-null   int64
 4   Balance            1000 non-null   float64
 5   Tenure             1000 non-null   int64
 6   Country            950 non-null    object
 7   CustomerGender     950 non-null    object
 8   Target             1000 non-null   object
 9   Income_in_Lakhs    1000 non-null   float64
 10  Balance_in_Lakhs   1000 non-null   float64
 11  SeniorCitizen      1000 non-null   float64
 12  HighCreditScore    1000 non-null   int64
 13  TotalMoney         1000 non-null   float64
 14  AgeAfter5Years     1000 non-null   int64
 15  MonthlyIncome      1000 non-null   float64
 16  CreditScoreDouble  1000 non-null   int64
dtypes: float64(7), int64(7), object(3)
memory usage: 140.6+ KB