In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\pkl\\fifa_19.csv", encoding="latin1")
df

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31.0,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94.0,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226.5M
1,1,20801,Cristiano Ronaldo,33.0,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94.0,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127.1M
2,2,190871,Neymar Jr,26.0,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92.0,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228.1M
3,3,193080,De Gea,27.0,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91.0,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,138.6M
4,4,192985,K. De Bruyne,27.0,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91.0,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19.0,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47.0,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,143K
18203,18203,243165,N. Christoffersson,19.0,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47.0,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,113K
18204,18204,241638,B. Worman,16.0,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47.0,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,165K
18205,18205,246268,D. Walker-Rice,17.0,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47.0,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,143K
18206,18206,246269,G. Nugent,16.0,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46.0,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,165K

In [2]:
# checking the info of dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 89 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18207 non-null  int64
 1   ID                        18207 non-null  int64
 2   Name                      18207 non-null  object
 3   Age                       18206 non-null  float64
 4   Photo                     18207 non-null  object
 5   Nationality               18207 non-null  object
 6   Flag                      18207 non-null  object
 7   Overall                   18206 non-null  float64
 8   Potential                 18207 non-null  int64
 9   Club                      17966 non-null  object
 10  Club Logo                 18207 non-null  object
 11  Value                     18207 non-null  object
 12  Wage                      18207 non-null  object
 13  Special                   18207 non-null  int64
 14  Preferred Foot            18159 non-null  object
 15  International Reputation  18159 non-null  float64
 16  Weak Foot                 18159 non-null  float64
 17  Skill Moves               18159 non-null  float64
 18  Work Rate                 18159 non-null  object
 19  Body Type                 18159 non-null  object
 20  Real Face                 18159 non-null  object
 21  Position                  18147 non-null  object
 22  Jersey Number             18147 non-null  float64
 23  Joined                    16654 non-null  object
 24  Loaned From               1264 non-null   object
 25  Contract Valid Until      17918 non-null  object
 26  Height                    18159 non-null  object
 27  Weight                    18159 non-null  object
 28  LS                        16122 non-null  object
 29  ST                        16122 non-null  object
 30  RS                        16122 non-null  object
 31  LW                        16122 non-null  object
 32  LF                        16122 non-null  object
 33  CF                        16122 non-null  object
 34  RF                        16122 non-null  object
 35  RW                        16122 non-null  object
 36  LAM                       16122 non-null  object
 37  CAM                       16122 non-null  object
 38  RAM                       16122 non-null  object
 39  LM                        16122 non-null  object
 40  LCM                       16122 non-null  object
 41  CM                        16122 non-null  object
 42  RCM                       16122 non-null  object
 43  RM                        16122 non-null  object
 44  LWB                       16122 non-null  object
 45  LDM                       16122 non-null  object
 46  CDM                       16122 non-null  object
 47  RDM                       16122 non-null  object
 48  RWB                       16122 non-null  object
 49  LB                        16122 non-null  object
 50  LCB                       16122 non-null  object
 51  CB                        16122 non-null  object
 52  RCB                       16122 non-null  object
 53  RB                        16122 non-null  object
 54  Crossing                  18159 non-null  float64
 55  Finishing                 18159 non-null  float64
 56  HeadingAccuracy           18159 non-null  float64
 57  ShortPassing              18159 non-null  float64
 58  Volleys                   18159 non-null  float64
 59  Dribbling                 18159 non-null  float64
 60  Curve                     18159 non-null  float64
 61  FKAccuracy                18159 non-null  float64
 62  LongPassing               18159 non-null  float64
 63  BallControl               18159 non-null  float64
 64  Acceleration              18159 non-null  float64
 65  SprintSpeed               18159 non-null  float64
 66  Agility                   18159 non-null  float64
 67  Reactions                 18159 non-null  float64
 68  Balance                   18159 non-null  float64
 69  ShotPower                 18159 non-null  float64
 70  Jumping                   18159 non-null  float64
 71  Stamina                   18159 non-null  float64
 72  Strength                  18159 non-null  float64
 73  LongShots                 18159 non-null  float64
 74  Aggression                18159 non-null  float64
 75  Interceptions             18159 non-null  float64
 76  Positioning               18159 non-null  float64
 77  Vision                    18159 non-null  float64
 78  Penalties                 18159 non-null  float64
 79  Composure                 18159 non-null  float64
 80  Marking                   18159 non-null  float64
 81  StandingTackle            18159 non-null  float64
 82  SlidingTackle             18159 non-null  float64
 83  GKDiving                  18159 non-null  float64
 84  GKHandling                18159 non-null  float64
 85  GKKicking                 18159 non-null  float64
 86  GKPositioning             18159 non-null  float64
 87  GKReflexes                18159 non-null  float64
 88  Release Clause            16643 non-null  object
dtypes: float64(40), int64(4), object(45)
memory usage: 12.4+ MB

In [3]:
# checking duplicates values

df.duplicated().sum()

np.int64(0)

In [4]:
df=df.drop("Unnamed: 0", axis = 1)

In [5]:
# sorting

df = df.sort_values("ID", ascending=True).reset_index(drop=True)

In [6]:
df

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,16,Luis García,37.0,https://cdn.sofifa.org/players/4/19/16.png,Spain,https://cdn.sofifa.org/flags/45.png,71.0,71,KAS Eupen,https://cdn.sofifa.org/teams/2/light/2013.png,...,79.0,70.0,43.0,40.0,9.0,12.0,13.0,11.0,11.0,1.1M
1,41,Iniesta,34.0,https://cdn.sofifa.org/players/4/19/41.png,Spain,https://cdn.sofifa.org/flags/45.png,86.0,86,Vissel Kobe,https://cdn.sofifa.org/teams/2/light/101146.png,...,89.0,67.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0,26.9M
2,80,E. Belözo?lu,37.0,https://cdn.sofifa.org/players/4/19/80.png,Turkey,https://cdn.sofifa.org/flags/48.png,79.0,79,Medipol Ba?ak?ehir FK,https://cdn.sofifa.org/teams/2/light/101014.png,...,80.0,65.0,67.0,60.0,7.0,11.0,7.0,14.0,8.0,7.6M
3,164,G. Pinzi,37.0,https://cdn.sofifa.org/players/4/19/164.png,Italy,https://cdn.sofifa.org/flags/27.png,70.0,70,Padova,https://cdn.sofifa.org/teams/2/light/110912.png,...,68.0,74.0,71.0,66.0,5.0,15.0,7.0,6.0,13.0,372K
4,657,D. Vaughan,35.0,https://cdn.sofifa.org/players/4/19/657.png,Wales,https://cdn.sofifa.org/flags/50.png,66.0,66,Notts County,https://cdn.sofifa.org/teams/2/light/1937.png,...,82.0,59.0,66.0,62.0,6.0,9.0,10.0,9.0,7.0,263K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,246609,J. Requena,19.0,https://cdn.sofifa.org/players/4/19/246609.png,Argentina,https://cdn.sofifa.org/flags/52.png,57.0,72,Newell's Old Boys,https://cdn.sofifa.org/teams/2/light/110396.png,...,58.0,57.0,53.0,58.0,11.0,7.0,6.0,12.0,11.0,468K
18203,246613,J. Zwarts,19.0,https://cdn.sofifa.org/players/4/19/246613.png,Netherlands,https://cdn.sofifa.org/flags/34.png,62.0,77,Feyenoord,https://cdn.sofifa.org/teams/2/light/246.png,...,51.0,18.0,22.0,17.0,8.0,12.0,8.0,7.0,6.0,1.3M
18204,246616,José Uche,18.0,https://cdn.sofifa.org/players/4/19/246616.png,Spain,https://cdn.sofifa.org/flags/45.png,58.0,69,SD Huesca,https://cdn.sofifa.org/teams/2/light/110839.png,...,43.0,59.0,57.0,48.0,13.0,12.0,9.0,14.0,7.0,432K
18205,246617,Javi Mier,19.0,https://cdn.sofifa.org/players/4/19/246617.png,Spain,https://cdn.sofifa.org/flags/45.png,62.0,76,Real Oviedo,https://cdn.sofifa.org/teams/2/light/110827.png,...,55.0,35.0,48.0,42.0,11.0,7.0,11.0,10.0,7.0,1.4M
18206,246620,E. McCue,17.0,https://cdn.sofifa.org/players/4/19/246620.png,Sweden,https://cdn.sofifa.org/flags/46.png,51.0,74,Houston Dynamo,https://cdn.sofifa.org/teams/2/light/698.png,...,49.0,49.0,49.0,46.0,9.0,13.0,11.0,15.0,10.0,175K

In [7]:
# checkiing missing val in name col

df["Name"].isna().sum()

np.int64(0)

In [8]:
# checking duplicate val in name col

df["Name"].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
18202     True
18203    False
18204    False
18205    False
18206    False
Name: Name, Length: 18207, dtype: bool

In [9]:
df[df["Name"].duplicated()]

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
249,135218,D. Perquis,34.0,https://cdn.sofifa.org/players/4/19/135218.png,Poland,https://cdn.sofifa.org/flags/37.png,64.0,64,GFC Ajaccio,https://cdn.sofifa.org/teams/2/light/110316.png,...,64.0,62.0,60.0,61.0,6.0,12.0,16.0,10.0,16.0,245K
357,140029,O. Pérez,45.0,https://cdn.sofifa.org/players/4/19/140029.png,Mexico,https://cdn.sofifa.org/flags/83.png,71.0,71,Pachuca,https://cdn.sofifa.org/teams/2/light/110147.png,...,62.0,23.0,12.0,11.0,70.0,64.0,65.0,73.0,74.0,272K
427,143745,A. Turan,31.0,https://cdn.sofifa.org/players/4/19/143745.png,Turkey,https://cdn.sofifa.org/flags/48.png,77.0,77,Medipol Ba?ak?ehir FK,https://cdn.sofifa.org/teams/2/light/101014.png,...,79.0,69.0,63.0,60.0,11.0,7.0,11.0,12.0,11.0,NaN
534,152456,S. Brown,33.0,https://cdn.sofifa.org/players/4/19/152456.png,England,https://cdn.sofifa.org/flags/14.png,65.0,65,Port Vale,https://cdn.sofifa.org/teams/2/light/1928.png,...,60.0,22.0,12.0,17.0,65.0,63.0,60.0,65.0,63.0,473K
538,152501,S. Brown,33.0,https://cdn.sofifa.org/players/4/19/152501.png,England,https://cdn.sofifa.org/flags/14.png,64.0,64,Accrington Stanley,https://cdn.sofifa.org/teams/2/light/110313.png,...,61.0,61.0,58.0,60.0,12.0,6.0,11.0,9.0,7.0,473K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18174,246448,R. Campbell,18.0,https://cdn.sofifa.org/players/4/19/246448.png,England,https://cdn.sofifa.org/flags/14.png,54.0,65,Gillingham,https://cdn.sofifa.org/teams/2/light/1802.png,...,47.0,18.0,15.0,21.0,9.0,9.0,13.0,6.0,12.0,215K
18184,246465,Guerrero,16.0,https://cdn.sofifa.org/players/4/19/246465.png,Spain,https://cdn.sofifa.org/flags/45.png,63.0,76,CF Rayo Majadahonda,https://cdn.sofifa.org/teams/2/light/110066.png,...,55.0,56.0,64.0,58.0,6.0,5.0,10.0,6.0,14.0,1.4M
18196,246600,K. Taylor,17.0,https://cdn.sofifa.org/players/4/19/246600.png,England,https://cdn.sofifa.org/flags/14.png,48.0,63,Shrewsbury,https://cdn.sofifa.org/teams/2/light/127.png,...,42.0,45.0,45.0,42.0,10.0,5.0,8.0,7.0,8.0,143K
18200,246606,Fran García,18.0,https://cdn.sofifa.org/players/4/19/246606.png,Spain,https://cdn.sofifa.org/flags/45.png,64.0,79,Real Madrid,https://cdn.sofifa.org/teams/2/light/243.png,...,60.0,60.0,58.0,59.0,9.0,6.0,12.0,9.0,11.0,2.2M
18202,246609,J. Requena,19.0,https://cdn.sofifa.org/players/4/19/246609.png,Argentina,https://cdn.sofifa.org/flags/52.png,57.0,72,Newell's Old Boys,https://cdn.sofifa.org/teams/2/light/110396.png,...,58.0,57.0,53.0,58.0,11.0,7.0,6.0,12.0,11.0,468K

In [10]:
# droping duplicates from name col

df = df.drop_duplicates(subset=["Name"], keep="first")

In [11]:
df["Name"].duplicated().sum()

np.int64(0)

In [12]:
df = df.sort_values("ID", ascending=True).reset_index(drop=True)

In [13]:
df

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,16,Luis García,37.0,https://cdn.sofifa.org/players/4/19/16.png,Spain,https://cdn.sofifa.org/flags/45.png,71.0,71,KAS Eupen,https://cdn.sofifa.org/teams/2/light/2013.png,...,79.0,70.0,43.0,40.0,9.0,12.0,13.0,11.0,11.0,1.1M
1,41,Iniesta,34.0,https://cdn.sofifa.org/players/4/19/41.png,Spain,https://cdn.sofifa.org/flags/45.png,86.0,86,Vissel Kobe,https://cdn.sofifa.org/teams/2/light/101146.png,...,89.0,67.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0,26.9M
2,80,E. Belözo?lu,37.0,https://cdn.sofifa.org/players/4/19/80.png,Turkey,https://cdn.sofifa.org/flags/48.png,79.0,79,Medipol Ba?ak?ehir FK,https://cdn.sofifa.org/teams/2/light/101014.png,...,80.0,65.0,67.0,60.0,7.0,11.0,7.0,14.0,8.0,7.6M
3,164,G. Pinzi,37.0,https://cdn.sofifa.org/players/4/19/164.png,Italy,https://cdn.sofifa.org/flags/27.png,70.0,70,Padova,https://cdn.sofifa.org/teams/2/light/110912.png,...,68.0,74.0,71.0,66.0,5.0,15.0,7.0,6.0,13.0,372K
4,657,D. Vaughan,35.0,https://cdn.sofifa.org/players/4/19/657.png,Wales,https://cdn.sofifa.org/flags/50.png,66.0,66,Notts County,https://cdn.sofifa.org/teams/2/light/1937.png,...,82.0,59.0,66.0,62.0,6.0,9.0,10.0,9.0,7.0,263K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17189,246608,Fidalgo,21.0,https://cdn.sofifa.org/players/4/19/246608.png,Spain,https://cdn.sofifa.org/flags/45.png,65.0,75,Real Madrid,https://cdn.sofifa.org/teams/2/light/243.png,...,68.0,46.0,51.0,47.0,10.0,9.0,10.0,11.0,9.0,2M
17190,246613,J. Zwarts,19.0,https://cdn.sofifa.org/players/4/19/246613.png,Netherlands,https://cdn.sofifa.org/flags/34.png,62.0,77,Feyenoord,https://cdn.sofifa.org/teams/2/light/246.png,...,51.0,18.0,22.0,17.0,8.0,12.0,8.0,7.0,6.0,1.3M
17191,246616,José Uche,18.0,https://cdn.sofifa.org/players/4/19/246616.png,Spain,https://cdn.sofifa.org/flags/45.png,58.0,69,SD Huesca,https://cdn.sofifa.org/teams/2/light/110839.png,...,43.0,59.0,57.0,48.0,13.0,12.0,9.0,14.0,7.0,432K
17192,246617,Javi Mier,19.0,https://cdn.sofifa.org/players/4/19/246617.png,Spain,https://cdn.sofifa.org/flags/45.png,62.0,76,Real Oviedo,https://cdn.sofifa.org/teams/2/light/110827.png,...,55.0,35.0,48.0,42.0,11.0,7.0,11.0,10.0,7.0,1.4M
17193,246620,E. McCue,17.0,https://cdn.sofifa.org/players/4/19/246620.png,Sweden,https://cdn.sofifa.org/flags/46.png,51.0,74,Houston Dynamo,https://cdn.sofifa.org/teams/2/light/698.png,...,49.0,49.0,49.0,46.0,9.0,13.0,11.0,15.0,10.0,175K

## clearing Age col

In [14]:
df["Age"].value_counts()

Age
26.0    1328
21.0    1324
24.0    1286
22.0    1239
25.0    1238
23.0    1225
20.0    1149
27.0    1113
28.0    1060
19.0     944
29.0     923
30.0     877
31.0     688
18.0     666
32.0     558
34.0     398
33.0     395
17.0     263
35.0     192
36.0     125
37.0      82
38.0      37
16.0      37
39.0      25
40.0      13
41.0       5
44.0       2
42.0       1
Name: count, dtype: int64

In [15]:
df["Age"].unique()

array([37., 34., 35., 33., 40., 38., 39., 41., 36., 32., 44., 31., 27.,
       28., 30., 42., 26., 25., 29., 21., nan, 24., 23., 20., 22., 19.,
       18., 17., 16.])

In [16]:
df = df.dropna(subset=["Age"])

In [17]:
df

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,16,Luis García,37.0,https://cdn.sofifa.org/players/4/19/16.png,Spain,https://cdn.sofifa.org/flags/45.png,71.0,71,KAS Eupen,https://cdn.sofifa.org/teams/2/light/2013.png,...,79.0,70.0,43.0,40.0,9.0,12.0,13.0,11.0,11.0,1.1M
1,41,Iniesta,34.0,https://cdn.sofifa.org/players/4/19/41.png,Spain,https://cdn.sofifa.org/flags/45.png,86.0,86,Vissel Kobe,https://cdn.sofifa.org/teams/2/light/101146.png,...,89.0,67.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0,26.9M
2,80,E. Belözo?lu,37.0,https://cdn.sofifa.org/players/4/19/80.png,Turkey,https://cdn.sofifa.org/flags/48.png,79.0,79,Medipol Ba?ak?ehir FK,https://cdn.sofifa.org/teams/2/light/101014.png,...,80.0,65.0,67.0,60.0,7.0,11.0,7.0,14.0,8.0,7.6M
3,164,G. Pinzi,37.0,https://cdn.sofifa.org/players/4/19/164.png,Italy,https://cdn.sofifa.org/flags/27.png,70.0,70,Padova,https://cdn.sofifa.org/teams/2/light/110912.png,...,68.0,74.0,71.0,66.0,5.0,15.0,7.0,6.0,13.0,372K
4,657,D. Vaughan,35.0,https://cdn.sofifa.org/players/4/19/657.png,Wales,https://cdn.sofifa.org/flags/50.png,66.0,66,Notts County,https://cdn.sofifa.org/teams/2/light/1937.png,...,82.0,59.0,66.0,62.0,6.0,9.0,10.0,9.0,7.0,263K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17189,246608,Fidalgo,21.0,https://cdn.sofifa.org/players/4/19/246608.png,Spain,https://cdn.sofifa.org/flags/45.png,65.0,75,Real Madrid,https://cdn.sofifa.org/teams/2/light/243.png,...,68.0,46.0,51.0,47.0,10.0,9.0,10.0,11.0,9.0,2M
17190,246613,J. Zwarts,19.0,https://cdn.sofifa.org/players/4/19/246613.png,Netherlands,https://cdn.sofifa.org/flags/34.png,62.0,77,Feyenoord,https://cdn.sofifa.org/teams/2/light/246.png,...,51.0,18.0,22.0,17.0,8.0,12.0,8.0,7.0,6.0,1.3M
17191,246616,José Uche,18.0,https://cdn.sofifa.org/players/4/19/246616.png,Spain,https://cdn.sofifa.org/flags/45.png,58.0,69,SD Huesca,https://cdn.sofifa.org/teams/2/light/110839.png,...,43.0,59.0,57.0,48.0,13.0,12.0,9.0,14.0,7.0,432K
17192,246617,Javi Mier,19.0,https://cdn.sofifa.org/players/4/19/246617.png,Spain,https://cdn.sofifa.org/flags/45.png,62.0,76,Real Oviedo,https://cdn.sofifa.org/teams/2/light/110827.png,...,55.0,35.0,48.0,42.0,11.0,7.0,11.0,10.0,7.0,1.4M
17193,246620,E. McCue,17.0,https://cdn.sofifa.org/players/4/19/246620.png,Sweden,https://cdn.sofifa.org/flags/46.png,51.0,74,Houston Dynamo,https://cdn.sofifa.org/teams/2/light/698.png,...,49.0,49.0,49.0,46.0,9.0,13.0,11.0,15.0,10.0,175K

## Photo col cleaning

In [18]:
df.isna().sum()

ID                   0
Name                 0
Age                  0
Photo                0
Nationality          0
                  ...
GKHandling          46
GKKicking           46
GKPositioning       46
GKReflexes          46
Release Clause    1469
Length: 88, dtype: int64

In [19]:
df["Photo"].isna().sum()

np.int64(0)

In [20]:
df["Photo"].duplicated().sum()

np.int64(0)

## Nationality

In [21]:
Nationality_count = df["Nationality"].value_counts()

In [22]:
Nationality_count

Nationality
England          1521
Germany          1172
Spain            1013
France            880
Argentina         845
                 ...
Guam                1
New Caledonia       1
Mauritius           1
Andorra             1
Qatar               1
Name: count, Length: 163, dtype: int64

In [23]:
df["Nationality"].value_counts().to_string()

'Nationality\nEngland                 1521\nGermany                 1172\nSpain                   1013\nFrance                   880\nArgentina                845\nBrazil                   759\nItaly                    693\nColombia                 503\nJapan                    456\nNetherlands              449\nChina PR                 386\nSweden                   380\nChile                    352\nRepublic of Ireland      349\nPoland                   344\nNorway                   333\nKorea Republic           330\nSaudi Arabia             324\nDenmark                  321\nUnited States            319\nPortugal                 307\nMexico                   302\nAustria                  297\nTurkey                   291\nScotland                 266\nBelgium                  259\nAustralia                224\nSwitzerland              215\nUruguay                  134\nCroatia                  123\nSenegal                  123\nSerbia                   123\nNigeria                  116\nWales                    115\nGhana                    112\nGreece                   102\nCzech Republic            99\nIvory Coast               91\nCameroon                  90\nMorocco                   84\nParaguay                  80\nRussia                    78\nUkraine                   73\nNorthern Ireland          71\nSouth Africa              70\nFinland                   65\nBosnia Herzegovina        61\nAlgeria                   60\nCanada                    59\nVenezuela                 57\nSlovenia                  55\nSlovakia                  54\nRomania                   53\nDR Congo                  52\nIceland                   47\nNew Zealand               42\nAlbania                   40\nHungary                   38\nMali                      38\nPeru                      35\nEcuador                   34\nKosovo                    33\nBulgaria                  32\nTunisia                   32\nEgypt                     31\nIndia                     29\nCosta Rica                28\nBolivia                   28\nJamaica                   27\nGeorgia                   26\nCongo                     24\nGuinea                    24\nMontenegro                23\nFYR Macedonia             19\nIran                      17\nCape Verde                17\nGuinea Bissau             15\nBenin                     15\nBurkina Faso              15\nGabon                     15\nAngola                    15\nHonduras                  14\nCuracao                   14\nGambia                    14\nIsrael                    14\nEstonia                   13\nZimbabwe                  13\nTogo                      12\nMadagascar                12\nArmenia                   10\nHaiti                     10\nKenya                     10\nPanama                    10\nSyria                      9\nZambia                     9\nLithuania                  8\nLuxembourg                 8\nCyprus                     7\nIraq                       7\nComoros                    6\nLatvia                     6\nUganda                     6\nSierra Leone               6\nEl Salvador                5\nThailand                   5\nEquatorial Guinea          5\nAzerbaijan                 5\nMoldova                    5\nFaroe Islands              5\nBelarus                    4\nMozambique                 4\nAfghanistan                4\nSuriname                   4\nAntigua & Barbuda          4\nMontserrat                 4\nLibya                      4\nKorea DPR                  4\nKazakhstan                 4\nCentral African Rep.       3\nBurundi                    3\nGuatemala                  3\nSudan                      3\nLiechtenstein              3\nTanzania                   3\nMauritania                 3\nNamibia                    3\nTrinidad & Tobago          3\nNiger                      3\nCuba                       3\nGuyana                     3\nBarbados                   3\nSt Kitts Nevis             3\nChad                       2\nHong Kong                  2\nUzbekistan                 2\nNicaragua                  2\nPhilippines                2\nBermuda                    2\nEritrea                    2\nDominican Republic         1\nRwanda                     1\nIndonesia                  1\nUnited Arab Emirates       1\nSouth Sudan                1\nBotswana                   1\nPuerto Rico                1\nBelize                     1\nJordan                     1\nLebanon                    1\nKuwait                     1\nPalestine                  1\nFiji                       1\nSt Lucia                   1\nEthiopia                   1\nMalta                      1\nOman                       1\nSão Tomé & Príncipe        1\nGrenada                    1\nGuam                       1\nNew Caledonia              1\nMauritius                  1\nAndorra                    1\nQatar                      1'

In [24]:
df["Nationality"].isna().sum()

np.int64(0)

## Flag

In [25]:
# checking missing val

df["Flag"].isna().sum()

np.int64(0)

In [26]:
# checking duplicate val

df["Flag"].value_counts()

Flag
https://cdn.sofifa.org/flags/14.png     1521
https://cdn.sofifa.org/flags/21.png     1172
https://cdn.sofifa.org/flags/45.png     1013
https://cdn.sofifa.org/flags/18.png      880
https://cdn.sofifa.org/flags/52.png      845
                                        ...
https://cdn.sofifa.org/flags/157.png       1
https://cdn.sofifa.org/flags/215.png       1
https://cdn.sofifa.org/flags/128.png       1
https://cdn.sofifa.org/flags/2.png         1
https://cdn.sofifa.org/flags/182.png       1
Name: count, Length: 163, dtype: int64

## Overall

In [27]:
df["Overall"].isna().sum()

np.int64(1)

In [28]:
df = df.dropna(subset=["Overall"])

In [29]:
df["Overall"].isna().sum()

np.int64(0)

In [30]:
df["Overall"].value_counts()

Overall
66.0    1106
67.0    1066
64.0    1021
68.0     979
65.0     973
63.0     947
69.0     932
70.0     855
62.0     816
71.0     746
72.0     712
61.0     655
60.0     610
73.0     588
74.0     513
59.0     482
75.0     473
58.0     412
57.0     368
76.0     361
56.0     317
77.0     295
55.0     247
54.0     235
53.0     186
79.0     166
78.0     161
52.0     148
80.0     137
51.0     115
50.0      94
82.0      92
81.0      90
83.0      68
84.0      43
49.0      33
85.0      32
48.0      28
86.0      21
88.0      16
47.0      16
87.0      13
89.0      10
91.0       6
90.0       4
94.0       2
92.0       1
46.0       1
Name: count, dtype: int64

In [31]:
df["Overall"].unique()

array([71., 86., 79., 70., 66., 75., 88., 73., 63., 57., 69., 82., 72.,
       84., 67., 59., 62., 53., 68., 61., 76., 65., 74., 94., 83., 58.,
       54., 85., 81., 80., 64., 77., 60., 48., 52., 55., 56., 89., 78.,
       87., 91., 90., 51., 92., 50., 49., 47., 46.])

In [32]:
df["Overall"].dtypes

dtype('float64')

In [33]:
df["Overall"] = df["Overall"].astype(int)

C:\Users\bhoom\AppData\Local\Temp\ipykernel_11368\4191887587.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Overall"] = df["Overall"].astype(int)

In [34]:
df["Overall"].dtypes

dtype('int64')

## Potential

In [35]:
df["Potential"].dtypes

dtype('int64')

In [36]:
df["Potential"].isna().sum()

np.int64(0)

In [37]:
df["Potential"].duplicated().sum()

np.int64(17145)

## Club

In [38]:
df["Club"].isna().sum()

np.int64(229)

In [39]:
df = df.dropna(subset=["Club"])

In [40]:
df["Club"].isna().sum()

np.int64(0)

In [41]:
df["Club"].value_counts()

Club
Wolverhampton Wanderers    33
Empoli                     33
Chelsea                    33
Liverpool                  33
TSG 1899 Hoffenheim        33
                           ..
Derry City                 18
Sligo Rovers               18
Tromsø IL                  18
Boyacá Chicó FC            18
Limerick FC                17
Name: count, Length: 651, dtype: int64

## Club Logo

In [42]:
df["Club Logo"].isna().sum()

np.int64(0)

In [43]:
df["Club Logo"].value_counts()

Club Logo
https://cdn.sofifa.org/teams/2/light/110.png       33
https://cdn.sofifa.org/teams/2/light/1746.png      33
https://cdn.sofifa.org/teams/2/light/5.png         33
https://cdn.sofifa.org/teams/2/light/9.png         33
https://cdn.sofifa.org/teams/2/light/10029.png     33
                                                   ..
https://cdn.sofifa.org/teams/2/light/445.png       18
https://cdn.sofifa.org/teams/2/light/563.png       18
https://cdn.sofifa.org/teams/2/light/418.png       18
https://cdn.sofifa.org/teams/2/light/112019.png    18
https://cdn.sofifa.org/teams/2/light/111285.png    17
Name: count, Length: 651, dtype: int64

In [44]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

## Value

In [45]:
df["Value"].isna().sum()

np.int64(0)

In [46]:
df["Value"].value_counts()

Value
1.1M    405
375K    350
425K    333
325K    332
450K    318
        ...
62M       1
36M       1
55M       1
68M       1
81M       1
Name: count, Length: 214, dtype: int64

In [47]:
df["Value"]

0         750K
1        21.5M
2           4M
3         240K
4         150K
          ...
17189     875K
17190     650K
17191     180K
17192     650K
17193      70K
Name: Value, Length: 16963, dtype: object

In [48]:
df["Value"].unique()

array(['\x80750K', '\x8021.5M', '\x804M', '\x80240K', '\x80150K',
       '\x802.7M', '\x80950K', '\x80130K', '\x8030K', '\x803.2M',
       '\x80140K', '\x80 0', '\x801.5M', '\x80425K', '\x80270K',
       '\x8015.5M', '\x8070K', '\x8050K', '\x80160K', '\x80100K',
       '\x8010K', '\x80210K', '\x8080K', '\x80525K', '\x801.8M',
       '\x80450K', '\x80120K', '\x802.1M', '\x80170K', '\x803.9M',
       '\x8077M', '\x8040K', '\x80400K', '\x801.3M', '\x806M', '\x801.6M',
       '\x8090K', '\x8020K', '\x80325K', '\x80200K', '\x8014M',
       '\x80900K', '\x80250K', '\x80280K', '\x803M', '\x801M', '\x8060K',
       '\x808M', '\x801.7M', '\x801.9M', '\x80300K', '\x804.1M',
       '\x80800K', '\x80220K', '\x801.1M', '\x80375K', '\x80725K',
       '\x80260K', '\x806.5M', '\x80180K', '\x801.2M', '\x80190K',
       '\x80575K', '\x80110K', '\x8012M', '\x801.4M', '\x80675K',
       '\x8013M', '\x803.6M', '\x80550K', '\x807M', '\x80230K',
       '\x805.5M', '\x803.3M', '\x80625K', '\x80350K', '\x80600K',
       '\x80475K', '\x809M', '\x8010M', '\x802.2M', '\x804.4M',
       '\x803.4M', '\x80290K', '\x8018M', '\x80650K', '\x802M',
       '\x804.2M', '\x803.8M', '\x802.5M', '\x803.5M', '\x804.7M',
       '\x8013.5M', '\x80500K', '\x8027M', '\x803.7M', '\x8022M',
       '\x80850K', '\x802.3M', '\x805M', '\x80700K', '\x80975K',
       '\x804.5M', '\x8030M', '\x802.8M', '\x804.3M', '\x80775K',
       '\x8011M', '\x80925K', '\x804.8M', '\x8011.5M', '\x808.5M',
       '\x803.1M', '\x802.9M', '\x80875K', '\x807.5M', '\x802.4M',
       '\x8034M', '\x8064.5M', '\x804.9M', '\x8051M', '\x802.6M',
       '\x8017.5M', '\x80110.5M', '\x8012.5M', '\x8024M', '\x8015M',
       '\x8019M', '\x80825K', '\x8037M', '\x8025M', '\x8038M', '\x8057M',
       '\x8036M', '\x8060M', '\x8046.5M', '\x8016.5M', '\x8014.5M',
       '\x8021M', '\x8026M', '\x8017M', '\x8023M', '\x809.5M', '\x8045M',
       '\x8080M', '\x8043.5M', '\x8043M', '\x8067M', '\x8027.5M',
       '\x8020M', '\x8024.5M', '\x8035.5M', '\x8029M', '\x8046M',
       '\x8038.5M', '\x8033M', '\x8044M', '\x8030.5M', '\x8037.5M',
       '\x8093M', '\x8029.5M', '\x8039M', '\x8035M', '\x8010.5M',
       '\x8022.5M', '\x8016M', '\x8032M', '\x8018.5M', '\x804.6M',
       '\x8059M', '\x8069.5M', '\x8045.5M', '\x8051.5M', '\x8073.5M',
       '\x8031M', '\x80118.5M', '\x8036.5M', '\x8053.5M', '\x8028.5M',
       '\x8052M', '\x8062.5M', '\x8025.5M', '\x8019.5M', '\x80102M',
       '\x8072M', '\x8078M', '\x8026.5M', '\x8064M', '\x8031.5M',
       '\x8062M', '\x8023.5M', '\x8055M', '\x8059.5M', '\x8068M',
       '\x8050M', '\x8053M', '\x8083.5M', '\x8032.5M', '\x8042M',
       '\x8056.5M', '\x8044.5M', '\x8020.5M', '\x8040.5M', '\x8034.5M',
       '\x8050.5M', '\x8041.5M', '\x8089M', '\x8042.5M', '\x8063M',
       '\x8054M', '\x8028M', '\x8041M', '\x8040M', '\x8081M'],
      dtype=object)

In [49]:
df=df.rename(columns={"Value":"Value in Euro"})

In [50]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [51]:
df["Value in Euro"] = (df["Value in Euro"].str.replace("\x80", "", regex=False).str.replace("K", "000", regex=False).str.replace("M", "000000").astype(float).astype(int))

In [52]:
df["Value in Euro"].dtypes

dtype('int64')

In [53]:
df["Value in Euro"].value_counts()

Value in Euro
1           1839
2            873
3            619
4            402
375000       350
            ...
62000000       1
38             1
55000000       1
46000000       1
81000000       1
Name: count, Length: 182, dtype: int64

In [54]:
df["Value in Euro"].isna().sum()

np.int64(0)

## Wage

In [55]:
df["Wage"].isna().sum()

np.int64(0)

In [56]:
df["Wage"].value_counts()

Wage
1K      4546
2K      2663
3K      1754
4K      1204
5K       821
         ...
455K       1
190K       1
420K       1
200K       1
225K       1
Name: count, Length: 142, dtype: int64

In [57]:
df["Wage"].unique()

array(['\x806K', '\x8021K', '\x8023K', '\x802K', '\x804K', '\x8013K',
       '\x8077K', '\x8030K', '\x801K', '\x8010K', '\x805K', '\x8016K',
       '\x80110K', '\x803K', '\x807K', '\x8014K', '\x809K', '\x8080K',
       '\x8012K', '\x80405K', '\x808K', '\x8056K', '\x8018K', '\x8015K',
       '\x8024K', '\x8020K', '\x8060K', '\x8022K', '\x8011K', '\x8019K',
       '\x8049K', '\x8025K', '\x8034K', '\x8039K', '\x8053K', '\x8036K',
       '\x8031K', '\x8028K', '\x8033K', '\x8029K', '\x8094K', '\x8026K',
       '\x8044K', '\x8027K', '\x8057K', '\x8017K', '\x8041K', '\x8047K',
       '\x8051K', '\x8043K', '\x80185K', '\x8050K', '\x8095K', '\x80120K',
       '\x8037K', '\x80215K', '\x80170K', '\x8048K', '\x8040K', '\x8062K',
       '\x8061K', '\x8032K', '\x8046K', '\x8045K', '\x8035K', '\x80240K',
       '\x8066K', '\x80300K', '\x8070K', '\x80380K', '\x8072K', '\x8055K',
       '\x8088K', '\x8042K', '\x80565K', '\x8098K', '\x8038K', '\x8074K',
       '\x8076K', '\x8085K', '\x80140K', '\x8052K', '\x8078K', '\x8075K',
       '\x8081K', '\x80165K', '\x8099K', '\x80105K', '\x80115K',
       '\x8068K', '\x80130K', '\x80245K', '\x80150K', '\x80285K',
       '\x8096K', '\x80260K', '\x8092K', '\x8058K', '\x8065K', '\x80145K',
       '\x80125K', '\x80155K', '\x8054K', '\x8091K', '\x8073K',
       '\x80355K', '\x80135K', '\x8064K', '\x80455K', '\x80190K',
       '\x80420K', '\x8086K', '\x8082K', '\x8069K', '\x80160K', '\x8090K',
       '\x80200K', '\x80100K', '\x80180K', '\x8097K', '\x80175K',
       '\x8079K', '\x80205K', '\x80340K', '\x8059K', '\x8084K', '\x8063K',
       '\x80265K', '\x80250K', '\x8083K', '\x80315K', '\x80290K',
       '\x8067K', '\x80230K', '\x80195K', '\x80210K', '\x8089K',
       '\x8087K', '\x8071K', '\x8093K', '\x80255K', '\x80225K'],
      dtype=object)

In [58]:
df["Wage"] = (df["Wage"].str.replace("\x80", "", regex=False).str.replace("K", "000", regex=False).astype(float).astype(int))

In [59]:
df["Wage"].dtypes

dtype('int64')

In [60]:
df["Wage"].value_counts()

Wage
1000      4546
2000      2663
3000      1754
4000      1204
5000       821
          ...
455000       1
190000       1
420000       1
200000       1
225000       1
Name: count, Length: 142, dtype: int64

In [61]:
df["Wage"].unique()

array([  6000,  21000,  23000,   2000,   4000,  13000,  77000,  30000,
         1000,  10000,   5000,  16000, 110000,   3000,   7000,  14000,
         9000,  80000,  12000, 405000,   8000,  56000,  18000,  15000,
        24000,  20000,  60000,  22000,  11000,  19000,  49000,  25000,
        34000,  39000,  53000,  36000,  31000,  28000,  33000,  29000,
        94000,  26000,  44000,  27000,  57000,  17000,  41000,  47000,
        51000,  43000, 185000,  50000,  95000, 120000,  37000, 215000,
       170000,  48000,  40000,  62000,  61000,  32000,  46000,  45000,
        35000, 240000,  66000, 300000,  70000, 380000,  72000,  55000,
        88000,  42000, 565000,  98000,  38000,  74000,  76000,  85000,
       140000,  52000,  78000,  75000,  81000, 165000,  99000, 105000,
       115000,  68000, 130000, 245000, 150000, 285000,  96000, 260000,
        92000,  58000,  65000, 145000, 125000, 155000,  54000,  91000,
        73000, 355000, 135000,  64000, 455000, 190000, 420000,  86000,
        82000,  69000, 160000,  90000, 200000, 100000, 180000,  97000,
       175000,  79000, 205000, 340000,  59000,  84000,  63000, 265000,
       250000,  83000, 315000, 290000,  67000, 230000, 195000, 210000,
        89000,  87000,  71000,  93000, 255000, 225000])

In [62]:
df=df.rename(columns={"Wage":"Wage in Euro"})

## Special

In [63]:
df["Special"].isna().sum()

np.int64(0)

In [64]:
df["Special"].value_counts()

Special
1728    43
1655    42
1628    42
1745    41
1740    41
        ..
2099     1
2061     1
890      1
2200     1
827      1
Name: count, Length: 1420, dtype: int64

In [65]:
df["Special"].dtypes

dtype('int64')

## Preferred Foot

In [66]:
df["Preferred Foot"].isna().sum()

np.int64(46)

In [67]:
df = df.dropna(subset=["Preferred Foot"])

In [68]:
df["Preferred Foot"].isna().sum()

np.int64(0)

In [69]:
df["Preferred Foot"].unique()

array(['Right', 'Left'], dtype=object)

In [70]:
df["Preferred Foot"].value_counts()

Preferred Foot
Right    13008
Left      3909
Name: count, dtype: int64

## International Reputation

In [71]:
df["International Reputation"].isna().sum()

np.int64(0)

In [72]:
df["International Reputation"].unique()

array([1., 4., 2., 3., 5.])

In [73]:
df["International Reputation"].value_counts()

International Reputation
1.0    15339
2.0     1224
3.0      299
4.0       49
5.0        6
Name: count, dtype: int64

In [74]:
df["International Reputation"].dtypes

dtype('float64')

In [75]:
df["International Reputation"] = df["International Reputation"].astype(int)

In [76]:
df["International Reputation"].dtypes

dtype('int64')

In [77]:
df["International Reputation"].value_counts()

International Reputation
1    15339
2     1224
3      299
4       49
5        6
Name: count, dtype: int64

In [78]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage in Euro',
       'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

## Weak Foot

In [79]:
df["Weak Foot"].isna().sum()

np.int64(0)

In [80]:
df["Weak Foot"].unique()

array([4., 3., 2., 5., 1.])

In [81]:
df["Weak Foot"].value_counts()

Weak Foot
3.0    10586
2.0     3455
4.0     2515
5.0      218
1.0      143
Name: count, dtype: int64

In [82]:
df["Weak Foot"].dtypes

dtype('float64')

In [83]:
df["Weak Foot"]=df["Weak Foot"].astype(int)

In [84]:
df["Weak Foot"].dtypes

dtype('int64')

In [85]:
df["Weak Foot"].value_counts()

Weak Foot
3    10586
2     3455
4     2515
5      218
1      143
Name: count, dtype: int64

## Skill Moves

In [86]:
df["Skill Moves"].isna().sum()

np.int64(0)

In [87]:
df["Skill Moves"].dtypes

dtype('float64')

In [88]:
df["Skill Moves"].value_counts()

Skill Moves
2.0    7907
3.0    6199
1.0    1894
4.0     871
5.0      46
Name: count, dtype: int64

In [89]:
df["Skill Moves"]=df["Skill Moves"].astype(int)

In [91]:
df["Skill Moves"].dtypes

dtype('int64')

In [92]:
df["Skill Moves"].value_counts()

Skill Moves
2    7907
3    6199
1    1894
4     871
5      46
Name: count, dtype: int64

## Work Rate

In [93]:
df["Work Rate"].isna().sum()

np.int64(0)

In [94]:
df["Work Rate"].dtypes

dtype('O')

In [95]:
df["Work Rate"].value_counts()

Work Rate
Medium/ Medium    9130
High/ Medium      2962
Medium/ High      1573
High/ High         967
Medium/ Low        794
High/ Low          635
Low/ Medium        414
Low/ High          411
Low/ Low            31
Name: count, dtype: int64

In [96]:
df["Work Rate"] = df["Work Rate"].str.replace(" ", "", regex=False)

In [97]:
df["Work Rate"].value_counts()

Work Rate
Medium/Medium    9130
High/Medium      2962
Medium/High      1573
High/High         967
Medium/Low        794
High/Low          635
Low/Medium        414
Low/High          411
Low/Low            31
Name: count, dtype: int64

In [98]:
df[["Work_Rate_Attack", "Work_Rate_Defense"]] = df["Work Rate"].str.split("/", expand=True)

In [99]:
df["Work_Rate_Attack"].value_counts()

Work_Rate_Attack
Medium    11497
High       4564
Low         856
Name: count, dtype: int64

In [100]:
df["Work_Rate_Defense"].value_counts()

Work_Rate_Defense
Medium    12506
High       2951
Low        1460
Name: count, dtype: int64

In [101]:
df.drop("Work Rate", axis=1, inplace=True)

In [102]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage in Euro',
       'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Body Type', 'Real Face', 'Position', 'Jersey Number',
       'Joined', 'Loaned From', 'Contract Valid Until', 'Height', 'Weight',
       'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM',
       'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB',
       'LCB', 'CB', 'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy',
       'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
       'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
       'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
       'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause', 'Work_Rate_Attack', 'Work_Rate_Defense'],
      dtype='object')

## Body Type

In [103]:
df["Body Type"].dtypes

dtype('O')

In [104]:
df["Body Type"].isna().sum()

np.int64(0)

In [105]:
df["Body Type"].value_counts()

Body Type
Normal                 9875
Lean                   5979
Stocky                 1056
C. Ronaldo                1
Akinfenwa                 1
Messi                     1
Neymar                    1
Courtois                  1
Shaqiri                   1
PLAYER_BODY_TYPE_25       1
Name: count, dtype: int64

In [106]:
df=df.replace({"Body Type":{"C. Ronaldo":"Normal",
                            "Akinfenwa":"Normal",
                            "Messi":"Normal",
                            "Neymar":"Normal",
                            "Courtois":"Normal",
                            "Shaqiri":"Normal",
                            "PLAYER_BODY_TYPE_25":"Normal"}})

In [107]:
df["Body Type"].value_counts()

Body Type
Normal    9882
Lean      5979
Stocky    1056
Name: count, dtype: int64

## Real Face

In [108]:
df["Real Face"].value_counts()

Real Face
No     15322
Yes     1595
Name: count, dtype: int64

In [109]:
df["Real Face"].isna().sum()

np.int64(0)

In [110]:
df["Real Face"].unique()

array(['No', 'Yes'], dtype=object)

## Position

In [111]:
df["Position"].isna().sum()

np.int64(0)

In [112]:
df["Position"].dtypes

dtype('O')

In [113]:
df["Position"].value_counts()

Position
ST     1967
GK     1894
CB     1641
CM     1302
LB     1220
RB     1191
RM     1041
LM     1025
CAM     907
CDM     893
RCB     625
LCB     610
RCM     373
LCM     367
LW      352
RW      346
RDM     238
LDM     229
RS      198
LS      193
RWB      85
LWB      75
CF       73
RAM      21
LAM      20
RF       16
LF       15
Name: count, dtype: int64

## Jersey Number

In [116]:
df["Jersey Number"].dtypes

dtype('float64')

In [117]:
df["Jersey Number"].isna().sum()

np.int64(0)

In [118]:
df["Jersey Number"].value_counts()

Jersey Number
8.0     570
7.0     565
10.0    560
6.0     550
11.0    537
       ...
68.0      3
74.0      2
79.0      2
64.0      2
85.0      1
Name: count, Length: 99, dtype: int64

In [119]:
df["Jersey Number"]=df["Jersey Number"].astype(int)

In [120]:
df["Jersey Number"].dtypes

dtype('int64')

In [121]:
df["Jersey Number"].unique()

array([10,  8,  5, 11, 27,  1, 22, 18,  4,  3, 24, 23,  7, 17, 16, 26, 40,
       15,  9, 14, 20, 25, 44, 33, 13, 32, 70, 37,  6, 19, 21, 34, 31, 30,
       35, 48, 12, 46, 29, 79,  2, 50, 60, 28, 99, 39, 83, 41, 77, 87, 42,
       71, 36, 88, 81, 38, 47, 55, 69, 56, 66, 76, 54, 45, 43, 82, 95, 89,
       63, 92, 91, 75, 90, 78, 86, 80, 53, 67, 68, 52, 93, 49, 58, 94, 57,
       96, 72, 73, 62, 97, 74, 98, 51, 64, 61, 65, 59, 84, 85])

## Joined

In [122]:
df["Joined"].dtypes

dtype('O')

In [123]:
df["Joined"].unique()

array(['Jul 19, 2014', 'Jul 16, 2018', 'Jul 9, 2015', ..., 'Nov 15, 2018',
       'Nov 27, 2018', 'Nov 30, 2018'], shape=(1698,), dtype=object)

In [124]:
df["Joined"].value_counts()

Joined
Jul 1, 2018     1447
Jul 1, 2017     1075
Jan 1, 2018      611
Jul 1, 2016      581
Jul 1, 2015      350
                ...
May 7, 2014        1
Nov 1, 2012        1
Dec 7, 2011        1
Dec 16, 2013       1
Mar 11, 2011       1
Name: count, Length: 1697, dtype: int64

In [125]:
df["Joined"].isna().sum()

np.int64(1183)

In [126]:
df.dropna(subset=["Joined"], inplace=True)

In [127]:
df["Joined"].isna().sum()

np.int64(0)

In [128]:
df["Joined"] = pd.to_datetime(df["Joined"], errors="coerce")

In [129]:
df["Joined"].value_counts()

Joined
2018-07-01    1447
2017-07-01    1075
2018-01-01     611
2016-07-01     581
2015-07-01     350
              ...
2014-05-07       1
2012-11-01       1
2011-12-07       1
2013-12-16       1
2011-03-11       1
Name: count, Length: 1697, dtype: int64

In [132]:
df["Joined"].unique()

<DatetimeArray>
['2014-07-19 00:00:00', '2018-07-16 00:00:00', '2015-07-09 00:00:00',
 '2017-08-31 00:00:00', '2018-07-06 00:00:00', '2017-07-04 00:00:00',
 '2016-07-04 00:00:00', '2018-07-01 00:00:00', '2011-07-01 00:00:00',
 '2008-07-01 00:00:00',
 ...
 '2018-10-07 00:00:00', '2018-10-13 00:00:00', '2018-10-20 00:00:00',
 '2018-10-28 00:00:00', '2018-11-06 00:00:00', '2018-11-11 00:00:00',
 '2018-10-29 00:00:00', '2018-11-15 00:00:00', '2018-11-27 00:00:00',
 '2018-11-30 00:00:00']
Length: 1697, dtype: datetime64[ns]

## Loaned From

In [133]:
df["Loaned From"].isna().sum()

np.int64(15734)

In [134]:
df.shape

(15734, 89)

In [135]:
df["Loaned From"].unique()

array([nan], dtype=object)

In [136]:
df["Loaned From"].value_counts()

Series([], Name: count, dtype: int64)

In [138]:
df.drop("Loaned From", axis=1, inplace=True)

In [139]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage in Euro',
       'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Body Type', 'Real Face', 'Position', 'Jersey Number',
       'Joined', 'Contract Valid Until', 'Height', 'Weight', 'LS', 'ST', 'RS',
       'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing',
       'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing',
       'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions',
       'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause', 'Work_Rate_Attack', 'Work_Rate_Defense'],
      dtype='object')

## Contract Valid Until

In [140]:
df["Contract Valid Until"].isna().sum()

np.int64(0)

In [141]:
df["Contract Valid Until"].unique()

array(['2019', '2021', '2020', '2023', '2018', '2022', '2024', '2025',
       '2026'], dtype=object)

In [142]:
df["Contract Valid Until"].value_counts()

Contract Valid Until
2019    4603
2021    4076
2020    3836
2022    1407
2023     966
2018     817
2024      20
2025       7
2026       2
Name: count, dtype: int64

In [143]:
df["Contract Valid Until"].dtypes

dtype('O')

In [144]:
df["Contract Valid Until"]=df["Contract Valid Until"].astype(int)

In [145]:
df["Contract Valid Until"].unique()

array([2019, 2021, 2020, 2023, 2018, 2022, 2024, 2025, 2026])

In [146]:
df["Contract Valid Until"].dtypes

dtype('int64')

##  Height

In [147]:
df["Height"].isna().sum()

np.int64(0)

In [148]:
df["Height"].value_counts()

Height
6'0     2476
5'10    2149
5'9     1938
5'11    1898
6'2     1775
6'1     1671
6'3      850
5'8      812
5'7      753
6'4      661
5'6      256
6'5      217
5'5      122
6'6       76
5'4       29
6'7       19
5'3       13
6'8        9
5'2        5
5'1        3
6'9        2
Name: count, dtype: int64

In [149]:
df["Height"].dtypes

dtype('O')

In [150]:
height = df["Height"].str.split("'", expand=True)

df["Height"] = ((height[0].astype(float) * 12 + height[1].astype(float)) * 2.54).round(1)

In [151]:
df["Height"].head()

0    177.8
1    170.2
2    170.2
3    180.3
4    167.6
Name: Height, dtype: float64

In [152]:
df["Height"].dtypes

dtype('float64')

## Weight

In [153]:
df["Weight"].isna().sum()

np.int64(0)

In [154]:
df["Weight"].unique()

array(['143lbs', '150lbs', '159lbs', '168lbs', '154lbs', '165lbs',
       '203lbs', '172lbs', '185lbs', '176lbs', '196lbs', '179lbs',
       '187lbs', '183lbs', '174lbs', '170lbs', '198lbs', '161lbs',
       '194lbs', '190lbs', '181lbs', '148lbs', '146lbs', '212lbs',
       '157lbs', '209lbs', '163lbs', '214lbs', '134lbs', '141lbs',
       '192lbs', '152lbs', '207lbs', '205lbs', '223lbs', '139lbs',
       '132lbs', '201lbs', '137lbs', '243lbs', '126lbs', '236lbs',
       '216lbs', '218lbs', '123lbs', '130lbs', '227lbs', '128lbs',
       '229lbs', '225lbs', '220lbs', '234lbs', '115lbs', '121lbs',
       '117lbs', '110lbs', '119lbs'], dtype=object)

In [155]:
df["Weight"] = df["Weight"].str.replace("lbs", "", regex=False).astype(int)

In [156]:
df["Weight"].dtypes

dtype('int64')

## all pos cols

In [157]:
df["LS"].isna().sum()

np.int64(1809)

In [160]:
df["LS"].value_counts()

LS
61+2    610
60+2    597
63+2    588
59+2    577
64+2    563
       ...
49+3      1
88+2      1
55+3      1
91+3      1
82+4      1
Name: count, Length: 93, dtype: int64

In [162]:
df[['LS', 'ST', 'RS',
    'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
    'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
    'RCB', 'RB']]

,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
0,66+2,66+2,66+2,67+2,68+2,68+2,68+2,67+2,69+2,69+2,...,62+2,65+2,65+2,65+2,62+2,59+2,59+2,59+2,59+2,59+2
1,74+3,74+3,74+3,82+3,81+3,81+3,81+3,82+3,85+3,85+3,...,71+3,73+3,73+3,73+3,71+3,68+3,63+3,63+3,63+3,68+3
2,67+2,67+2,67+2,72+2,72+2,72+2,72+2,72+2,76+2,76+2,...,68+2,74+2,74+2,74+2,68+2,65+2,66+2,66+2,66+2,65+2
3,63+2,63+2,63+2,64+2,64+2,64+2,64+2,64+2,65+2,65+2,...,68+2,69+2,69+2,69+2,68+2,67+2,69+2,69+2,69+2,67+2
4,59+2,59+2,59+2,59+2,60+2,60+2,60+2,59+2,62+2,62+2,...,60+2,65+2,65+2,65+2,60+2,59+2,62+2,62+2,62+2,59+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17189,57+2,57+2,57+2,63+2,62+2,62+2,62+2,63+2,64+2,64+2,...,58+2,59+2,59+2,59+2,58+2,56+2,52+2,52+2,52+2,56+2
17190,60+2,60+2,60+2,62+2,60+2,60+2,60+2,62+2,58+2,58+2,...,46+2,39+2,39+2,39+2,46+2,43+2,36+2,36+2,36+2,43+2
17191,43+2,43+2,43+2,41+2,41+2,41+2,41+2,41+2,43+2,43+2,...,52+2,55+2,55+2,55+2,52+2,54+2,56+2,56+2,56+2,54+2
17192,55+2,55+2,55+2,60+2,59+2,59+2,59+2,60+2,61+2,61+2,...,51+2,49+2,49+2,49+2,51+2,49+2,42+2,42+2,42+2,49+2
17193,37+2,37+2,37+2,33+2,34+2,34+2,34+2,33+2,34+2,34+2,...,44+2,46+2,46+2,46+2,44+2,46+2,50+2,50+2,50+2,46+2

In [163]:
position_cols = [
    'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
    'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM',
    'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
    'RCB', 'RB'
]

In [166]:
position_cols = [
    'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
    'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM',
    'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
    'RCB', 'RB'
]

for col in position_cols:
    parts = df[col].astype("string").str.split("+", expand=True)

    df[col] = (
        pd.to_numeric(parts[0], errors="coerce") +
        pd.to_numeric(parts[1], errors="coerce")
    )

In [168]:
df[position_cols]

,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
0,68,68,68,69,70,70,70,69,71,71,...,64,67,67,67,64,61,61,61,61,61
1,77,77,77,85,84,84,84,85,88,88,...,74,76,76,76,74,71,66,66,66,71
2,69,69,69,74,74,74,74,74,78,78,...,70,76,76,76,70,67,68,68,68,67
3,65,65,65,66,66,66,66,66,67,67,...,70,71,71,71,70,69,71,71,71,69
4,61,61,61,61,62,62,62,61,64,64,...,62,67,67,67,62,61,64,64,64,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17189,59,59,59,65,64,64,64,65,66,66,...,60,61,61,61,60,58,54,54,54,58
17190,62,62,62,64,62,62,62,64,60,60,...,48,41,41,41,48,45,38,38,38,45
17191,45,45,45,43,43,43,43,43,45,45,...,54,57,57,57,54,56,58,58,58,56
17192,57,57,57,62,61,61,61,62,63,63,...,53,51,51,51,53,51,44,44,44,51
17193,39,39,39,35,36,36,36,35,36,36,...,46,48,48,48,46,48,52,52,52,48

In [169]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage in Euro',
       'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Body Type', 'Real Face', 'Position', 'Jersey Number',
       'Joined', 'Contract Valid Until', 'Height', 'Weight', 'LS', 'ST', 'RS',
       'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing',
       'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing',
       'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions',
       'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause', 'Work_Rate_Attack', 'Work_Rate_Defense'],
      dtype='object')

## Crossing

In [170]:
df["Crossing"].isna().sum()

np.int64(0)

In [171]:
df["Crossing"].unique()

array([68., 77., 80., 63., 64., 34., 13., 18., 49., 59., 62., 53., 67.,
       75., 28., 72., 15., 51., 41., 20., 24., 61., 33., 52., 11., 16.,
       46., 19., 12., 55., 48., 92., 84., 83., 36., 79., 10., 56., 17.,
       71., 45., 73., 86., 70., 58., 35., 69., 78., 25., 65., 74., 43.,
       54., 57., 39., 21., 42., 14., 60.,  9., 66., 76.,  7., 37., 50.,
        8., 26., 30., 40., 32., 23., 47., 85., 44., 38., 82., 31., 81.,
       27., 29., 22., 87., 91., 90.,  5., 88., 93.,  6., 89.])

In [172]:
df["Crossing"].value_counts()

Crossing
60.0    451
65.0    448
62.0    445
59.0    437
64.0    432
       ...
89.0      2
92.0      1
5.0       1
88.0      1
93.0      1
Name: count, Length: 89, dtype: int64

In [173]:
df["Crossing"].dtypes

dtype('float64')

In [174]:
df["Crossing"]=df["Crossing"].astype(int)

In [175]:
df["Crossing"].dtypes

dtype('int64')

## Finishing

In [176]:
df["Finishing"].isna().sum()

np.int64(0)

In [177]:
df["Finishing"].unique()

array([64., 70., 68., 53., 59., 20., 15., 11., 62., 60., 29., 69., 12.,
       56., 22., 85., 51., 65., 23., 52., 26., 58., 17., 13., 34., 39.,
        9.,  8., 19., 76., 25., 55., 67., 94., 49., 44., 14., 78.,  4.,
       50., 40., 61., 86., 80., 57., 66., 16., 45., 10., 75., 37., 46.,
       38., 32., 54., 35., 63., 47., 33., 48., 30., 18., 83., 21., 31.,
       81., 72., 41., 28., 82., 42., 79., 74., 27., 73., 77., 43., 71.,
       36., 93., 24., 95., 84.,  7., 88., 89., 87.,  5.,  6., 91., 90.,
        2.])

In [178]:
df["Finishing"].dtypes

dtype('float64')

In [179]:
df["Finishing"]=df["Finishing"].astype(int)

In [180]:
df["Finishing"].dtypes

dtype('int64')

## HeadingAccuracy

In [181]:
df["HeadingAccuracy"].isna().sum()

np.int64(0)

In [182]:
df["HeadingAccuracy"].unique()

array([61., 54., 43., 62., 58., 74., 13., 14., 75., 77., 72., 25., 69.,
       73., 51., 11., 48., 65., 56., 49., 10., 12., 19., 64., 59., 39.,
       41., 47., 89., 60., 44., 76.,  6., 15., 46., 28.,  9., 83., 55.,
       68., 52., 63., 78., 70., 66., 50., 45., 85., 92., 81., 23., 30.,
       34., 57., 20., 16., 35., 26., 82., 22., 80., 67., 71., 18., 17.,
       24., 38., 36., 37., 79., 40., 42., 84., 33., 53., 91.,  8., 86.,
       90., 94., 32., 93., 87., 27., 31.,  7., 88., 29.,  5., 21.,  4.])

In [184]:
df["HeadingAccuracy"]=df["HeadingAccuracy"].astype(int)

In [185]:
df["HeadingAccuracy"].dtypes

dtype('int64')

## ShortPassing

In [186]:
df["ShortPassing"].isna().sum()

np.int64(0)

In [187]:
df["ShortPassing"].unique()

array([76., 90., 86., 69., 72., 62., 37., 39., 68., 54., 78., 60., 75.,
       21., 56., 82., 46., 67., 58., 28., 38., 24., 64., 66., 27., 33.,
       52., 26., 29., 74., 79., 77., 81., 57., 70., 19., 34., 65., 73.,
       61., 59., 17., 35., 36., 31., 45., 50., 53., 71., 25., 43., 18.,
       63., 15., 23., 22., 42., 11., 20., 32., 13., 80., 44., 85., 55.,
       51., 48., 40., 84., 12., 30., 16., 83., 47., 49., 89., 41., 93.,
       87., 88., 14.,  7.,  8., 91., 92.])

In [188]:
df["ShortPassing"]=df["ShortPassing"].astype(int)

In [189]:
df["ShortPassing"].dtypes

dtype('int64')

## Volleys

In [190]:
df["Volleys"].isna().sum()

np.int64(0)

In [191]:
df["Volleys"].unique()

array([68., 74., 69., 61., 57., 19., 17., 11., 56., 63., 32., 67., 14.,
       86., 66., 45., 18., 21., 52., 24., 12., 33., 51., 15., 20., 60.,
       53., 75., 35., 65., 80., 87., 54., 73., 10., 49., 78.,  7., 59.,
       62., 38., 64., 50., 70., 27., 58., 26., 81., 43., 42., 22., 30.,
       55., 82., 13., 83., 71., 40., 76., 37., 31., 46., 44., 16.,  9.,
       23., 47., 48., 79., 72.,  8., 29., 77., 39., 41., 28., 34., 25.,
       36., 88., 85., 84., 90.,  6.,  4.,  5., 89.])

In [192]:
df["Volleys"]=df["Volleys"].astype(int)

In [193]:
df["Volleys"].dtypes

dtype('int64')

## Dribbling

In [194]:
df["Dribbling"].isna().sum()

np.int64(0)

In [195]:
df["Dribbling"].unique()

array([69., 90., 78., 66., 62., 44., 26., 12., 49., 65., 71., 46., 68.,
       25., 52., 72., 89., 14., 16., 20., 57., 29., 56., 18., 13., 43.,
       47., 17., 59., 48., 11., 80., 88., 73., 10., 76., 15., 70., 79.,
       35., 85., 41., 64., 58., 55., 24., 32., 45., 31., 67., 61., 74.,
       40., 38., 63., 54., 27.,  8.,  9., 51., 34., 83., 60., 22., 19.,
       39., 75., 77.,  7., 82., 53., 87., 30., 23., 42., 36., 33., 84.,
       21., 37., 81., 86., 28., 50., 97., 91.,  6., 95., 93., 92., 96.,
       94.,  4.,  5.])

In [196]:
df["Dribbling"]=df["Dribbling"].astype(int)

In [197]:
df["Dribbling"].dtypes

dtype('int64')

## Curve

In [199]:
df["Curve"].isna().sum()

np.int64(0)

In [200]:
df["Curve"].unique()

array([79., 80., 83., 58., 68., 49., 20., 13., 48., 63., 65., 51., 73.,
       25., 76., 40., 70., 90., 12., 74., 55., 46., 19., 22., 43., 14.,
       42.,  6., 18., 30., 71., 81., 94., 82., 50., 86., 57., 11., 17.,
       21., 87., 15., 69., 62., 67., 72., 38., 59., 52., 60., 10., 44.,
       78., 64., 66., 61., 16., 84.,  9., 54., 53., 39., 77., 23., 37.,
       28., 26., 75., 36., 47., 31., 29., 35., 33., 56., 24., 27., 32.,
       45., 41., 34., 85., 93., 88.,  8., 89., 91.,  7., 92.])

In [201]:
df["Curve"]=df["Curve"].astype(int)

In [202]:
df["Curve"].dtypes

dtype('int64')

## FKAccuracy

In [203]:
df["FKAccuracy"].isna().sum()

np.int64(0)

In [204]:
df["FKAccuracy"].unique()

array([79., 70., 80., 54., 67., 21., 13., 42., 62., 57., 35., 71., 31.,
       61., 81., 12., 69., 50., 47., 11., 15., 55., 23., 58., 18., 24.,
       14., 25.,  9., 10., 27., 75., 28., 20., 77., 73., 74., 76., 49.,
       56., 72., 65., 88., 46., 82., 68., 29., 64., 33., 17., 19., 63.,
       53., 22., 60., 38., 37., 52., 16., 44., 40., 48., 66., 83., 51.,
       34., 45., 43., 85., 32., 36., 41., 59., 78., 30., 86., 26.,  8.,
       39., 94., 84., 87., 92., 93.,  4.,  7., 90.,  3.,  6., 91.])

In [205]:
df["FKAccuracy"]=df["FKAccuracy"].astype(int)

In [206]:
df["FKAccuracy"].dtypes

dtype('int64')

## LongPassing

In [207]:
df["LongPassing"].isna().sum()

np.int64(0)

In [208]:
df["LongPassing"].unique()

array([71., 85., 87., 64., 68., 35., 37., 41., 47., 73., 57., 72., 22.,
       43., 60., 52., 27., 63., 49., 26., 39., 32., 59., 23., 25., 28.,
       30., 69., 75., 77., 51., 70., 78., 74., 33., 29., 83., 61., 58.,
       56., 66., 34., 79., 55., 48., 62., 24., 76., 53., 80., 31., 40.,
       13., 67., 20., 82., 15., 14., 38., 21., 50., 65., 12., 45., 19.,
       36., 11., 81., 54., 42., 16., 44., 84., 46., 17., 89., 90., 18.,
       88., 10.,  9., 91., 86.])

In [209]:
df["LongPassing"]=df["LongPassing"].astype(int)

In [210]:
df["LongPassing"].dtypes

dtype('int64')

## BallControl

In [211]:
df["BallControl"].isna().sum()

np.int64(0)

In [212]:
df["BallControl"].unique()

array([71., 92., 82., 67., 68., 60., 28., 31., 63., 61., 75., 76., 23.,
       55., 88., 29., 70., 58., 21., 30., 62., 38., 65., 37., 39., 48.,
       59., 52., 15., 94., 74., 69., 78., 20., 26., 24., 72., 84., 83.,
       51., 45., 64., 33., 32., 22., 57., 79., 49., 40., 77., 44., 50.,
       35., 18., 66., 27., 56., 19., 46., 34., 16., 80., 73., 25., 14.,
       85., 12., 53., 47., 43., 54., 86., 17., 87., 13., 41., 10., 81.,
       89., 96., 42., 90., 93.,  9., 11., 36., 91., 95.,  5.,  8.])

In [213]:
df["BallControl"]=df["BallControl"].astype(int)

In [214]:
df["BallControl"].dtypes

dtype('int64')

## Acceleration

In [215]:
df["Acceleration"].isna().sum()

np.int64(0)

In [216]:
df["Acceleration"].unique()

array([56., 70., 54., 65., 33., 38., 49., 30., 35., 45., 51., 29., 39.,
       59., 48., 83., 31., 64., 44., 20., 58., 55., 22., 61., 26., 21.,
       50., 52., 62., 42., 75., 36., 84., 89., 37., 34., 41., 32., 25.,
       77., 60., 69., 71., 43., 53., 40., 47., 24., 68., 73., 66., 23.,
       57., 67., 63., 46., 76., 15., 87., 28., 27., 78., 72., 81., 80.,
       74., 17., 94., 79., 82., 88., 91., 85., 86., 93., 18., 19., 90.,
       92., 95., 97., 13., 16., 96., 12., 14.])

In [217]:
df["Acceleration"]=df["Acceleration"].astype(int)

In [218]:
df["Acceleration"].dtypes

dtype('int64')

In [219]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage in Euro',
       'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Body Type', 'Real Face', 'Position', 'Jersey Number',
       'Joined', 'Contract Valid Until', 'Height', 'Weight', 'LS', 'ST', 'RS',
       'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing',
       'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing',
       'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions',
       'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause', 'Work_Rate_Attack', 'Work_Rate_Defense'],
      dtype='object')

## SprintSpeed

In [220]:
df["SprintSpeed"].isna().sum()

np.int64(0)

In [221]:
df["SprintSpeed"].unique()

array([50., 67., 38., 62., 33., 41., 43., 36., 40., 42., 52., 32., 57.,
       49., 76., 37., 29., 47., 56., 54., 45., 46., 39., 26., 65., 27.,
       51., 58., 68., 72., 44., 82., 63., 91., 34., 28., 30., 64., 59.,
       78., 25., 61., 55., 31., 75., 21., 53., 70., 35., 17., 66., 86.,
       48., 69., 73., 24., 74., 71., 23., 60., 79., 77., 83., 81., 19.,
       90., 80., 87., 88., 22., 85., 84., 93., 89., 95., 16., 92., 15.,
       94., 20., 18., 96., 13., 12., 14.])

In [222]:
df["SprintSpeed"]=df["SprintSpeed"].astype(int)

In [223]:
df["SprintSpeed"].dtypes

dtype('int64')

## Agility

In [224]:
df["Agility"].isna().sum()

np.int64(0)

In [225]:
df["Agility"].unique()

array([62., 79., 68., 69., 60., 49., 55., 30., 35., 57., 59., 43., 87.,
       36., 73., 34., 47., 23., 65., 70., 32., 74., 53., 52., 38., 48.,
       46., 56., 71., 28., 91., 76., 67., 63., 50., 29., 25., 75., 19.,
       77., 72., 61., 58., 64., 37., 27., 31., 85., 81., 82., 51., 66.,
       42., 54., 45., 33., 78., 40., 22., 41., 44., 18., 39., 80., 92.,
       83., 84., 86., 89., 21., 88., 90., 94., 14., 93., 26., 24., 95.,
       20., 96., 15.])

In [226]:
df["Agility"]=df["Agility"].astype(int)

In [227]:
df["Agility"].dtypes

dtype('int64')

## Reactions

In [228]:
df["Reactions"].isna().sum()

np.int64(0)

In [229]:
df["Reactions"].unique()

array([65., 86., 73., 67., 72., 79., 60., 78., 63., 70., 77., 71., 85.,
       66., 68., 61., 54., 58., 62., 56., 52., 59., 55., 96., 82., 64.,
       51., 36., 76., 69., 80., 74., 47., 42., 49., 48., 57., 53., 75.,
       83., 81., 50., 84., 87., 90., 43., 41., 95., 88., 45., 92., 46.,
       91., 94., 44., 39., 40., 93., 38., 35., 37., 32., 33., 34., 30.,
       31., 21.])

In [230]:
df["Reactions"]=df["Reactions"].astype(int)

In [231]:
df["Reactions"].dtypes

dtype('int64')

## Balance

In [235]:
df["Balance"].isna().sum()

np.int64(0)

In [236]:
df["Balance"].unique()

array([72., 84., 81., 63., 91., 49., 27., 51., 66., 52., 54., 67., 46.,
       60., 34., 62., 90., 41., 65., 22., 80., 48., 76., 55., 50., 58.,
       69., 64., 21., 59., 74., 70., 85., 57., 35., 36., 25., 37., 75.,
       68., 39., 73., 78., 38., 31., 61., 28., 30., 40., 79., 87., 32.,
       56., 83., 45., 44., 71., 77., 53., 82., 33., 47., 42., 43., 19.,
       29., 23., 86., 94., 88., 24., 95., 89., 26., 92., 93., 16., 18.,
       96., 20., 17.])

In [237]:
df["Balance"]=df["Balance"].astype(int)

In [238]:
df["Balance"].dtypes

dtype('int64')

## ShotPower

In [239]:
df["ShotPower"].isna().sum()

np.int64(0)

In [240]:
df["ShotPower"].unique()

array([75., 65., 77., 71., 70., 68., 39., 13., 60., 69., 49., 28., 74.,
       82., 86., 66., 67., 20., 21., 17., 62., 48., 64., 19., 25., 26.,
       23., 24., 34., 76., 79., 95., 55., 84., 30., 22., 58., 15., 90.,
       57., 45., 56., 35., 37., 63., 80., 83., 72., 46., 50., 27., 36.,
       78., 61., 81., 52., 54., 89., 16., 85., 12., 59., 44., 40., 41.,
       53., 14., 73., 47., 38., 51., 10., 42., 31., 43., 92., 87., 88.,
       11., 18., 33., 32., 93., 29.,  6.,  7.,  8., 91.,  9., 94.,  3.,
        2.])

In [241]:
df["ShotPower"]=df["ShotPower"].astype(int)

In [242]:
df["ShotPower"].dtypes

dtype('int64')

## Jumping

In [243]:
df["Jumping"].isna().sum()

np.int64(0)

In [244]:
df["Jumping"].unique()

array([54., 47., 72., 69., 60., 75., 55., 66., 67., 57., 30., 77., 70.,
       74., 56., 45., 68., 79., 29., 53., 76., 64., 58., 65., 92., 62.,
       49., 63., 95., 82., 32., 73., 33., 81., 87., 46., 50., 44., 59.,
       71., 31., 80., 43., 36., 51., 78., 52., 61., 48., 42., 86., 90.,
       83., 35., 85., 37., 93., 84., 88., 89., 40., 38., 27., 34., 41.,
       91., 39., 94., 26., 16., 28., 23., 15., 22.])

In [245]:
df["Jumping"]=df["Jumping"].astype(int)

In [246]:
df["Jumping"].dtypes

dtype('int64')

In [247]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage in Euro',
       'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Body Type', 'Real Face', 'Position', 'Jersey Number',
       'Joined', 'Contract Valid Until', 'Height', 'Weight', 'LS', 'ST', 'RS',
       'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing',
       'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing',
       'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions',
       'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause', 'Work_Rate_Attack', 'Work_Rate_Defense'],
      dtype='object')

## Stamina

In [248]:
df["Stamina"].isna().sum()

np.int64(0)

In [249]:
df["Stamina"].unique()

array([64., 55., 61., 74., 50., 48., 39., 30., 34., 54., 41., 43., 47.,
       32., 40., 69., 27., 79., 66., 31., 26., 76., 38., 89., 80., 75.,
       53., 65., 60., 88., 29., 57., 28., 45., 22., 72., 87., 73., 62.,
       63., 46., 68., 49., 67., 33., 70., 82., 85., 25., 51., 71., 78.,
       52., 44., 23., 42., 59., 77., 19., 24., 81., 83., 35., 37., 58.,
       36., 18., 91., 21., 84., 86., 12., 16., 90., 20., 56., 94., 92.,
       15., 17., 93., 14., 95., 96., 13.])

In [250]:
df["Stamina"]=df["Stamina"].astype(int)

In [251]:
df["Stamina"].dtypes

dtype('int64')

## Strength

In [252]:
df["Strength"].isna().sum()

np.int64(0)

In [253]:
df["Strength"].unique()

array([60., 58., 65., 67., 69., 77., 82., 78., 56., 70., 74., 79., 72.,
       64., 84., 54., 76., 63., 66., 91., 55., 75., 90., 39., 62., 50.,
       57., 71., 44., 53., 86., 88., 81., 68., 61., 51., 43., 93., 41.,
       83., 85., 80., 73., 87., 59., 36., 89., 92., 34., 49., 40., 31.,
       48., 52., 35., 94., 47., 97., 46., 33., 45., 30., 42., 37., 32.,
       27., 26., 38., 28., 29., 24., 17., 95., 25.])

In [254]:
df["Strength"]=df["Strength"].astype(int)

In [255]:
df["Strength"].dtypes

dtype('int64')

## LongShots

In [256]:
df["LongShots"].isna().sum()

np.int64(0)

In [257]:
df["LongShots"].unique()

array([71., 76., 65., 66., 40., 13., 11., 47., 67., 73., 23., 72., 69.,
       31., 77., 86., 16., 68., 59., 18., 19., 58., 36., 63., 15., 26.,
       51., 53., 17., 75., 32., 12., 70., 80., 93., 55., 74.,  8., 50.,
       48., 56., 82., 64., 43., 39., 60., 14., 52., 33., 57., 78., 61.,
       62., 44., 20., 54., 49.,  9., 30., 79., 21., 22.,  7., 24., 35.,
       41., 83., 28., 34., 25., 27., 10., 45., 46., 37., 42., 94., 89.,
       38., 87., 29., 90., 84., 81.,  6., 91., 85.,  5., 88.,  3.,  4.])

In [258]:
df["LongShots"]=df["LongShots"].astype(int)

In [259]:
df["LongShots"].dtypes

dtype('int64')

## Aggression

In [ ]:
df["Aggression"].isna().sum()

In [ ]:
df["Aggression"].unique()

In [ ]:
df["Aggression"]=df["Aggression"].astype(int)

In [ ]:
df["Aggression"].dtypes

## Interceptions

In [261]:
df["Interceptions"].isna().sum()

np.int64(0)

In [262]:
df["Interceptions"].unique()

array([71., 66., 70., 63., 81., 28., 26., 53., 76., 54., 22., 68., 83.,
       37., 23., 43., 56., 36., 17., 47., 29., 60., 62., 45., 19., 11.,
       73., 24., 41., 46., 72., 69., 33., 27., 21., 40., 65., 20., 74.,
       35., 25., 79., 42., 84., 55., 18., 14., 82., 59., 51., 38., 44.,
       32., 15., 58., 61., 31., 87., 34., 50., 77., 13., 39., 16., 49.,
       30., 67., 12., 64., 85., 86., 48., 88., 75., 80., 90., 78., 10.,
       52., 57.,  7.,  9., 89., 92.,  6.,  8.,  5.,  4.,  3.])

In [263]:
df["Interceptions"]=df["Interceptions"].astype(int)

In [264]:
df["Interceptions"].dtypes

dtype('int64')

## Positioning

In [265]:
df["Positioning"].isna().sum()

np.int64(0)

In [266]:
df["Positioning"].unique()

array([72., 81., 63., 61., 55., 29., 12., 69., 62., 32., 65., 16., 58.,
       71., 84., 14., 66., 50., 11., 20., 19., 54., 43., 10., 17., 13.,
       40., 18., 64., 60., 77., 56., 78., 74., 95., 42., 15.,  9., 68.,
       59., 85., 31., 76., 27., 28., 75., 79., 47.,  8., 80., 67., 41.,
       38., 70., 33., 44.,  7., 37., 49., 25., 57., 48., 26., 87., 45.,
       39., 30., 86., 83., 53., 73., 35.,  6., 36., 52., 23., 22., 46.,
       82., 51., 21., 24., 92., 34., 94., 88., 89., 93., 90.,  3.,  5.,
       91.,  4.,  2.])

In [267]:
df["Positioning"]=df["Positioning"].astype(int)

In [268]:
df["Positioning"].dtypes

dtype('int64')

## Vision

In [269]:
df["Vision"].isna().sum()

np.int64(0)

In [270]:
df["Vision"].unique()

array([73., 93., 86., 65., 64., 46., 50., 40., 68., 61., 77., 55., 83.,
       25., 72., 80., 47., 69., 51., 37., 19., 15., 63., 23., 71., 49.,
       56., 57., 41., 52., 53., 38., 43., 58., 34., 66., 45., 22., 84.,
       82., 67., 87., 78., 36., 60., 39., 62., 74., 48., 70., 79., 31.,
       75., 26., 76., 44., 30., 42., 59., 21., 11., 33., 18., 28., 10.,
       17., 35., 32., 14., 27., 54., 81., 24., 20., 12., 85., 94., 91.,
       92., 29., 88., 16., 89., 90., 13.])

In [271]:
df["Vision"]=df["Vision"].astype(int)

In [272]:
df["Vision"].dtypes

dtype('int64')

## Penalties

In [273]:
df["Penalties"].isna().sum()

np.int64(0)

In [274]:
df["Penalties"].unique()

array([75., 71., 85., 65., 66., 35., 22., 23., 68., 60., 47., 76., 24.,
       72., 30., 74., 78., 46., 67., 31., 13., 63., 45., 20., 33., 58.,
       15.,  7., 27., 56., 29., 64., 40., 25., 54., 81.,  9., 12., 11.,
       83., 69., 59., 89., 53., 49., 51., 14., 36., 62., 18., 50., 82.,
       70., 37., 77., 73., 42., 21., 17., 80., 16., 86., 79., 38., 26.,
       55., 61., 57., 88., 19., 44., 52., 84., 41., 43., 48., 34., 10.,
       87., 32., 39., 28., 90., 92., 91.,  5.,  8.])

In [275]:
df["Penalties"]=df["Penalties"].astype(int)

In [276]:
df["Penalties"].dtypes

dtype('int64')

## Composure

In [277]:
df["Composure"].isna().sum()

np.int64(0)

In [278]:
df["Composure"].unique()

array([79., 89., 80., 68., 82., 70., 59., 69., 71., 81., 75., 85., 55.,
       60., 61., 48., 43., 40., 63., 72., 51., 54., 52., 56., 57., 67.,
       65., 95., 77., 84., 64., 86., 38., 45., 73., 90., 76., 58., 66.,
       53., 78., 46., 62., 87., 74., 41., 49., 44., 50., 83., 30., 47.,
       31., 88., 20., 39., 42., 37., 96., 34., 35., 92., 93., 12., 36.,
       13., 26., 25., 32., 91., 23., 28., 18., 94., 15., 33., 22., 24.,
       21., 27., 29., 14.])

In [279]:
df["Composure"]=df["Composure"].astype(int)

In [280]:
df["Composure"].dtypes

dtype('int64')

## Marking

In [282]:
df["Marking"].isna().sum()

np.int64(0)

In [283]:
df["Marking"].unique()

array([70., 67., 65., 74., 59., 77., 13.,  9., 24., 41., 72., 58., 80.,
       73., 55., 30., 12., 60., 40., 15., 51., 20., 11., 18., 21., 10.,
       23., 76., 29., 48., 28., 47., 42., 36., 14., 38., 37., 82., 64.,
       35., 52., 56., 25., 45., 39., 62., 61., 66., 34., 22., 44., 68.,
       19., 71., 63., 69., 90., 57., 32., 17., 50., 78.,  3., 43., 16.,
        7., 75.,  8., 79., 86., 85., 26., 94., 31., 46., 33., 93., 53.,
       87., 27., 81., 54., 91., 83., 89., 84., 49., 88.,  5.,  4.,  6.,
       92.])

In [284]:
df["Marking"]=df["Marking"].astype(int)

In [285]:
df["Marking"].dtypes

dtype('int64')

In [281]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage in Euro',
       'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Body Type', 'Real Face', 'Position', 'Jersey Number',
       'Joined', 'Contract Valid Until', 'Height', 'Weight', 'LS', 'ST', 'RS',
       'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing',
       'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing',
       'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions',
       'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause', 'Work_Rate_Attack', 'Work_Rate_Defense'],
      dtype='object')

## StandingTackle

In [286]:
df["StandingTackle"].isna().sum()

np.int64(0)

In [287]:
df["StandingTackle"].unique()

array([43., 57., 67., 71., 66., 80., 11., 15., 20., 36., 70., 56., 73.,
       76., 26., 13., 51., 46., 31., 14., 17., 63., 69., 12., 74., 16.,
       19., 23., 32., 22., 48., 77., 35., 29., 62., 33., 10., 40., 38.,
        8., 68., 37., 41., 27., 78., 60., 72., 58., 61., 54., 34., 49.,
       52., 18., 59., 25., 82., 21., 65., 64., 55.,  9., 24., 44., 84.,
       28., 42., 85., 50., 75., 53., 39., 30., 79., 90., 45., 93., 81.,
       47., 86., 92., 87., 83., 89., 88.,  6., 91.,  7.,  5.,  2.])

In [288]:
df["StandingTackle"]=df["StandingTackle"].astype(int)

In [289]:
df["StandingTackle"].dtypes

dtype('int64')

## SlidingTackle

In [290]:
df["SlidingTackle"].isna().sum()

np.int64(0)

In [291]:
df["SlidingTackle"].unique()

array([40., 56., 60., 66., 62., 76., 11., 14., 19., 34., 59., 68., 43.,
       13., 65., 70., 38., 26., 12., 45., 31., 17., 53., 18., 50., 69.,
       22., 24., 46., 74., 20., 37., 32., 23., 29., 64., 63., 15., 71.,
       39., 25., 58., 52., 55., 51., 48., 41., 47., 16., 10., 73., 80.,
       54., 21., 67., 27., 36., 49., 82., 28.,  9., 72., 75.,  8., 33.,
       30., 79., 35., 57., 90., 84., 78., 77., 61., 44., 42., 91., 85.,
       81., 86., 83., 88.,  4.,  6., 89., 87.,  7.,  3.])

In [292]:
df["SlidingTackle"]=df["SlidingTackle"].astype(int)

In [293]:
df["SlidingTackle"].dtypes

dtype('int64')

## GKDiving

In [294]:
df["GKDiving"].isna().sum()

np.int64(0)

In [295]:
df["GKDiving"].unique()

array([ 9.,  6.,  7.,  5., 11., 88., 71., 12., 87., 15., 10., 64., 14.,
       66., 57., 13.,  8., 76., 72., 16., 70., 61., 68., 67., 69., 80.,
       65., 54.,  3., 75., 78., 74., 81., 62., 48., 59., 63., 45., 32.,
       56., 73.,  1., 79.,  4., 84., 60., 55., 82., 77., 58., 22., 17.,
       52.,  2., 86., 90., 83., 27., 85., 46., 37., 26., 53., 51., 23.,
       49., 19., 18., 50., 47.])

In [296]:
df["GKDiving"]=df["GKDiving"].astype(int)

In [297]:
df["GKDiving"].dtypes

dtype('int64')

## GKHandling

In [298]:
df["GKHandling"].isna().sum()

np.int64(0)

In [299]:
df["GKHandling"].unique()

array([12., 13., 11., 15.,  9.,  6., 87., 72., 14.,  7., 74.,  8., 70.,
       56., 69., 73., 76., 54., 66., 58., 65., 16., 83., 64., 63., 10.,
        3., 82., 67., 62., 71., 48., 61., 33., 60.,  4.,  1., 52., 68.,
       75.,  5., 77., 79., 59.,  2., 57., 80., 81., 22., 86., 78., 84.,
       25., 55., 49., 32., 53., 91., 85., 92., 51., 46., 45., 17., 50.,
       47., 43., 18., 19., 44.])

In [300]:
df["GKHandling"]=df["GKHandling"].astype(int)

In [301]:
df["GKHandling"].dtypes

dtype('int64')

## GKKicking

In [302]:
df["GKKicking"].isna().sum()

np.int64(0)

In [303]:
df["GKKicking"].unique()

array([13.,  6.,  7., 10.,  8., 74., 76., 16., 58.,  9., 14., 11., 52.,
       12., 65., 57., 66., 69., 72., 54., 63., 62., 15., 82., 67., 71.,
       59., 68.,  3., 73., 70., 64., 56., 60., 44., 38., 55., 47., 35.,
        5.,  1.,  2., 81., 61., 50.,  4., 53., 75., 78., 46., 45., 28.,
       17., 77., 91., 33., 49., 85., 31., 79., 80., 41., 36., 21., 87.,
       48., 20., 83., 51., 88., 30., 84., 18., 42., 23., 40., 19., 43.])

In [304]:
df["GKKicking"]=df["GKKicking"].astype(int)

In [305]:
df["GKKicking"].dtypes

dtype('int64')

## GKPositioning

In [306]:
df["GKPositioning"].isna().sum()

np.int64(0)

In [307]:
df["GKPositioning"].unique()

array([11., 13., 14.,  6.,  9., 90., 73., 10.,  7., 82.,  8.,  5., 77.,
       15., 68., 56., 16., 70., 72., 12., 81., 63., 66., 71., 62., 61.,
       78.,  3., 83., 74., 76., 69., 64., 60., 65., 49., 32., 53.,  1.,
       57., 86., 75., 67., 79., 80., 85.,  2., 55.,  4., 59., 58., 24.,
       17., 89., 87., 33., 84., 52., 48., 27., 54., 88., 18., 50., 39.,
       47., 46., 51., 23., 45., 44., 20., 19., 38., 41., 40., 42., 43.])

In [308]:
df["GKPositioning"]=df["GKPositioning"].astype(int)

In [309]:
df["GKPositioning"].dtypes

dtype('int64')

## GKReflexes

In [310]:
df["GKReflexes"].isna().sum()

np.int64(0)

In [311]:
df["GKReflexes"].unique()

array([11.,  7.,  8., 13.,  5., 83., 73.,  9.,  6., 16., 14., 84., 12.,
       10., 15., 64., 56., 76., 70., 66., 55., 71., 75., 82., 53., 51.,
       67.,  3., 65., 77., 79., 69., 74., 68., 44., 60., 46., 34., 58.,
        4.,  1., 63., 72.,  2., 59., 62., 78., 57., 81., 23., 61., 17.,
       52., 89., 80., 88., 87., 92., 37., 85., 54., 21., 30., 86., 90.,
       94., 25., 50., 45., 48., 19., 18., 20., 47., 49.])

In [312]:
df["GKReflexes"]=df["GKReflexes"].astype(int)

In [313]:
df["GKReflexes"].dtypes

dtype('int64')

In [314]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage in Euro',
       'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Body Type', 'Real Face', 'Position', 'Jersey Number',
       'Joined', 'Contract Valid Until', 'Height', 'Weight', 'LS', 'ST', 'RS',
       'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing',
       'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing',
       'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions',
       'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause', 'Work_Rate_Attack', 'Work_Rate_Defense'],
      dtype='object')

## Release Clause

In [317]:
df["Release Clause"].isna().sum()

np.int64(11)

In [318]:
df["Release Clause"].unique()

array(['\x801.1M', '\x8026.9M', '\x807.6M', ..., '\x80918K', '\x80177K',
       '\x80542K'], shape=(1230,), dtype=object)

In [320]:
df.dropna(subset="Release Clause", inplace=True)

In [321]:
df["Release Clause"].isna().sum()

np.int64(0)

In [322]:
df.head()

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,Work_Rate_Attack,Work_Rate_Defense
0,16,Luis García,37.0,https://cdn.sofifa.org/players/4/19/16.png,Spain,https://cdn.sofifa.org/flags/45.png,71,71,KAS Eupen,https://cdn.sofifa.org/teams/2/light/2013.png,...,43,40,9,12,13,11,11,1.1M,Medium,Medium
1,41,Iniesta,34.0,https://cdn.sofifa.org/players/4/19/41.png,Spain,https://cdn.sofifa.org/flags/45.png,86,86,Vissel Kobe,https://cdn.sofifa.org/teams/2/light/101146.png,...,57,56,6,13,6,13,7,26.9M,High,Medium
2,80,E. Belözo?lu,37.0,https://cdn.sofifa.org/players/4/19/80.png,Turkey,https://cdn.sofifa.org/flags/48.png,79,79,Medipol Ba?ak?ehir FK,https://cdn.sofifa.org/teams/2/light/101014.png,...,67,60,7,11,7,14,8,7.6M,Medium,Medium
3,164,G. Pinzi,37.0,https://cdn.sofifa.org/players/4/19/164.png,Italy,https://cdn.sofifa.org/flags/27.png,70,70,Padova,https://cdn.sofifa.org/teams/2/light/110912.png,...,71,66,5,15,7,6,13,372K,Low,High
4,657,D. Vaughan,35.0,https://cdn.sofifa.org/players/4/19/657.png,Wales,https://cdn.sofifa.org/flags/50.png,66,66,Notts County,https://cdn.sofifa.org/teams/2/light/1937.png,...,66,62,6,9,10,9,7,263K,Medium,High

In [323]:
df=df.rename(columns={"Release Clause":"Release Clause in Euro"})

In [324]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value in Euro', 'Wage in Euro',
       'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Body Type', 'Real Face', 'Position', 'Jersey Number',
       'Joined', 'Contract Valid Until', 'Height', 'Weight', 'LS', 'ST', 'RS',
       'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing',
       'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing',
       'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions',
       'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause in Euro', 'Work_Rate_Attack', 'Work_Rate_Defense'],
      dtype='object')

In [326]:
df["Release Clause in Euro"] = (df["Release Clause in Euro"].str.replace("\x80", "", regex=False).str.replace("K", "000", regex=False).str.replace("M", "000000").astype(float).astype(int))

In [328]:
df["Release Clause in Euro"].isna().sum()

np.int64(0)

In [329]:
df["Release Clause in Euro"].value_counts()

Release Clause in Euro
1         2908
2          994
3          548
4          406
5          338
          ...
561000       1
301000       1
516000       1
968000       1
542000       1
Name: count, Length: 882, dtype: int64

In [330]:
df["Release Clause in Euro"].dtypes

dtype('int64')

In [331]:
df.to_csv("FIFA_19_cleared_data.csv", index=False)