In [71]:
# its a data manpulation 

import pandas as pd

In [72]:
# DataFrame: converts dict/json/array so on.. data into dataframe

dict1 = {"name" : ["paritosh","sumit","santosh"],
         "age" : [20,21,20]
        }

df = pd.DataFrame(dict1)
df

       name  age
0  paritosh   20
1     sumit   21
2   santosh   20

In [73]:
list1= (1,2,3,4,5)

list_df = pd.DataFrame(list1,columns = ["Numbers"])

list_df

   Numbers
0        1
1        2
2        3
3        4
4        5

In [75]:
# method 2: load_csv: load the dataset 
# df = pd.read_csv("C:/Users/bhoom/Downloads/dataset.csv")


df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\dataset.csv")

df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [76]:
# method 3: head() : display top 5 rows

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
# method 4: tail() : show last 5 rows

df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [7]:
df.tail(2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [8]:
df.head(1)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1

In [9]:
# method 5: sample(): display random rows

df.sample(2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
97,52,1,0,108,233,1,1,147,0,0.1,2,3,3,1
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3,0

In [10]:
# method 6: shape : check the size of dataset

df.shape
#(rows,col)

(303, 14)

In [11]:
# method 7: info(): check the info about the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [12]:
# method 8: columns: check the column names

df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [13]:
# method 9: dtypes : check the colums data type

df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [14]:
# method 10: isnull() : check the missing values

df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [15]:
# method 11: isna() : check the missing value

df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [16]:
# method 12: select_dtype : 

Target = df['target']
Target

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [17]:
df[["age","sex","cp"]]

     age  sex  cp
0     63    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
..   ...  ...  ..
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

In [18]:
# method 13 : select_dtype

df.select_dtypes(include = ["int","float"]).columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [19]:
# method 14: describe() : show the stats
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [20]:
# method 15: drop() : drop columns

df.drop("exang",axis = 1, inplace = True)

In [21]:
# method 16 :  duplicated():
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Length: 303, dtype: bool

In [22]:
# method 17 : drop_duplicates():
df.drop_duplicates(inplace = True)
df.drop_duplicates().sum()

age         16435.0
sex           206.0
cp            291.0
trestbps    39744.0
chol        74443.0
fbs            45.0
restecg       159.0
thalach     45170.0
oldpeak       315.0
slope         422.0
ca            217.0
thal          699.0
target        164.0
dtype: float64

In [23]:
# method 18 : value_counts():

df["target"].value_counts(dropna = True)

target
1    164
0    138
Name: count, dtype: int64

### RENAMEING AND TYPECONVERSION

In [24]:
# method 19: rename() : to change the column name 

df.rename(columns = {"target":"result","sex":"gender"},inplace = True)

In [25]:
df.head(2)

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,oldpeak,slope,ca,thal,result
0,63,1,3,145,233,1,0,150,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,3.5,0,0,2,1

In [26]:
# rename the rows index:

df.rename(index ={0:"first",1:"2nd"})

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,oldpeak,slope,ca,thal,result
first,63,1,3,145,233,1,0,150,2.3,0,0,1,1
2nd,37,1,2,130,250,0,1,187,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0.0,1,1,2,0

In [27]:
df.columns = [col.title() for col in df.columns]
df.columns

Index(['Age', 'Gender', 'Cp', 'Trestbps', 'Chol', 'Fbs', 'Restecg', 'Thalach',
       'Oldpeak', 'Slope', 'Ca', 'Thal', 'Result'],
      dtype='object')

In [28]:
# method 20 : add prefix:
df.add_prefix("Col_")

,Col_Age,Col_Gender,Col_Cp,Col_Trestbps,Col_Chol,Col_Fbs,Col_Restecg,Col_Thalach,Col_Oldpeak,Col_Slope,Col_Ca,Col_Thal,Col_Result
0,63,1,3,145,233,1,0,150,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0.0,1,1,2,0

In [29]:
# method 21: astype(): can convert into diff type

#df['Col_Oldpeak']=df['Col_Oldpeak'].astype("int")

In [30]:
import numpy as np

dicts = {"Age":[12,14,15,15,16,np.nan,56,70,71,np.nan,np.nan]}
df =pd.DataFrame(dicts)
df.head()

    Age
0  12.0
1  14.0
2  15.0
3  15.0
4  16.0

In [31]:
# method 22 : fillna()

df["Age"].fillna('unknow',inplace = True)
df

C:\Users\bhoom\AppData\Local\Temp\ipykernel_33592\2063943418.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna('unknow',inplace = True)
C:\Users\bhoom\AppData\Local\Temp\ipykernel_33592\2063943418.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unknow' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df["Age"].fillna('unknow',inplace = True)

       Age
0     12.0
1     14.0
2     15.0
3     15.0
4     16.0
5   unknow
6     56.0
7     70.0
8     71.0
9   unknow
10  unknow

In [32]:
dicts = {"Age":[12,14,15,15,16,np.nan,56,70,71,np.nan,np.nan]}
df =pd.DataFrame(dicts)
df

     Age
0   12.0
1   14.0
2   15.0
3   15.0
4   16.0
5    NaN
6   56.0
7   70.0
8   71.0
9    NaN
10   NaN

In [33]:
age_mean = int(df['Age'].mean())
age_mean

33

In [34]:
# 23 fill the missing val using mean of age:
df['Age'] = df['Age'].fillna(age_mean)

df['Age'] = df['Age'].astype("int")
df['Age']

0     12
1     14
2     15
3     15
4     16
5     33
6     56
7     70
8     71
9     33
10    33
Name: Age, dtype: int64

In [35]:
dicts = {"Age":[12,14,15,15,16,np.nan,56,70,71,np.nan,np.nan]}
df =pd.DataFrame(dicts)
df

     Age
0   12.0
1   14.0
2   15.0
3   15.0
4   16.0
5    NaN
6   56.0
7   70.0
8   71.0
9    NaN
10   NaN

In [36]:
# 24 fill the missing val using age meadian

age_median = df['Age'].median()
age_median

15.5

In [37]:
df['Age'] = df['Age'].fillna(age_median)
df['Age'] = df['Age'].astype("int")
df['Age']

0     12
1     14
2     15
3     15
4     16
5     15
6     56
7     70
8     71
9     15
10    15
Name: Age, dtype: int64

In [38]:
# method 23 : ffill

df1=df['Age'].fillna(method = "ffill")
df1

C:\Users\bhoom\AppData\Local\Temp\ipykernel_33592\4117828326.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1=df['Age'].fillna(method = "ffill")

0     12
1     14
2     15
3     15
4     16
5     15
6     56
7     70
8     71
9     15
10    15
Name: Age, dtype: int64

In [39]:
# method 24: bfill:

#df['Age'].fillna=(method = "bfill")
#df

In [40]:
dicts = {"Age":[12,14,15,15,16,np.nan,56,70,71,np.nan,np.nan]}
df =pd.DataFrame(dicts)
df

     Age
0   12.0
1   14.0
2   15.0
3   15.0
4   16.0
5    NaN
6   56.0
7   70.0
8   71.0
9    NaN
10   NaN

In [41]:
# method 25: dropna()
df.dropna(inplace=True)
df

    Age
0  12.0
1  14.0
2  15.0
3  15.0
4  16.0
6  56.0
7  70.0
8  71.0

In [42]:
# method 26: notnull() : check the non missing val
df.notnull().sum()

Age    8
dtype: int64

In [43]:
df[df.notnull()]

    Age
0  12.0
1  14.0
2  15.0
3  15.0
4  16.0
6  56.0
7  70.0
8  71.0

In [44]:
# method 27: replace(): replace val with the other val

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\Bank_customer_churn.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [45]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [46]:
# df['Gender'].replace(
df.replace({'Gender':{'Male':'1','Female':'0'}},inplace=True)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [47]:
# method 28: sort_value() -- sort the column val:

df.sort_values('Age')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [48]:
df.sort_values('Age',ascending = False)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
6443,6444,15764927,Rogova,753,France,1,92,3,121513.31,1,0,1,195563.99,0
6759,6760,15660878,T'ien,705,France,1,92,1,126076.24,2,1,1,34436.83,0
2458,2459,15813303,Rearick,513,Spain,1,88,10,0.00,2,1,1,52952.24,0
3033,3034,15578006,Yao,787,France,0,85,10,0.00,2,1,1,116537.96,0
3387,3388,15798024,Lori,537,Germany,1,84,8,92242.34,1,1,1,186235.98,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9782,9783,15728829,Weigel,509,France,1,18,7,102983.91,1,1,0,171770.58,0
2141,2142,15758372,Wallace,674,France,1,18,7,0.00,2,1,1,55753.12,1
9501,9502,15634146,Hou,835,Germany,1,18,2,142872.36,1,1,1,117632.63,0
9520,9521,15673180,Onyekaozulu,727,Germany,0,18,2,93816.70,2,1,0,126172.11,0
1619,1620,15770309,McDonald,656,France,1,18,10,151762.74,1,0,1,127014.32,0

In [49]:
# method 29: sort()-- 

df.sort_index()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [50]:
df.sort_index(ascending = False)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9999,10000,15628319,Walker,792,France,0,28,4,130142.79,1,1,0,38190.78,0
9998,9999,15682355,Sabbatini,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9997,9998,15584532,Liu,709,France,0,36,7,0.00,1,0,1,42085.58,1
9996,9997,15569892,Johnstone,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9995,9996,15606229,Obijiaku,771,France,1,39,5,0.00,2,1,0,96270.64,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,15737888,Mitchell,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
3,4,15701354,Boni,699,France,0,39,1,0.00,2,0,0,93826.63,0
2,3,15619304,Onio,502,France,0,42,8,159660.80,3,1,0,113931.57,1
1,2,15647311,Hill,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
0,1,15634602,Hargrave,619,France,0,42,2,0.00,1,1,1,101348.88,1

### GROUPING AND AGGREGATION

In [51]:
# checking the avg 
df.groupby("Gender")['Age'].mean()

Gender
0    39.238389
1    38.658237
Name: Age, dtype: float64

In [52]:
df.groupby(["Geography","Gender"])['Age'].mean()

Geography  Gender
France     0         38.773994
           1         38.296404
Germany    0         40.154233
           1         39.424772
Spain      0         39.199265
           1         38.649135
Name: Age, dtype: float64

In [53]:
df.groupby("Geography")['CreditScore'].mean()

Geography
France     649.668329
Germany    651.453567
Spain      651.333872
Name: CreditScore, dtype: float64

In [54]:
df["Age_Level"]=["Older" if age > 45 else "Young" for age in df['Age']]

In [55]:
# dict
dicts1= {"Age":["12","20","13","14","paritosh","70-1","8.0","90*2","santosh"]}

In [56]:
# convert into dataframe:

df=pd.DataFrame(dicts1)
df

        Age
0        12
1        20
2        13
3        14
4  paritosh
5      70-1
6       8.0
7      90*2
8   santosh

In [57]:
df.dtypes

Age    object
dtype: object

In [58]:
# to_numeric() :
# syntax: pd.to_numeric("col",error = "coerce")

In [59]:
# method 30: to_numeric()

df["Age"]= pd.to_numeric(df["Age"],errors = "coerce")
df

    Age
0  12.0
1  20.0
2  13.0
3  14.0
4   NaN
5   NaN
6   8.0
7   NaN
8   NaN

In [60]:
# Date columns Handling

df= pd.DataFrame({"date":["2024-01-15", "2024-02-20", "2024-03-25"]})
df

         date
0  2024-01-15
1  2024-02-20
2  2024-03-25

In [61]:
df.dtypes

date    object
dtype: object

In [62]:
# to_datetime(df[col]7

In [63]:
df["date"] = pd.to_datetime(df['date'], yearfirst=True)
df

        date
0 2024-01-15
1 2024-02-20
2 2024-03-25

In [64]:
df['days'] = df["date"].dt.day
df['month'] = df["date"].dt.month
df['year'] = df["date"].dt.year
df

        date  days  month  year
0 2024-01-15    15      1  2024
1 2024-02-20    20      2  2024
2 2024-03-25    25      3  2024

In [65]:
# df.to_csv("filename.csv")

df = pd.DataFrame({"Price": ["$23090","$65434","$8929","$9902"]})
df

    Price
0  $23090
1  $65434
2   $8929
3   $9902

In [66]:
# step 1 : remove the $ 
df["Price"] = df["Price"].str.replace("$","")
df

   Price
0  23090
1  65434
2   8929
3   9902

In [67]:
df.dtypes

Price    object
dtype: object

In [68]:
# step 2: convert into to_numeric

df["Price"] = pd.to_numeric(df["Price"], errors = "coerce")
df.dtypes

Price    int64
dtype: object

In [70]:
# method 31: apply()
# df['Score_status'] = df['CreditScore'].apply(lambda x:"Good Score" if x > 750 else "Bad score")
# df.head()

In [ ]:
# applymap():
df.applymap(

In [79]:
# method :iloc[start:stop] display 
df.iloc[2:9]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1

In [80]:
# iloc[start_row : stop_row, start_col : stop_col]
df.iloc[1:9,1:5]

   sex  cp  trestbps  chol
1    1   2       130   250
2    0   1       130   204
3    1   1       120   236
4    0   0       120   354
5    1   0       140   192
6    0   1       140   294
7    1   1       120   263
8    1   2       172   199

In [81]:
# loc[]

df.loc[1:5]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1

In [85]:
df.loc[1:5,["oldpeak"]]

   oldpeak
1      3.5
2      1.4
3      0.8
4      0.6
5      0.4

In [83]:
df.loc[1:5,["age","cp","trestbps"]]

   age  cp  trestbps
1   37   2       130
2   41   1       130
3   56   1       120
4   57   0       120
5   57   0       140

In [ ]:
df