In [1]:
import pandas as pd

data = {
    "Order_ID": [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,
                 1011,1012,1013,1014,1015,1016,1017,1018,1019,1001],

    "Order_Date": ["2026-01-05","2026-01-07","2026-01-10","2026-01-12",
                   "2026-01-15","2026-01-18","2026-01-20","2026-01-22",
                   "2026-01-25","2026-01-28","2026-02-02","2026-02-05",
                   "2026-02-08","2026-02-11","2026-02-15","2026-02-18",
                   "2026-02-20","2026-02-23","2026-02-25","2026-01-05"],

    "Customer_Name": ["Rahul","Priya","Amit","Sneha","Kiran","Ravi","Anjali",
                      "Vijay","Neha","Arjun","Rahul","Priya","Amit","Sneha",
                      "Kiran","Ravi","Anjali","Vijay","Neha","Rahul"],

    "City": ["Hyderabad","Mumbai","Delhi","Hyderabad","Bangalore","Delhi",
             "Mumbai","Hyderabad","Bangalore","Delhi","Hyderabad","Mumbai",
             "Delhi","Hyderabad","Bangalore","Delhi","Mumbai","Hyderabad",
             "Bangalore","Hyderabad"],

    "Category": ["Electronics","Fashion","Electronics","Home","Fashion",
                 "Electronics","Home","Fashion","Electronics","Home",
                 "Electronics","Fashion","Electronics","Home","Fashion",
                 "Electronics","Home","Fashion","Electronics","Electronics"],

    "Product": ["Laptop","Shoes","Headphones","Chair","Jacket","Monitor",
                "Table","Jeans","Keyboard","Sofa","Mouse","Dress","Laptop",
                "Lamp","T-Shirt","Monitor","Chair","Shoes","Headphones","Laptop"],

    "Quantity": [1,2,3,4,2,2,1,3,2,1,4,2,1,5,4,1,2,1,2,1],

    "Unit_Price": [55000,2500,1800,2200,3500,12000,8500,1800,2500,25000,
                   1200,4500,55000,900,1200,12000,2200,2500,1800,55000],

    "Discount": ["10%","5%","10%","15%","10%","5%","10%","5%","0%","15%",
                 "5%","10%","5%","10%","5%","10%","5%","10%",None,"10%"],

    "Payment_Method": ["UPI","Card","UPI","Cash","Card","UPI","Card","UPI",
                       "Cash","Card","UPI","Card","UPI","Cash","Card","UPI",
                       "Card","UPI","Cash","UPI"],

    "Customer_Rating": [4.5,4.2,4.0,4.3,4.6,4.1,4.4,3.9,4.2,4.7,
                        4.0,4.5,4.8,4.1,4.3,4.4,4.0,None,4.2,4.5],

    "Returned": ["No","No","Yes","No","No","No","Yes","No","No","No",
                 "No","No","No","Yes","No","No","No","No","Yes","No"]
}

df = pd.DataFrame(data)

df.head()

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Customer_Rating,Returned
0,1001,2026-01-05,Rahul,Hyderabad,Electronics,Laptop,1,55000,10%,UPI,4.5,No
1,1002,2026-01-07,Priya,Mumbai,Fashion,Shoes,2,2500,5%,Card,4.2,No
2,1003,2026-01-10,Amit,Delhi,Electronics,Headphones,3,1800,10%,UPI,4.0,Yes
3,1004,2026-01-12,Sneha,Hyderabad,Home,Chair,4,2200,15%,Cash,4.3,No
4,1005,2026-01-15,Kiran,Bangalore,Fashion,Jacket,2,3500,10%,Card,4.6,No

In [2]:
# 1. Load and Display the Dataset

df.head()

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Customer_Rating,Returned
0,1001,2026-01-05,Rahul,Hyderabad,Electronics,Laptop,1,55000,10%,UPI,4.5,No
1,1002,2026-01-07,Priya,Mumbai,Fashion,Shoes,2,2500,5%,Card,4.2,No
2,1003,2026-01-10,Amit,Delhi,Electronics,Headphones,3,1800,10%,UPI,4.0,Yes
3,1004,2026-01-12,Sneha,Hyderabad,Home,Chair,4,2200,15%,Cash,4.3,No
4,1005,2026-01-15,Kiran,Bangalore,Fashion,Jacket,2,3500,10%,Card,4.6,No

In [3]:
#  2. Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         20 non-null     int64
 1   Order_Date       20 non-null     object
 2   Customer_Name    20 non-null     object
 3   City             20 non-null     object
 4   Category         20 non-null     object
 5   Product          20 non-null     object
 6   Quantity         20 non-null     int64
 7   Unit_Price       20 non-null     int64
 8   Discount         19 non-null     object
 9   Payment_Method   20 non-null     object
 10  Customer_Rating  19 non-null     float64
 11  Returned         20 non-null     object
dtypes: float64(1), int64(3), object(8)
memory usage: 2.0+ KB

In [4]:
# 3. Find Missing Values

df.isna().sum()

Order_ID           0
Order_Date         0
Customer_Name      0
City               0
Category           0
Product            0
Quantity           0
Unit_Price         0
Discount           1
Payment_Method     0
Customer_Rating    1
Returned           0
dtype: int64

In [5]:
# 4. Find Duplicate Orders

df["Order_ID"].duplicated().sum()

np.int64(1)

In [6]:
# 5. Remove Duplicate Orders

df = df.drop_duplicates(subset="Order_ID", keep="first")

In [7]:
df.shape

(19, 12)

In [8]:
# 6. Calculate Revenue

df["Revenue"] = df["Quantity"] * df["Unit_Price"]

In [9]:
df[["Quantity", "Unit_Price", "Revenue"]]

    Quantity  Unit_Price  Revenue
0          1       55000    55000
1          2        2500     5000
2          3        1800     5400
3          4        2200     8800
4          2        3500     7000
5          2       12000    24000
6          1        8500     8500
7          3        1800     5400
8          2        2500     5000
9          1       25000    25000
10         4        1200     4800
11         2        4500     9000
12         1       55000    55000
13         5         900     4500
14         4        1200     4800
15         1       12000    12000
16         2        2200     4400
17         1        2500     2500
18         2        1800     3600

In [10]:
# 7. Calculate Final Amount

df["Discount"] = df["Discount"].str.replace("%", "").astype(float)

df["Final_Amount"] = df["Revenue"] - (df["Revenue"] * df["Discount"] / 100)

df[["Revenue", "Discount", "Final_Amount"]]

    Revenue  Discount  Final_Amount
0     55000      10.0       49500.0
1      5000       5.0        4750.0
2      5400      10.0        4860.0
3      8800      15.0        7480.0
4      7000      10.0        6300.0
5     24000       5.0       22800.0
6      8500      10.0        7650.0
7      5400       5.0        5130.0
8      5000       0.0        5000.0
9     25000      15.0       21250.0
10     4800       5.0        4560.0
11     9000      10.0        8100.0
12    55000       5.0       52250.0
13     4500      10.0        4050.0
14     4800       5.0        4560.0
15    12000      10.0       10800.0
16     4400       5.0        4180.0
17     2500      10.0        2250.0
18     3600       NaN           NaN

In [11]:
#  8. Find High-Value Orders

df[df["Final_Amount"] > 10000]

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Customer_Rating,Returned,Revenue,Final_Amount
0,1001,2026-01-05,Rahul,Hyderabad,Electronics,Laptop,1,55000,10.0,UPI,4.5,No,55000,49500.0
5,1006,2026-01-18,Ravi,Delhi,Electronics,Monitor,2,12000,5.0,UPI,4.1,No,24000,22800.0
9,1010,2026-01-28,Arjun,Delhi,Home,Sofa,1,25000,15.0,Card,4.7,No,25000,21250.0
12,1013,2026-02-08,Amit,Delhi,Electronics,Laptop,1,55000,5.0,UPI,4.8,No,55000,52250.0
15,1016,2026-02-18,Ravi,Delhi,Electronics,Monitor,1,12000,10.0,UPI,4.4,No,12000,10800.0

In [12]:
#  9. City Analysis

df.groupby("City")["Final_Amount"].sum()

City
Bangalore     15860.0
Delhi        111960.0
Hyderabad     72970.0
Mumbai        24680.0
Name: Final_Amount, dtype: float64

In [13]:
# 10. Category Analysis

df.groupby("Category")["Revenue"].sum()

Category
Electronics    164800
Fashion         33700
Home            51200
Name: Revenue, dtype: int64

In [14]:
# 11. Average Order Value by Payment Method

df.groupby("Payment_Method")["Final_Amount"].mean()

Payment_Method
Card     8112.857143
Cash     5510.000000
UPI     19018.750000
Name: Final_Amount, dtype: float64

In [15]:
#  12. Top 5 Products by Revenue

df.groupby("Product")["Revenue"].sum().sort_values(ascending=False).head(5)

Product
Laptop     110000
Monitor     36000
Sofa        25000
Chair       13200
Dress        9000
Name: Revenue, dtype: int64

In [16]:
# 13 Most Ordered Category

df.groupby("Category")["Quantity"].sum().sort_values(ascending=False)

Category
Electronics    16
Fashion        14
Home           13
Name: Quantity, dtype: int64

In [17]:
# 14. Customer Spending

df.groupby("Customer_Name")["Final_Amount"].sum().sort_values(ascending=False).head(10)

Customer_Name
Amit      57110.0
Rahul     54060.0
Ravi      33600.0
Arjun     21250.0
Priya     12850.0
Anjali    11830.0
Sneha     11530.0
Kiran     10860.0
Vijay      7380.0
Neha       5000.0
Name: Final_Amount, dtype: float64

In [18]:
# 15. Rating Analysis

df.groupby("Category")["Customer_Rating"].mean()

Category
Electronics    4.275
Fashion        4.300
Home           4.300
Name: Customer_Rating, dtype: float64

In [19]:
# 16. Returned Orders

df["Returned"].value_counts(normalize=True) * 100

Returned
No     78.947368
Yes    21.052632
Name: proportion, dtype: float64

In [20]:
# 17. Date Analysis

df["Order_Date"] = pd.to_datetime(df["Order_Date"])

df["Month"] = df["Order_Date"].dt.month

In [21]:
df[["Order_Date", "Month"]]

   Order_Date  Month
0  2026-01-05      1
1  2026-01-07      1
2  2026-01-10      1
3  2026-01-12      1
4  2026-01-15      1
5  2026-01-18      1
6  2026-01-20      1
7  2026-01-22      1
8  2026-01-25      1
9  2026-01-28      1
10 2026-02-02      2
11 2026-02-05      2
12 2026-02-08      2
13 2026-02-11      2
14 2026-02-15      2
15 2026-02-18      2
16 2026-02-20      2
17 2026-02-23      2
18 2026-02-25      2

In [22]:
# 18. Monthly Revenue

df.groupby("Month")["Final_Amount"].sum()

Month
1    134720.0
2     90750.0
Name: Final_Amount, dtype: float64

In [23]:
df.groupby("Month")["Final_Amount"].sum().sort_index()

Month
1    134720.0
2     90750.0
Name: Final_Amount, dtype: float64

In [24]:
# 19. Multiple Conditions

df[
    (df["Category"] == "Electronics") &
    (df["Final_Amount"] > 5000) &
    (df["Customer_Rating"] > 4)
]

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Discount,Payment_Method,Customer_Rating,Returned,Revenue,Final_Amount,Month
0,1001,2026-01-05,Rahul,Hyderabad,Electronics,Laptop,1,55000,10.0,UPI,4.5,No,55000,49500.0,1
5,1006,2026-01-18,Ravi,Delhi,Electronics,Monitor,2,12000,5.0,UPI,4.1,No,24000,22800.0,1
12,1013,2026-02-08,Amit,Delhi,Electronics,Laptop,1,55000,5.0,UPI,4.8,No,55000,52250.0,2
15,1016,2026-02-18,Ravi,Delhi,Electronics,Monitor,1,12000,10.0,UPI,4.4,No,12000,10800.0,2

In [25]:
#  20. City + Category Analysis

df.groupby(["City", "Category"])["Revenue"].sum().sort_values(ascending=False)

City       Category
Delhi      Electronics    96400
Hyderabad  Electronics    59800
Delhi      Home           25000
Mumbai     Fashion        14000
Hyderabad  Home           13300
Mumbai     Home           12900
Bangalore  Fashion        11800
           Electronics     8600
Hyderabad  Fashion         7900
Name: Revenue, dtype: int64