In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Amit", "Rahul", "Priya", "Sneha", "Vikram", "Anjali", "Kiran", "Rohit"],
    "Age": [25, 30, 28, 24, 35, 29, 31, 27],
    "City": ["Hyderabad", "Mumbai", "Delhi", "Hyderabad", "Mumbai", "Delhi", "Hyderabad", "Mumbai"],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR", "Finance", "IT"],
    "Salary": [45000, 55000, 60000, 40000, 75000, 50000, 48000, 65000],
    "Experience": [2, 5, 4, 1, 8, 3, 6, 5]
})

df

     Name  Age       City Department  Salary  Experience
0    Amit   25  Hyderabad         IT   45000           2
1   Rahul   30     Mumbai         HR   55000           5
2   Priya   28      Delhi         IT   60000           4
3   Sneha   24  Hyderabad    Finance   40000           1
4  Vikram   35     Mumbai         IT   75000           8
5  Anjali   29      Delhi         HR   50000           3
6   Kiran   31  Hyderabad    Finance   48000           6
7   Rohit   27     Mumbai         IT   65000           5

In [2]:
# 1. Display the first 5 rows.

df.head()

     Name  Age       City Department  Salary  Experience
0    Amit   25  Hyderabad         IT   45000           2
1   Rahul   30     Mumbai         HR   55000           5
2   Priya   28      Delhi         IT   60000           4
3   Sneha   24  Hyderabad    Finance   40000           1
4  Vikram   35     Mumbai         IT   75000           8

In [3]:
# 2. Display the last 3 rows.

df.tail()

     Name  Age       City Department  Salary  Experience
3   Sneha   24  Hyderabad    Finance   40000           1
4  Vikram   35     Mumbai         IT   75000           8
5  Anjali   29      Delhi         HR   50000           3
6   Kiran   31  Hyderabad    Finance   48000           6
7   Rohit   27     Mumbai         IT   65000           5

In [4]:
# 3. Find the number of rows and columns.

df.shape

(8, 6)

In [5]:
# 4. Display all column names.

df.columns

Index(['Name', 'Age', 'City', 'Department', 'Salary', 'Experience'], dtype='object')

In [6]:
for i in df.columns:
    print(i)

Name
Age
City
Department
Salary
Experience

In [10]:
# 5. Display the data types of all columns.

df.dtypes

Name          object
Age            int64
City          object
Department    object
Salary         int64
Experience     int64
dtype: object

In [11]:
# 6. Select only the Name column.

df["Name"]

0      Amit
1     Rahul
2     Priya
3     Sneha
4    Vikram
5    Anjali
6     Kiran
7     Rohit
Name: Name, dtype: object

In [13]:
# 7. Select Name, Department, and Salary.

df[["Name","Department","Salary"]]

     Name Department  Salary
0    Amit         IT   45000
1   Rahul         HR   55000
2   Priya         IT   60000
3   Sneha    Finance   40000
4  Vikram         IT   75000
5  Anjali         HR   50000
6   Kiran    Finance   48000
7   Rohit         IT   65000

In [15]:
# 8. Find employees whose Salary is greater than 50000.

df[df["Salary"]>50000]

     Name  Age    City Department  Salary  Experience
1   Rahul   30  Mumbai         HR   55000           5
2   Priya   28   Delhi         IT   60000           4
4  Vikram   35  Mumbai         IT   75000           8
7   Rohit   27  Mumbai         IT   65000           5

In [17]:
# 9. Find employees whose Age is less than 30.

df[df["Age"] < 30]

     Name  Age       City Department  Salary  Experience
0    Amit   25  Hyderabad         IT   45000           2
2   Priya   28      Delhi         IT   60000           4
3   Sneha   24  Hyderabad    Finance   40000           1
5  Anjali   29      Delhi         HR   50000           3
7   Rohit   27     Mumbai         IT   65000           5

In [18]:
# 10. Find employees who work in the IT department.

df[df["Department"] == "IT"]

     Name  Age       City Department  Salary  Experience
0    Amit   25  Hyderabad         IT   45000           2
2   Priya   28      Delhi         IT   60000           4
4  Vikram   35     Mumbai         IT   75000           8
7   Rohit   27     Mumbai         IT   65000           5

In [19]:
# 11. Find employees who live in Hyderabad.

df[df["City"] == "Hyderabad"]

    Name  Age       City Department  Salary  Experience
0   Amit   25  Hyderabad         IT   45000           2
3  Sneha   24  Hyderabad    Finance   40000           1
6  Kiran   31  Hyderabad    Finance   48000           6

In [20]:
# 12. Find employees whose salary is greater than 50000 AND experience is greater than 4.

df[(df["Salary"] > 50000) & (df["Experience"] > 4)]

     Name  Age    City Department  Salary  Experience
1   Rahul   30  Mumbai         HR   55000           5
4  Vikram   35  Mumbai         IT   75000           8
7   Rohit   27  Mumbai         IT   65000           5

In [21]:
# 13. Find the average salary.

df["Salary"].mean()

np.float64(54750.0)

In [22]:
# 14. Find the highest salary.

df["Salary"].max()

75000

In [23]:
# 15. Find the employee who has the highest salary.

df[df["Salary"] == df["Salary"].max()]

     Name  Age    City Department  Salary  Experience
4  Vikram   35  Mumbai         IT   75000           8

In [24]:
# 16. Sort the DataFrame by Salary from lowest to highest.

df.sort_values("Salary")

     Name  Age       City Department  Salary  Experience
3   Sneha   24  Hyderabad    Finance   40000           1
0    Amit   25  Hyderabad         IT   45000           2
6   Kiran   31  Hyderabad    Finance   48000           6
5  Anjali   29      Delhi         HR   50000           3
1   Rahul   30     Mumbai         HR   55000           5
2   Priya   28      Delhi         IT   60000           4
7   Rohit   27     Mumbai         IT   65000           5
4  Vikram   35     Mumbai         IT   75000           8

In [25]:
# 17. Sort the DataFrame by Salary from highest to lowest.

df.sort_values("Salary", ascending=False)

     Name  Age       City Department  Salary  Experience
4  Vikram   35     Mumbai         IT   75000           8
7   Rohit   27     Mumbai         IT   65000           5
2   Priya   28      Delhi         IT   60000           4
1   Rahul   30     Mumbai         HR   55000           5
5  Anjali   29      Delhi         HR   50000           3
6   Kiran   31  Hyderabad    Finance   48000           6
0    Amit   25  Hyderabad         IT   45000           2
3   Sneha   24  Hyderabad    Finance   40000           1

In [26]:
# 18. Count how many employees are in each department.

df["Department"].value_counts()

Department
IT         4
HR         2
Finance    2
Name: count, dtype: int64

In [27]:
# 19. Find the average salary for each department.

df.groupby("Department")["Salary"].mean()

Department
Finance    44000.0
HR         52500.0
IT         61250.0
Name: Salary, dtype: float64

In [28]:
# 20. Find the average salary for each city.

df.groupby("City")["Salary"].mean()

City
Delhi        55000.000000
Hyderabad    44333.333333
Mumbai       65000.000000
Name: Salary, dtype: float64